import type { Metadata } from "next";
import { LegalDocument, LegalList, LegalSection } from "../legal/LegalDocument";
export const metadata: Metadata = { title: "Third-Party Provider Notice — Stratxcel", description: "How third-party platforms and subprocessors support Stratxcel services." };
export default function ThirdPartyProvidersPage() { return <LegalDocument eyebrow="Transparency" title="Third-Party Provider Notice" intro="Stratxcel relies on external providers and connects to services selected by clients. This Notice explains the resulting responsibilities without claiming integrations that are not actually configured.">
  <LegalSection title="Provider categories"><LegalList><li>Cloud hosting, content delivery, database, storage, authentication, monitoring, and analytics.</li><li>AI model, document-processing, automation, and communications providers.</li><li>Social networks, advertising platforms, messaging services, search and business-profile platforms.</li><li>Payment gateways, banks, domain registrars, registries, DNS, certificate, hosting, and email providers.</li><li>Support, professional advisory, security, and compliance vendors.</li></LegalList></LegalSection>
  <LegalSection title="Independent terms"><p>Each provider controls its services, policies, permissions, data use, pricing, reviews, quotas, and availability. Its terms and privacy notice apply independently. Connecting an account authorizes the exchanges needed for the selected feature. You must maintain provider accounts, permissions, consents, payment methods, and compliance.</p></LegalSection>
  <LegalSection title="Changes and failures"><p>Providers may change or withdraw APIs and features, reject content, suspend accounts, delay domains or payments, or experience outages. We may adapt, replace, restrict, or discontinue affected functionality. We do not guarantee third-party approval, access, delivery, ranking, reach, verification, registration, settlement, or uptime.</p></LegalSection>
  <LegalSection title="Subprocessor transparency"><p>A verified production list should identify material providers, purpose, and processing location where appropriate. <strong>[PLACEHOLDER — publish the approved production provider/subprocessor list after confirming actual deployments, contracts, and data regions]</strong>. Repository references or optional configuration do not by themselves mean a provider receives production data.</p></LegalSection>
</LegalDocument>; }
