import type { CanonicalActionDefinition, CanonicalActionType } from "./types.ts";

export const ACTION_CATALOG: Record<CanonicalActionType, CanonicalActionDefinition> = {
  // TECHNICAL FAMILY
  FIX_MISSING_TITLE: {
    actionType: "FIX_MISSING_TITLE",
    family: "TECHNICAL",
    title: "Generate and Insert Missing Title Tag",
    description: "Generates an intent-aligned, branded HTML <title> tag within 50-60 characters.",
    autonomyClass: "AUTO_SAFE",
    expectedImpact: "HIGH",
    riskLevel: "LOW",
    verificationMethod: "LIVE_DOM_CHECK",
    rollbackMethod: "REVERT_METADATA",
    requiresWriteCapability: true,
  },
  FIX_TITLE_LENGTH: {
    actionType: "FIX_TITLE_LENGTH",
    family: "TECHNICAL",
    title: "Optimize Title Tag Length",
    description: "Shortens or enriches title tag to fit optimal 50-60 character boundary.",
    autonomyClass: "AUTO_SAFE",
    expectedImpact: "MEDIUM",
    riskLevel: "LOW",
    verificationMethod: "LIVE_DOM_CHECK",
    rollbackMethod: "REVERT_METADATA",
    requiresWriteCapability: true,
  },
  FIX_MISSING_META_DESCRIPTION: {
    actionType: "FIX_MISSING_META_DESCRIPTION",
    family: "TECHNICAL",
    title: "Generate and Insert Meta Description",
    description: "Inserts a 120-155 character grounded summary with clear search call-to-action.",
    autonomyClass: "AUTO_SAFE",
    expectedImpact: "MEDIUM",
    riskLevel: "LOW",
    verificationMethod: "LIVE_DOM_CHECK",
    rollbackMethod: "REVERT_METADATA",
    requiresWriteCapability: true,
  },
  FIX_DUPLICATE_TITLE: {
    actionType: "FIX_DUPLICATE_TITLE",
    family: "TECHNICAL",
    title: "Disambiguate Duplicate Title Tag",
    description: "Assigns unique service/location modifiers to eliminate identical title tags across pages.",
    autonomyClass: "AUTO_SAFE",
    expectedImpact: "HIGH",
    riskLevel: "LOW",
    verificationMethod: "LIVE_DOM_CHECK",
    rollbackMethod: "REVERT_METADATA",
    requiresWriteCapability: true,
  },
  FIX_DUPLICATE_META_DESCRIPTION: {
    actionType: "FIX_DUPLICATE_META_DESCRIPTION",
    family: "TECHNICAL",
    title: "Disambiguate Duplicate Meta Description",
    description: "Generates page-specific meta descriptions for indexed URLs.",
    autonomyClass: "AUTO_SAFE",
    expectedImpact: "MEDIUM",
    riskLevel: "LOW",
    verificationMethod: "LIVE_DOM_CHECK",
    rollbackMethod: "REVERT_METADATA",
    requiresWriteCapability: true,
  },
  FIX_CANONICAL_URL: {
    actionType: "FIX_CANONICAL_URL",
    family: "TECHNICAL",
    title: "Correct Canonical Link Tag",
    description: "Ensures rel='canonical' points to the absolute, HTTPS canonical URL version.",
    autonomyClass: "AUTO_SAFE",
    expectedImpact: "HIGH",
    riskLevel: "LOW",
    verificationMethod: "LIVE_DOM_CHECK",
    rollbackMethod: "REVERT_METADATA",
    requiresWriteCapability: true,
  },
  FIX_ROBOTS_INDEXABILITY: {
    actionType: "FIX_ROBOTS_INDEXABILITY",
    family: "TECHNICAL",
    title: "Correct Robots Meta Indexability",
    description: "Removes erroneous 'noindex' or 'disallow' directives from valid commercial landing pages.",
    autonomyClass: "AUTO_WITH_POLICY",
    expectedImpact: "HIGH",
    riskLevel: "MEDIUM",
    verificationMethod: "LIVE_DOM_CHECK",
    rollbackMethod: "REVERT_METADATA",
    requiresWriteCapability: true,
  },
  FIX_BROKEN_INTERNAL_LINK: {
    actionType: "FIX_BROKEN_INTERNAL_LINK",
    family: "TECHNICAL",
    title: "Repair Broken Internal Link",
    description: "Updates 404 internal hyperlinks to point to active canonical URLs.",
    autonomyClass: "AUTO_SAFE",
    expectedImpact: "MEDIUM",
    riskLevel: "LOW",
    verificationMethod: "HTTP_STATUS_CHECK",
    rollbackMethod: "RESTORE_PAGE_SNAPSHOT",
    requiresWriteCapability: true,
  },
  FIX_IMAGE_ALT_TEXT: {
    actionType: "FIX_IMAGE_ALT_TEXT",
    family: "TECHNICAL",
    title: "Add Descriptive Image Alt Text",
    description: "Adds contextual, non-stuffed alt attributes to informational images.",
    autonomyClass: "AUTO_SAFE",
    expectedImpact: "LOW",
    riskLevel: "LOW",
    verificationMethod: "LIVE_DOM_CHECK",
    rollbackMethod: "RESTORE_PAGE_SNAPSHOT",
    requiresWriteCapability: true,
  },
  FIX_HEADING_HIERARCHY: {
    actionType: "FIX_HEADING_HIERARCHY",
    family: "TECHNICAL",
    title: "Correct Heading Hierarchy (H1/H2/H3)",
    description: "Ensures exactly one semantic H1 per page and proper sequential heading nesting.",
    autonomyClass: "AUTO_SAFE",
    expectedImpact: "MEDIUM",
    riskLevel: "LOW",
    verificationMethod: "LIVE_DOM_CHECK",
    rollbackMethod: "RESTORE_PAGE_SNAPSHOT",
    requiresWriteCapability: true,
  },
  INSERT_SCHEMA_MARKUP: {
    actionType: "INSERT_SCHEMA_MARKUP",
    family: "TECHNICAL",
    title: "Inject Verified JSON-LD Schema",
    description: "Injects valid JSON-LD structured data (Organization, LocalBusiness, Service, FAQ).",
    autonomyClass: "AUTO_SAFE",
    expectedImpact: "HIGH",
    riskLevel: "LOW",
    verificationMethod: "SCHEMA_VALIDATION",
    rollbackMethod: "REMOVE_INJECTED_TAG",
    requiresWriteCapability: true,
  },
  CORRECT_SCHEMA_MARKUP: {
    actionType: "CORRECT_SCHEMA_MARKUP",
    family: "TECHNICAL",
    title: "Correct Invalid Schema Markup",
    description: "Fixes missing required properties or syntax errors in existing JSON-LD blocks.",
    autonomyClass: "AUTO_SAFE",
    expectedImpact: "MEDIUM",
    riskLevel: "LOW",
    verificationMethod: "SCHEMA_VALIDATION",
    rollbackMethod: "RESTORE_PAGE_SNAPSHOT",
    requiresWriteCapability: true,
  },
  NORMALIZE_INTERNAL_URLS: {
    actionType: "NORMALIZE_INTERNAL_URLS",
    family: "TECHNICAL",
    title: "Normalize Internal URLs",
    description: "Standardizes trailing slashes and forces HTTPS on internal hyperlinks.",
    autonomyClass: "AUTO_SAFE",
    expectedImpact: "LOW",
    riskLevel: "LOW",
    verificationMethod: "LIVE_DOM_CHECK",
    rollbackMethod: "RESTORE_PAGE_SNAPSHOT",
    requiresWriteCapability: true,
  },

  // CONTENT FAMILY
  CREATE_SERVICE_PAGE: {
    actionType: "CREATE_SERVICE_PAGE",
    family: "CONTENT",
    title: "Publish New Dedicated Service Page",
    description: "Drafts and publishes a structured, evidence-backed service landing page.",
    autonomyClass: "AUTO_WITH_POLICY",
    expectedImpact: "HIGH",
    riskLevel: "MEDIUM",
    verificationMethod: "HTTP_STATUS_CHECK",
    rollbackMethod: "RESTORE_PAGE_SNAPSHOT",
    requiresWriteCapability: true,
  },
  CREATE_LOCATION_PAGE: {
    actionType: "CREATE_LOCATION_PAGE",
    family: "CONTENT",
    title: "Publish New Dedicated Location Page",
    description: "Generates geo-targeted location landing page with NAP and LocalBusiness schema.",
    autonomyClass: "AUTO_WITH_POLICY",
    expectedImpact: "HIGH",
    riskLevel: "MEDIUM",
    verificationMethod: "HTTP_STATUS_CHECK",
    rollbackMethod: "RESTORE_PAGE_SNAPSHOT",
    requiresWriteCapability: true,
  },
  CREATE_SUPPORTING_PAGE: {
    actionType: "CREATE_SUPPORTING_PAGE",
    family: "CONTENT",
    title: "Publish Supporting Topic Article",
    description: "Publishes helpful informational article answering customer query cluster.",
    autonomyClass: "AUTHORIZATION_REQUIRED",
    expectedImpact: "MEDIUM",
    riskLevel: "MEDIUM",
    verificationMethod: "HTTP_STATUS_CHECK",
    rollbackMethod: "RESTORE_PAGE_SNAPSHOT",
    requiresWriteCapability: true,
  },
  EXPAND_THIN_PAGE: {
    actionType: "EXPAND_THIN_PAGE",
    family: "CONTENT",
    title: "Expand Thin Content on Service Page",
    description: "Enriches low-wordcount pages with detailed benefits, processes, and FAQs.",
    autonomyClass: "AUTO_WITH_POLICY",
    expectedImpact: "HIGH",
    riskLevel: "LOW",
    verificationMethod: "CONTENT_INSPECTION",
    rollbackMethod: "RESTORE_PAGE_SNAPSHOT",
    requiresWriteCapability: true,
  },
  REFRESH_OUTDATED_PAGE: {
    actionType: "REFRESH_OUTDATED_PAGE",
    family: "CONTENT",
    title: "Refresh Outdated Content",
    description: "Updates temporal references, services, and FAQs to regain ranking traction.",
    autonomyClass: "AUTO_WITH_POLICY",
    expectedImpact: "HIGH",
    riskLevel: "LOW",
    verificationMethod: "CONTENT_INSPECTION",
    rollbackMethod: "RESTORE_PAGE_SNAPSHOT",
    requiresWriteCapability: true,
  },
  ALIGN_QUERY_INTENT: {
    actionType: "ALIGN_QUERY_INTENT",
    family: "CONTENT",
    title: "Align On-Page Content to Search Intent",
    description: "Re-structures page headings and introductory copy to match commercial query intent.",
    autonomyClass: "AUTO_WITH_POLICY",
    expectedImpact: "MEDIUM",
    riskLevel: "LOW",
    verificationMethod: "CONTENT_INSPECTION",
    rollbackMethod: "RESTORE_PAGE_SNAPSHOT",
    requiresWriteCapability: true,
  },
  ADD_FAQ_SECTION: {
    actionType: "ADD_FAQ_SECTION",
    family: "CONTENT",
    title: "Add FAQ Section with FAQPage Schema",
    description: "Adds structured FAQ accordions answering authentic customer questions.",
    autonomyClass: "AUTO_SAFE",
    expectedImpact: "HIGH",
    riskLevel: "LOW",
    verificationMethod: "SCHEMA_VALIDATION",
    rollbackMethod: "RESTORE_PAGE_SNAPSHOT",
    requiresWriteCapability: true,
  },
  ENHANCE_ANSWER_STRUCTURE: {
    actionType: "ENHANCE_ANSWER_STRUCTURE",
    family: "CONTENT",
    title: "Structure Direct Answers for AI/SERP Snippets",
    description: "Formats concise 40-50 word answer paragraphs directly beneath H2 question headers.",
    autonomyClass: "AUTO_SAFE",
    expectedImpact: "HIGH",
    riskLevel: "LOW",
    verificationMethod: "CONTENT_INSPECTION",
    rollbackMethod: "RESTORE_PAGE_SNAPSHOT",
    requiresWriteCapability: true,
  },

  // INTERNAL LINKING FAMILY
  REPAIR_ORPHAN_PAGE: {
    actionType: "REPAIR_ORPHAN_PAGE",
    family: "INTERNAL_LINKING",
    title: "Link Orphan Page from Parent Category",
    description: "Inserts contextual links from relevant parent pages to discoverable orphan URLs.",
    autonomyClass: "AUTO_SAFE",
    expectedImpact: "HIGH",
    riskLevel: "LOW",
    verificationMethod: "LIVE_DOM_CHECK",
    rollbackMethod: "RESTORE_PAGE_SNAPSHOT",
    requiresWriteCapability: true,
  },
  ADD_TOPIC_CLUSTER_LINKS: {
    actionType: "ADD_TOPIC_CLUSTER_LINKS",
    family: "INTERNAL_LINKING",
    title: "Build Topic Cluster Interlinking",
    description: "Connects related service and blog articles in a unified semantic cluster.",
    autonomyClass: "AUTO_SAFE",
    expectedImpact: "MEDIUM",
    riskLevel: "LOW",
    verificationMethod: "LIVE_DOM_CHECK",
    rollbackMethod: "RESTORE_PAGE_SNAPSHOT",
    requiresWriteCapability: true,
  },
  IMPROVE_ANCHOR_RELEVANCE: {
    actionType: "IMPROVE_ANCHOR_RELEVANCE",
    family: "INTERNAL_LINKING",
    title: "Replace Generic Anchor Text ('click here')",
    description: "Replaces vague anchor texts with descriptive, keyword-rich phrases.",
    autonomyClass: "AUTO_SAFE",
    expectedImpact: "LOW",
    riskLevel: "LOW",
    verificationMethod: "LIVE_DOM_CHECK",
    rollbackMethod: "RESTORE_PAGE_SNAPSHOT",
    requiresWriteCapability: true,
  },
  BUILD_HUB_SPOKE_LINKS: {
    actionType: "BUILD_HUB_SPOKE_LINKS",
    family: "INTERNAL_LINKING",
    title: "Construct Hub-and-Spoke Architecture Links",
    description: "Links main pillar service pages to sub-specialty spoke pages.",
    autonomyClass: "AUTO_SAFE",
    expectedImpact: "HIGH",
    riskLevel: "LOW",
    verificationMethod: "LIVE_DOM_CHECK",
    rollbackMethod: "RESTORE_PAGE_SNAPSHOT",
    requiresWriteCapability: true,
  },

  // LOCAL FAMILY
  ENHANCE_LOCATION_PAGE: {
    actionType: "ENHANCE_LOCATION_PAGE",
    family: "LOCAL",
    title: "Enhance Local Landing Page Content",
    description: "Enriches location pages with driving directions, landmarks, and local service scope.",
    autonomyClass: "AUTO_WITH_POLICY",
    expectedImpact: "HIGH",
    riskLevel: "LOW",
    verificationMethod: "CONTENT_INSPECTION",
    rollbackMethod: "RESTORE_PAGE_SNAPSHOT",
    requiresWriteCapability: true,
  },
  INJECT_LOCAL_BUSINESS_SCHEMA: {
    actionType: "INJECT_LOCAL_BUSINESS_SCHEMA",
    family: "LOCAL",
    title: "Inject Verified LocalBusiness Schema",
    description: "Injects schema with exact verified name, address, phone (NAP), and geo-coordinates.",
    autonomyClass: "AUTO_SAFE",
    expectedImpact: "HIGH",
    riskLevel: "LOW",
    verificationMethod: "SCHEMA_VALIDATION",
    rollbackMethod: "REMOVE_INJECTED_TAG",
    requiresWriteCapability: true,
  },
  FIX_NAP_CONSISTENCY: {
    actionType: "FIX_NAP_CONSISTENCY",
    family: "LOCAL",
    title: "Align On-Page Name, Address, Phone (NAP)",
    description: "Corrects website footer and contact page NAP to match verified Google Business Profile.",
    autonomyClass: "AUTO_SAFE",
    expectedImpact: "HIGH",
    riskLevel: "LOW",
    verificationMethod: "LIVE_DOM_CHECK",
    rollbackMethod: "RESTORE_PAGE_SNAPSHOT",
    requiresWriteCapability: true,
  },
  ADD_LOCAL_FAQ: {
    actionType: "ADD_LOCAL_FAQ",
    family: "LOCAL",
    title: "Add Location-Specific FAQ Section",
    description: "Answers local questions about parking, emergency service, and neighborhood coverage.",
    autonomyClass: "AUTO_SAFE",
    expectedImpact: "MEDIUM",
    riskLevel: "LOW",
    verificationMethod: "SCHEMA_VALIDATION",
    rollbackMethod: "RESTORE_PAGE_SNAPSHOT",
    requiresWriteCapability: true,
  },

  // AI SEARCH FAMILY
  INJECT_ENTITY_DATA: {
    actionType: "INJECT_ENTITY_DATA",
    family: "AI_SEARCH",
    title: "Inject Clear Verified Entity Data",
    description: "Provides explicit Organization and sameAs entity references for AI knowledge graphs.",
    autonomyClass: "AUTO_SAFE",
    expectedImpact: "HIGH",
    riskLevel: "LOW",
    verificationMethod: "SCHEMA_VALIDATION",
    rollbackMethod: "REMOVE_INJECTED_TAG",
    requiresWriteCapability: true,
  },
  ADD_CITATION_READY_SECTION: {
    actionType: "ADD_CITATION_READY_SECTION",
    family: "AI_SEARCH",
    title: "Add Citation-Ready Summary Section",
    description: "Formats factual bullet points and comparison tables optimized for AI search synthesis.",
    autonomyClass: "AUTO_WITH_POLICY",
    expectedImpact: "HIGH",
    riskLevel: "LOW",
    verificationMethod: "CONTENT_INSPECTION",
    rollbackMethod: "RESTORE_PAGE_SNAPSHOT",
    requiresWriteCapability: true,
  },
  STRUCTURE_FACTUAL_QA: {
    actionType: "STRUCTURE_FACTUAL_QA",
    family: "AI_SEARCH",
    title: "Structure Factual Q&A for Answer Inclusion",
    description: "Formats structured Q&A blocks addressing target AI conversational queries.",
    autonomyClass: "AUTO_SAFE",
    expectedImpact: "HIGH",
    riskLevel: "LOW",
    verificationMethod: "CONTENT_INSPECTION",
    rollbackMethod: "RESTORE_PAGE_SNAPSHOT",
    requiresWriteCapability: true,
  },
};

export function getActionDefinition(actionType: CanonicalActionType): CanonicalActionDefinition {
  const def = ACTION_CATALOG[actionType];
  if (!def) {
    throw new Error(`Unknown canonical action type: ${actionType}`);
  }
  return def;
}
