import type { SpecialistRoleDefinition } from "./types.ts";
import { roleRegistryKey } from "./types.ts";
import { DEPARTMENT_KEYS, isDepartmentKey } from "../departments/types.ts";
import { getDepartment } from "../departments/registry.ts";

type RoleInput = Omit<SpecialistRoleDefinition, "department" | "key"> & {
  department: SpecialistRoleDefinition["department"];
  key: string;
};

function role(r: RoleInput): SpecialistRoleDefinition {
  return r;
}

const ROLE_DEFINITIONS: readonly SpecialistRoleDefinition[] = [
  role({ key: "ceo_delegate", department: "executive", label: "CEO delegate", purpose: "Represents executive intent and approves mission direction.", typicalInputs: ["mission_brief"], typicalOutputs: ["mission_charter"], requestableCapabilityClasses: ["analytics.read"], riskLevel: "low", evidenceRequirement: "recommended" }),
  role({ key: "mission_coordinator", department: "executive", label: "Mission coordinator", purpose: "Orchestrates mission scope, owners, and handoffs.", typicalInputs: ["mission_brief"], typicalOutputs: ["mission_charter"], requestableCapabilityClasses: ["analytics.read"], riskLevel: "low", evidenceRequirement: "none" }),
  role({ key: "decision_recorder", department: "executive", label: "Decision recorder", purpose: "Captures decisions, rationale, and accountability.", typicalInputs: ["strategy_memo"], typicalOutputs: ["decision_log"], requestableCapabilityClasses: ["report.generate"], riskLevel: "low", evidenceRequirement: "recommended" }),
  role({ key: "growth_strategist", department: "strategy", label: "Growth strategist", purpose: "Designs growth bets and measurable outcomes.", typicalInputs: ["mission_brief"], typicalOutputs: ["strategy_memo"], requestableCapabilityClasses: ["research.web"], riskLevel: "medium", evidenceRequirement: "recommended" }),
  role({ key: "channel_strategist", department: "strategy", label: "Channel strategist", purpose: "Selects and prioritizes channels.", typicalInputs: ["market_context"], typicalOutputs: ["channel_plan"], requestableCapabilityClasses: ["research.web"], riskLevel: "medium", evidenceRequirement: "recommended" }),
  role({ key: "campaign_planner", department: "strategy", label: "Campaign planner", purpose: "Builds campaign architecture and dependencies.", typicalInputs: ["strategy_memo"], typicalOutputs: ["campaign_plan"], requestableCapabilityClasses: ["report.generate"], riskLevel: "medium", evidenceRequirement: "recommended" }),
  role({ key: "market_researcher", department: "research", label: "Market researcher", purpose: "Maps market size and category dynamics.", typicalInputs: ["research_brief"], typicalOutputs: ["research_evidence"], requestableCapabilityClasses: ["research.web"], riskLevel: "low", evidenceRequirement: "required" }),
  role({ key: "audience_researcher", department: "research", label: "Audience researcher", purpose: "Profiles audience needs and intent.", typicalInputs: ["research_brief"], typicalOutputs: ["research_summary"], requestableCapabilityClasses: ["research.web"], riskLevel: "low", evidenceRequirement: "required" }),
  role({ key: "competitor_researcher", department: "research", label: "Competitor researcher", purpose: "Analyzes competitor positioning.", typicalInputs: ["competitor_list"], typicalOutputs: ["research_evidence"], requestableCapabilityClasses: ["research.web"], riskLevel: "low", evidenceRequirement: "required" }),
  role({ key: "trend_researcher", department: "research", label: "Trend researcher", purpose: "Tracks emerging trends.", typicalInputs: ["research_brief"], typicalOutputs: ["research_evidence"], requestableCapabilityClasses: ["research.web"], riskLevel: "low", evidenceRequirement: "required" }),
  role({ key: "evidence_reviewer", department: "research", label: "Evidence reviewer", purpose: "Validates source quality and citations.", typicalInputs: ["research_evidence"], typicalOutputs: ["research_summary"], requestableCapabilityClasses: ["research.web"], riskLevel: "low", evidenceRequirement: "required" }),
  role({ key: "brand_strategist", department: "brand", label: "Brand strategist", purpose: "Defines brand narrative and differentiation.", typicalInputs: ["brand_slice"], typicalOutputs: ["brand_guidance"], requestableCapabilityClasses: ["content.longform"], riskLevel: "medium", evidenceRequirement: "recommended" }),
  role({ key: "voice_guardian", department: "brand", label: "Voice guardian", purpose: "Enforces tone and messaging rules.", typicalInputs: ["shortform_copy"], typicalOutputs: ["voice_rules"], requestableCapabilityClasses: ["content.shortform"], riskLevel: "medium", evidenceRequirement: "recommended" }),
  role({ key: "offer_positioning_specialist", department: "brand", label: "Offer positioning specialist", purpose: "Frames offers for clarity and fit.", typicalInputs: ["offer_brief"], typicalOutputs: ["positioning_memo"], requestableCapabilityClasses: ["content.shortform"], riskLevel: "medium", evidenceRequirement: "recommended" }),
  role({ key: "creative_director", department: "creative", label: "Creative director", purpose: "Sets creative vision and approves direction.", typicalInputs: ["content_brief"], typicalOutputs: ["creative_concept"], requestableCapabilityClasses: ["media.image_generation"], riskLevel: "medium", evidenceRequirement: "none" }),
  role({ key: "concept_developer", department: "creative", label: "Concept developer", purpose: "Explores territories and campaign ideas.", typicalInputs: ["campaign_plan"], typicalOutputs: ["creative_concept"], requestableCapabilityClasses: ["content.shortform"], riskLevel: "medium", evidenceRequirement: "none" }),
  role({ key: "art_director", department: "creative", label: "Art director", purpose: "Defines visual systems and asset direction.", typicalInputs: ["creative_concept"], typicalOutputs: ["art_direction"], requestableCapabilityClasses: ["media.image_generation"], riskLevel: "medium", evidenceRequirement: "none" }),
  role({ key: "copywriter", department: "content", label: "Copywriter", purpose: "Writes hooks, captions, and conversion copy.", typicalInputs: ["content_brief"], typicalOutputs: ["caption_set"], requestableCapabilityClasses: ["content.shortform"], riskLevel: "medium", evidenceRequirement: "recommended" }),
  role({ key: "scriptwriter", department: "content", label: "Scriptwriter", purpose: "Drafts scripts for video and audio.", typicalInputs: ["content_brief"], typicalOutputs: ["script"], requestableCapabilityClasses: ["content.longform"], riskLevel: "medium", evidenceRequirement: "recommended" }),
  role({ key: "longform_writer", department: "content", label: "Long-form writer", purpose: "Produces articles and guides.", typicalInputs: ["content_brief"], typicalOutputs: ["longform_draft"], requestableCapabilityClasses: ["content.longform"], riskLevel: "medium", evidenceRequirement: "recommended" }),
  role({ key: "editor", department: "content", label: "Editor", purpose: "Refines structure, tone, and readability.", typicalInputs: ["longform_draft"], typicalOutputs: ["caption_set"], requestableCapabilityClasses: ["content.shortform"], riskLevel: "medium", evidenceRequirement: "recommended" }),
  role({ key: "image_producer", department: "media", label: "Image producer", purpose: "Creates still image assets.", typicalInputs: ["art_direction"], typicalOutputs: ["image_final"], requestableCapabilityClasses: ["media.image_generation"], riskLevel: "medium", evidenceRequirement: "recommended" }),
  role({ key: "carousel_designer", department: "media", label: "Carousel designer", purpose: "Builds multi-slide carousel creatives.", typicalInputs: ["carousel_brief"], typicalOutputs: ["carousel_candidate"], requestableCapabilityClasses: ["media.carousel_generation"], riskLevel: "medium", evidenceRequirement: "recommended" }),
  role({ key: "video_producer", department: "media", label: "Video producer", purpose: "Produces short-form video assets.", typicalInputs: ["video_brief"], typicalOutputs: ["reel_candidate"], requestableCapabilityClasses: ["media.video_generation"], riskLevel: "medium", evidenceRequirement: "recommended" }),
  role({ key: "reel_producer", department: "media", label: "Reel producer", purpose: "Optimizes vertical short video.", typicalInputs: ["video_brief"], typicalOutputs: ["reel_candidate"], requestableCapabilityClasses: ["media.video_generation"], riskLevel: "medium", evidenceRequirement: "recommended" }),
  role({ key: "storyboard_artist", department: "media", label: "Storyboard artist", purpose: "Plans shot sequences for video.", typicalInputs: ["video_brief"], typicalOutputs: ["storyboard"], requestableCapabilityClasses: [], riskLevel: "medium", evidenceRequirement: "recommended" }),
  role({ key: "social_strategist", department: "social", label: "Social strategist", purpose: "Plans platform mix and cadence.", typicalInputs: ["social_brief"], typicalOutputs: ["social_plan"], requestableCapabilityClasses: ["analytics.read"], riskLevel: "high", evidenceRequirement: "recommended" }),
  role({ key: "community_manager", department: "social", label: "Community manager", purpose: "Guides community tone and responses.", typicalInputs: ["social_plan"], typicalOutputs: ["shortform_copy"], requestableCapabilityClasses: ["content.shortform"], riskLevel: "high", evidenceRequirement: "recommended" }),
  role({ key: "scheduling_specialist", department: "social", label: "Scheduling specialist", purpose: "Schedules approved posts.", typicalInputs: ["social_final"], typicalOutputs: ["schedule_receipt"], requestableCapabilityClasses: ["social.schedule"], riskLevel: "high", evidenceRequirement: "recommended" }),
  role({ key: "engagement_analyst", department: "social", label: "Engagement analyst", purpose: "Interprets engagement metrics.", typicalInputs: ["analytics_evidence"], typicalOutputs: ["insight_memo"], requestableCapabilityClasses: ["analytics.read"], riskLevel: "medium", evidenceRequirement: "recommended" }),
  role({ key: "keyword_researcher", department: "seo", label: "Keyword researcher", purpose: "Builds keyword maps.", typicalInputs: ["keyword_brief"], typicalOutputs: ["keyword_map"], requestableCapabilityClasses: ["research.serp"], riskLevel: "low", evidenceRequirement: "recommended" }),
  role({ key: "serp_researcher", department: "seo", label: "SERP researcher", purpose: "Analyzes SERP composition.", typicalInputs: ["keyword_brief"], typicalOutputs: ["serp_evidence"], requestableCapabilityClasses: ["research.serp"], riskLevel: "low", evidenceRequirement: "recommended" }),
  role({ key: "seo_writer", department: "seo", label: "SEO writer", purpose: "Drafts search-oriented articles.", typicalInputs: ["seo_brief"], typicalOutputs: ["seo_article_draft"], requestableCapabilityClasses: ["seo.article"], riskLevel: "low", evidenceRequirement: "recommended" }),
  role({ key: "onpage_optimizer", department: "seo", label: "On-page optimizer", purpose: "Optimizes titles and metadata.", typicalInputs: ["website_snapshot"], typicalOutputs: ["seo_audit_report"], requestableCapabilityClasses: ["seo.audit"], riskLevel: "low", evidenceRequirement: "recommended" }),
  role({ key: "internal_linking_specialist", department: "seo", label: "Internal linking specialist", purpose: "Designs internal link architecture.", typicalInputs: ["keyword_map"], typicalOutputs: ["seo_audit_report"], requestableCapabilityClasses: ["seo.audit"], riskLevel: "low", evidenceRequirement: "recommended" }),
  role({ key: "ux_architect", department: "website", label: "UX architect", purpose: "Designs page structure and flows.", typicalInputs: ["page_brief"], typicalOutputs: ["website_draft"], requestableCapabilityClasses: ["website.generate"], riskLevel: "high", evidenceRequirement: "recommended" }),
  role({ key: "page_copy_specialist", department: "website", label: "Page copy specialist", purpose: "Writes landing page copy.", typicalInputs: ["page_brief"], typicalOutputs: ["website_draft"], requestableCapabilityClasses: ["website.generate"], riskLevel: "medium", evidenceRequirement: "recommended" }),
  role({ key: "landing_page_builder", department: "website", label: "Landing page builder", purpose: "Assembles page drafts.", typicalInputs: ["page_brief"], typicalOutputs: ["website_draft"], requestableCapabilityClasses: ["website.generate"], riskLevel: "high", evidenceRequirement: "recommended" }),
  role({ key: "deploy_coordinator", department: "website", label: "Deploy coordinator", purpose: "Coordinates governed deployment.", typicalInputs: ["website_approved"], typicalOutputs: ["deploy_receipt"], requestableCapabilityClasses: ["website.deploy"], riskLevel: "critical", evidenceRequirement: "recommended" }),
  role({ key: "media_planner", department: "advertising", label: "Media planner", purpose: "Plans budgets and channel mix.", typicalInputs: ["campaign_brief"], typicalOutputs: ["ads_plan"], requestableCapabilityClasses: ["ads.plan"], riskLevel: "high", evidenceRequirement: "recommended" }),
  role({ key: "ad_copywriter", department: "advertising", label: "Ad copywriter", purpose: "Writes ad copy variants.", typicalInputs: ["ads_plan"], typicalOutputs: ["shortform_copy"], requestableCapabilityClasses: ["ads.plan"], riskLevel: "high", evidenceRequirement: "recommended" }),
  role({ key: "bid_strategist", department: "advertising", label: "Bid strategist", purpose: "Recommends bidding tactics.", typicalInputs: ["ads_plan"], typicalOutputs: ["metric_snapshot"], requestableCapabilityClasses: ["ads.plan"], riskLevel: "high", evidenceRequirement: "recommended" }),
  role({ key: "creative_tester", department: "advertising", label: "Creative tester", purpose: "Designs creative tests.", typicalInputs: ["ads_plan"], typicalOutputs: ["creative_test_plan"], requestableCapabilityClasses: ["ads.plan"], riskLevel: "high", evidenceRequirement: "recommended" }),
  role({ key: "funnel_architect", department: "growth", label: "Funnel architect", purpose: "Maps funnel stages and metrics.", typicalInputs: ["growth_brief"], typicalOutputs: ["funnel_map"], requestableCapabilityClasses: ["analytics.read"], riskLevel: "medium", evidenceRequirement: "recommended" }),
  role({ key: "experiment_designer", department: "growth", label: "Experiment designer", purpose: "Designs tests with measurement plans.", typicalInputs: ["funnel_map"], typicalOutputs: ["experiment_plan"], requestableCapabilityClasses: ["analytics.read"], riskLevel: "medium", evidenceRequirement: "recommended" }),
  role({ key: "retention_strategist", department: "growth", label: "Retention strategist", purpose: "Plans lifecycle improvement programs.", typicalInputs: ["crm_snapshot"], typicalOutputs: ["retention_playbook"], requestableCapabilityClasses: ["crm.read"], riskLevel: "medium", evidenceRequirement: "recommended" }),
  role({ key: "sales_strategist", department: "sales", label: "Sales strategist", purpose: "Designs sales motions and playbooks.", typicalInputs: ["sales_brief"], typicalOutputs: ["outreach_sequence"], requestableCapabilityClasses: ["crm.read"], riskLevel: "high", evidenceRequirement: "recommended" }),
  role({ key: "outreach_specialist", department: "sales", label: "Outreach specialist", purpose: "Drafts personalized outreach sequences.", typicalInputs: ["crm_snapshot"], typicalOutputs: ["outreach_sequence"], requestableCapabilityClasses: ["crm.write"], riskLevel: "high", evidenceRequirement: "recommended" }),
  role({ key: "proposal_writer", department: "sales", label: "Proposal writer", purpose: "Produces proposal drafts.", typicalInputs: ["sales_brief"], typicalOutputs: ["proposal_draft"], requestableCapabilityClasses: ["crm.read"], riskLevel: "high", evidenceRequirement: "recommended" }),
  role({ key: "crm_analyst", department: "crm", label: "CRM analyst", purpose: "Analyzes CRM data quality and trends.", typicalInputs: ["crm_query"], typicalOutputs: ["crm_snapshot"], requestableCapabilityClasses: ["crm.read"], riskLevel: "medium", evidenceRequirement: "recommended" }),
  role({ key: "lead_lifecycle_specialist", department: "crm", label: "Lead lifecycle specialist", purpose: "Manages stage transitions.", typicalInputs: ["crm_mutation_request"], typicalOutputs: ["crm_write_receipt"], requestableCapabilityClasses: ["crm.write"], riskLevel: "high", evidenceRequirement: "recommended" }),
  role({ key: "segmentation_specialist", department: "crm", label: "Segmentation specialist", purpose: "Builds audience segments.", typicalInputs: ["crm_query"], typicalOutputs: ["segment_definition"], requestableCapabilityClasses: ["crm.read"], riskLevel: "medium", evidenceRequirement: "recommended" }),
  role({ key: "conversation_designer", department: "whatsapp", label: "Conversation designer", purpose: "Designs WhatsApp flows and templates.", typicalInputs: ["whatsapp_brief"], typicalOutputs: ["conversation_flow"], requestableCapabilityClasses: ["content.shortform"], riskLevel: "high", evidenceRequirement: "required" }),
  role({ key: "followup_specialist", department: "whatsapp", label: "Follow-up specialist", purpose: "Plans timed follow-ups.", typicalInputs: ["conversation_flow"], typicalOutputs: ["whatsapp_message_draft"], requestableCapabilityClasses: ["whatsapp.send"], riskLevel: "critical", evidenceRequirement: "required" }),
  role({ key: "consent_guardian", department: "whatsapp", label: "Consent guardian", purpose: "Verifies consent before send actions.", typicalInputs: ["consent_record"], typicalOutputs: ["policy_clearance"], requestableCapabilityClasses: [], riskLevel: "critical", evidenceRequirement: "required" }),
  role({ key: "cro_specialist", department: "conversion", label: "CRO specialist", purpose: "Diagnoses conversion leaks.", typicalInputs: ["funnel_map"], typicalOutputs: ["cro_audit"], requestableCapabilityClasses: ["analytics.read"], riskLevel: "medium", evidenceRequirement: "recommended" }),
  role({ key: "offer_optimizer", department: "conversion", label: "Offer optimizer", purpose: "Refines offers and value framing.", typicalInputs: ["offer_brief"], typicalOutputs: ["offer_variant"], requestableCapabilityClasses: ["content.shortform"], riskLevel: "medium", evidenceRequirement: "recommended" }),
  role({ key: "cta_strategist", department: "conversion", label: "CTA strategist", purpose: "Designs CTA hierarchy and copy.", typicalInputs: ["page_brief"], typicalOutputs: ["cta_recommendation"], requestableCapabilityClasses: ["content.shortform"], riskLevel: "medium", evidenceRequirement: "recommended" }),
  role({ key: "performance_analyst", department: "analytics", label: "Performance analyst", purpose: "Tracks KPI trends and anomalies.", typicalInputs: ["analytics_query"], typicalOutputs: ["analytics_evidence"], requestableCapabilityClasses: ["analytics.read"], riskLevel: "low", evidenceRequirement: "required" }),
  role({ key: "attribution_analyst", department: "analytics", label: "Attribution analyst", purpose: "Attributes outcomes across touchpoints.", typicalInputs: ["analytics_query"], typicalOutputs: ["insight_memo"], requestableCapabilityClasses: ["analytics.read"], riskLevel: "low", evidenceRequirement: "required" }),
  role({ key: "insight_synthesizer", department: "analytics", label: "Insight synthesizer", purpose: "Turns metrics into insights.", typicalInputs: ["analytics_evidence"], typicalOutputs: ["insight_memo"], requestableCapabilityClasses: ["analytics.read"], riskLevel: "low", evidenceRequirement: "required" }),
  role({ key: "report_writer", department: "reporting", label: "Report writer", purpose: "Compiles structured reports.", typicalInputs: ["report_brief"], typicalOutputs: ["report_artifact"], requestableCapabilityClasses: ["report.generate"], riskLevel: "low", evidenceRequirement: "required" }),
  role({ key: "dashboard_curator", department: "reporting", label: "Dashboard curator", purpose: "Organizes metrics into dashboards.", typicalInputs: ["analytics_evidence"], typicalOutputs: ["dashboard_spec"], requestableCapabilityClasses: ["analytics.read"], riskLevel: "low", evidenceRequirement: "required" }),
  role({ key: "executive_summarizer", department: "reporting", label: "Executive summarizer", purpose: "Distills outcomes into summaries.", typicalInputs: ["report_artifact"], typicalOutputs: ["executive_summary"], requestableCapabilityClasses: ["report.generate"], riskLevel: "low", evidenceRequirement: "required" }),
  role({ key: "experiment_analyst", department: "optimization", label: "Experiment analyst", purpose: "Evaluates experiment outcomes.", typicalInputs: ["experiment_plan"], typicalOutputs: ["experiment_result"], requestableCapabilityClasses: ["analytics.read"], riskLevel: "medium", evidenceRequirement: "recommended" }),
  role({ key: "iteration_planner", department: "optimization", label: "Iteration planner", purpose: "Plans next test cycles.", typicalInputs: ["experiment_result"], typicalOutputs: ["iteration_plan"], requestableCapabilityClasses: ["analytics.read"], riskLevel: "medium", evidenceRequirement: "recommended" }),
  role({ key: "learning_synthesizer", department: "optimization", label: "Learning synthesizer", purpose: "Consolidates cross-channel learnings.", typicalInputs: ["experiment_result"], typicalOutputs: ["learning_memo"], requestableCapabilityClasses: ["report.generate"], riskLevel: "medium", evidenceRequirement: "recommended" }),
  role({ key: "creative_critic", department: "quality", label: "Creative critic", purpose: "Reviews concepts and copy for quality.", typicalInputs: ["shortform_copy"], typicalOutputs: ["qa_report"], requestableCapabilityClasses: [], riskLevel: "low", evidenceRequirement: "recommended" }),
  role({ key: "final_reviewer", department: "quality", label: "Final reviewer", purpose: "Performs last-pass review before release.", typicalInputs: ["social_final"], typicalOutputs: ["approval_stamp"], requestableCapabilityClasses: [], riskLevel: "low", evidenceRequirement: "required" }),
  role({ key: "visual_qa", department: "quality", label: "Visual QA", purpose: "Checks visual assets for defects.", typicalInputs: ["image_final"], typicalOutputs: ["qa_report"], requestableCapabilityClasses: [], riskLevel: "low", evidenceRequirement: "recommended" }),
  role({ key: "claim_checker", department: "compliance", label: "Claim checker", purpose: "Verifies claims are supported.", typicalInputs: ["longform_draft"], typicalOutputs: ["claim_review"], requestableCapabilityClasses: ["research.web"], riskLevel: "medium", evidenceRequirement: "required" }),
  role({ key: "policy_checker", department: "compliance", label: "Policy checker", purpose: "Checks outputs against policy.", typicalInputs: ["ads_plan"], typicalOutputs: ["policy_clearance"], requestableCapabilityClasses: [], riskLevel: "medium", evidenceRequirement: "required" }),
  role({ key: "brand_rule_checker", department: "compliance", label: "Brand rule checker", purpose: "Ensures artifacts follow brand rules.", typicalInputs: ["shortform_copy"], typicalOutputs: ["compliance_report"], requestableCapabilityClasses: [], riskLevel: "medium", evidenceRequirement: "recommended" }),
  role({ key: "success_strategist", department: "customer_success", label: "Success strategist", purpose: "Defines success plans and milestones.", typicalInputs: ["success_brief"], typicalOutputs: ["success_plan"], requestableCapabilityClasses: ["crm.read"], riskLevel: "medium", evidenceRequirement: "recommended" }),
  role({ key: "onboarding_specialist", department: "customer_success", label: "Onboarding specialist", purpose: "Designs onboarding journeys.", typicalInputs: ["customer_profile"], typicalOutputs: ["onboarding_playbook"], requestableCapabilityClasses: ["content.longform"], riskLevel: "medium", evidenceRequirement: "recommended" }),
  role({ key: "retention_advisor", department: "customer_success", label: "Retention advisor", purpose: "Recommends retention interventions.", typicalInputs: ["crm_snapshot"], typicalOutputs: ["retention_recommendation"], requestableCapabilityClasses: ["crm.read"], riskLevel: "medium", evidenceRequirement: "recommended" }),
  role({ key: "ops_coordinator", department: "operations", label: "Ops coordinator", purpose: "Coordinates timelines and logistics.", typicalInputs: ["mission_charter"], typicalOutputs: ["ops_plan"], requestableCapabilityClasses: ["analytics.read"], riskLevel: "low", evidenceRequirement: "none" }),
  role({ key: "capacity_planner", department: "operations", label: "Capacity planner", purpose: "Balances workload against capacity.", typicalInputs: ["capacity_request"], typicalOutputs: ["capacity_report"], requestableCapabilityClasses: ["analytics.read"], riskLevel: "low", evidenceRequirement: "none" }),
  role({ key: "process_auditor", department: "operations", label: "Process auditor", purpose: "Audits workflows for gaps.", typicalInputs: ["workflow_snapshot"], typicalOutputs: ["process_audit"], requestableCapabilityClasses: ["report.generate"], riskLevel: "low", evidenceRequirement: "recommended" }),
  role({ key: "solution_architect", department: "engineering", label: "Solution architect", purpose: "Designs technical solutions.", typicalInputs: ["technical_brief"], typicalOutputs: ["solution_design"], requestableCapabilityClasses: ["website.generate"], riskLevel: "medium", evidenceRequirement: "recommended" }),
  role({ key: "integration_specialist", department: "engineering", label: "Integration specialist", purpose: "Implements system integrations.", typicalInputs: ["integration_spec"], typicalOutputs: ["integration_plan"], requestableCapabilityClasses: ["website.deploy"], riskLevel: "medium", evidenceRequirement: "recommended" }),
  role({ key: "reliability_reviewer", department: "engineering", label: "Reliability reviewer", purpose: "Reviews failure modes and observability.", typicalInputs: ["solution_design"], typicalOutputs: ["reliability_review"], requestableCapabilityClasses: [], riskLevel: "medium", evidenceRequirement: "recommended" }),
  role({ key: "budget_analyst", department: "finance", label: "Budget analyst", purpose: "Tracks budgets and allocation.", typicalInputs: ["budget_brief"], typicalOutputs: ["budget_report"], requestableCapabilityClasses: ["analytics.read"], riskLevel: "medium", evidenceRequirement: "recommended" }),
  role({ key: "cost_guardian", department: "finance", label: "Cost guardian", purpose: "Enforces spend guardrails.", typicalInputs: ["ads_plan"], typicalOutputs: ["spend_clearance"], requestableCapabilityClasses: ["ads.plan"], riskLevel: "high", evidenceRequirement: "recommended" }),
  role({ key: "commercial_compliance_reviewer", department: "finance", label: "Commercial compliance reviewer", purpose: "Reviews commercial terms.", typicalInputs: ["proposal_draft"], typicalOutputs: ["commercial_review"], requestableCapabilityClasses: ["report.generate"], riskLevel: "medium", evidenceRequirement: "required" }),
];

export const ROLE_REGISTRY: Record<string, SpecialistRoleDefinition> = Object.fromEntries(
  ROLE_DEFINITIONS.map((r) => [roleRegistryKey(r.department, r.key), r]),
) as Record<string, SpecialistRoleDefinition>;

export function getRole(department: string, roleKey: string): SpecialistRoleDefinition | undefined {
  return ROLE_REGISTRY[roleRegistryKey(department, roleKey)];
}

export function listRolesForDepartment(department: string): SpecialistRoleDefinition[] {
  if (!isDepartmentKey(department)) return [];
  const dept = getDepartment(department);
  if (!dept) return [];
  return dept.specialistRoles
    .map((ref) => getRole(department, ref.key))
    .filter((r): r is SpecialistRoleDefinition => r !== undefined);
}

export function listAllRoles(): SpecialistRoleDefinition[] {
  return [...ROLE_DEFINITIONS];
}

export function assertRole(department: string, roleKey: string): SpecialistRoleDefinition {
  const found = getRole(department, roleKey);
  if (!found) throw new Error(`unknown_role:${department}.${roleKey}`);
  return found;
}

for (const deptKey of DEPARTMENT_KEYS) {
  if (listRolesForDepartment(deptKey).length === 0) {
    throw new Error(`department_has_no_roles:${deptKey}`);
  }
}
