import { NextResponse } from "next/server";
import { createSupabaseServiceClient } from "@/lib/supabase/service";
import { requireLocalAIAdmin } from "@/lib/local-ai/admin-auth";
import { pairLocalAIConnection } from "@/lib/local-ai/connection";

/**
 * POST /api/admin/system/local-ai/pair
 * Body: { pairingCode: string }
 *
 * Redeems a pairing code generated by the existing Local PC "Generate
 * Code" button against the real, live POST /v1/pair exchange (see
 * lib/local-ai/connection.ts's header for the confirmed request/response
 * contract). LOCAL_AI_API_URL (the stable tunnel hostname, ai.stratxcel.in)
 * is the one piece of configuration this route still reads from the
 * environment -- pairing produces a new API KEY, not a new hostname.
 */
export async function POST(request: Request) {
  const auth = await requireLocalAIAdmin();
  if (!auth.ok) return NextResponse.json({ error: auth.error }, { status: auth.status });

  const body = (await request.json().catch(() => null)) as { pairingCode?: string } | null;
  const pairingCode = body?.pairingCode?.trim();
  if (!pairingCode) return NextResponse.json({ error: "pairingCode is required" }, { status: 400 });

  const apiUrl = process.env.LOCAL_AI_API_URL;
  if (!apiUrl) {
    return NextResponse.json(
      { error: "LOCAL_AI_API_URL is not configured on this deployment. Set it to the Local AI server's tunnel URL (e.g. https://ai.stratxcel.in) before pairing." },
      { status: 500 }
    );
  }

  const service = createSupabaseServiceClient();
  const result = await pairLocalAIConnection(service, { apiUrl, pairingCode, pairedByUserId: auth.userId });
  if (!result.ok) return NextResponse.json({ error: result.errorMessage, errorCode: result.errorCode }, { status: 400 });

  return NextResponse.json({ ok: true, connection: result.connection });
}

export const dynamic = "force-dynamic";
export const runtime = "nodejs";
export const maxDuration = 30;
