import type { Metadata } from "next";
import { LegalDocument, LegalList, LegalSection } from "../legal/LegalDocument";
export const metadata: Metadata = { title: "AI, Automation & Acceptable Use — Stratxcel", description: "Rules for safe and lawful use of Stratxcel AI, automation, content, and communications." };
export default function AcceptableUsePage() { return <LegalDocument eyebrow="Responsible use" title="AI, Automation & Acceptable Use Policy" intro="You must use Stratxcel lawfully, safely, with appropriate human oversight, and within the rights and permissions granted by every connected service.">
  <LegalSection title="Prohibited activity"><LegalList><li>Illegal, fraudulent, deceptive, defamatory, discriminatory, exploitative, or rights-infringing activity.</li><li>Malware, credential theft, phishing, impersonation, unauthorized surveillance, security testing without permission, or attempts to bypass safeguards or extract secrets.</li><li>Spam, purchased or unlawfully sourced lists, communications without required consent, ignored opt-outs, misleading advertising, fake engagement, or platform manipulation.</li><li>Sexual exploitation, child sexual abuse material, credible threats, violent wrongdoing, or content that facilitates serious harm.</li><li>High-impact decisions about employment, credit, insurance, housing, education, healthcare, legal rights, or essential services without lawful authority, qualified human review, and appropriate safeguards.</li><li>Submitting personal, confidential, copyrighted, biometric, health, financial, or other sensitive material without authority and a valid legal basis.</li></LegalList></LegalSection>
  <LegalSection title="AI and content responsibilities"><p>Clearly assess accuracy, provenance, bias, intellectual-property rights, disclosure requirements, and audience suitability. Do not represent AI output as verified fact or professional advice. Similar outputs may be generated for others, and output ownership or protectability is not guaranteed.</p></LegalSection>
  <LegalSection title="Automation and communications"><p>Use test modes, approvals, spending limits, recipient checks, frequency controls, suppression lists, and rollback paths appropriate to the risk. You remain responsible for every enabled workflow and must comply with consent and preference rules, including applicable commercial-communications requirements.</p></LegalSection>
  <LegalSection title="Enforcement"><p>We may investigate, preserve relevant records, rate-limit, block output or external actions, disable integrations, suspend accounts, or report conduct where reasonably necessary for safety, law, provider rules, or protection of others. We may require remediation before restoring access. Enforcement does not make us responsible for client activity.</p></LegalSection>
</LegalDocument>; }
