import { requireTenantContext, getTenantServiceContext } from "@/lib/tenants/tenant-context";
import { generate5PageSite, WEBSITE_ENTITLEMENT_ENFORCED } from "@stratxcel/websites-and-domains";
import { hasEntitlement } from "@stratxcel/payments-and-wallet";
import { getCurrentBrandBrain } from "@stratxcel/brand-brain";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/**
 * Creates a site project and its first version. Content is generated by the
 * controlled template system (packages/websites-and-domains/src/site-
 * builder.ts) enriched with real Brand Brain context where available — never
 * an uncontrolled/arbitrary-code AI blob, and never a fabricated fact (see
 * that file's placeholder-marking rules).
 */
export async function POST(request: Request) {
  try {
    const body = await request.json().catch(() => ({}));
    const { tenantId, businessName, industry, businessDescription, differentiators, contactEmail, contactPhone, contactAddress } = body;

    if (!tenantId || !businessName) {
      return Response.json({ error: "tenantId and businessName are required" }, { status: 400 });
    }

    const ctx = await requireTenantContext(tenantId);
    if (!ctx.ok) return Response.json({ error: ctx.error }, { status: ctx.status });

    const { supabase: serviceDb } = getTenantServiceContext();

    // Entitlement check is real and answered honestly; it does not yet block
    // (see WEBSITE_ENTITLEMENT_ENFORCED) because no tenant has a subscription
    // entitlement row until subscriptions go live.
    const entitled = await hasEntitlement(serviceDb, tenantId, "website_maintenance", 1);
    if (WEBSITE_ENTITLEMENT_ENFORCED && !entitled) {
      return Response.json({ error: "This plan does not include website generation." }, { status: 403 });
    }

    const brandBrain = await getCurrentBrandBrain(serviceDb, tenantId).catch(() => null);

    const site = generate5PageSite({
      tenantId,
      businessName,
      industry,
      businessDescription: businessDescription ?? undefined,
      differentiators: Array.isArray(differentiators) ? differentiators.slice(0, 6) : undefined,
      contactEmail,
      contactPhone,
      brandBrain: brandBrain?.content
        ? { targetAudience: brandBrain.content.target_audience, toneOfVoice: brandBrain.content.tone_of_voice, pillars: brandBrain.content.pillars }
        : null,
    });

    const businessInput = { businessName, industry: industry ?? null, businessDescription: businessDescription ?? null, differentiators: differentiators ?? null, contactEmail: contactEmail ?? null, contactPhone: contactPhone ?? null, contactAddress: contactAddress ?? null };

    const { data: dbSite, error } = await serviceDb
      .from("site_projects")
      .insert({
        tenant_id: tenantId,
        name: site.name,
        slug: site.slug,
        template_id: site.templateId,
        status: "draft",
        preview_subdomain: site.previewSubdomain,
        pages: [],
        business_input: businessInput,
        generation_spec: { templateId: site.templateId },
      })
      .select("*")
      .single();

    if (error) {
      return Response.json({ error: `Failed to create site project: ${error.message}` }, { status: 500 });
    }

    const { data: versionResult, error: rpcErr } = await serviceDb.rpc("apply_site_project_version", {
      p_site_project_id: dbSite.id,
      p_tenant_id: tenantId,
      p_action: "generate",
      p_pages: site.pages,
      p_notes: null,
      p_custom_domain: null,
      p_actor_user_id: ctx.userId,
    });

    if (rpcErr || !(versionResult as { success?: boolean })?.success) {
      return Response.json({ error: `Failed to record initial version: ${rpcErr?.message ?? "unknown error"}` }, { status: 500 });
    }

    const { data: finalSite } = await serviceDb.from("site_projects").select("*").eq("id", dbSite.id).single();

    return Response.json({
      site: finalSite,
      previewUrl: `/app/website/${dbSite.id}/preview`,
      entitled,
      entitlementEnforced: WEBSITE_ENTITLEMENT_ENFORCED,
    });
  } catch (err) {
    const msg = err instanceof Error ? err.message : "Failed to create site project";
    return Response.json({ error: msg }, { status: 400 });
  }
}

export async function PATCH(request: Request) {
  try {
    const body = await request.json().catch(() => ({}));
    const { tenantId, siteId, action, notes, customDomain, pages } = body;

    if (!tenantId || !siteId || !action) {
      return Response.json({ error: "tenantId, siteId, and action (revision | approve) are required" }, { status: 400 });
    }
    if (!["revision", "approve"].includes(action)) {
      return Response.json({ error: "Action must be 'revision' or 'approve'" }, { status: 400 });
    }

    const ctx = await requireTenantContext(tenantId);
    if (!ctx.ok) return Response.json({ error: ctx.error }, { status: ctx.status });

    const { supabase: serviceDb } = getTenantServiceContext();

    const { data: rpcResult, error: rpcErr } = await serviceDb.rpc("apply_site_project_version", {
      p_site_project_id: siteId,
      p_tenant_id: tenantId,
      p_action: action,
      p_pages: pages ?? null, // revision content is optional — supplying it records a new version; omitting it just records the request notes
      p_notes: notes ?? (action === "revision" ? "Customer requested changes" : null),
      p_custom_domain: customDomain ?? null,
      p_actor_user_id: ctx.userId,
    });

    if (rpcErr) {
      return Response.json({ error: `Failed to update site: ${rpcErr.message}` }, { status: 500 });
    }
    const result = rpcResult as { success: boolean; reason?: string };
    if (!result.success) {
      const status = result.reason === "site_project_not_found" ? 404 : result.reason === "tenant_mismatch" ? 403 : 400;
      return Response.json({ error: result.reason }, { status });
    }

    // Approving a site with no custom domain requested means there is no
    // further deployment step — the controlled in-app renderer serves the
    // approved version immediately at its own preview/production route.
    if (action === "approve" && !customDomain) {
      await serviceDb.rpc("apply_site_project_version", {
        p_site_project_id: siteId,
        p_tenant_id: tenantId,
        p_action: "mark_live",
        p_pages: null,
        p_notes: null,
        p_custom_domain: null,
        p_actor_user_id: ctx.userId,
      });
    }

    const { data: saved } = await serviceDb.from("site_projects").select("*").eq("id", siteId).eq("tenant_id", tenantId).single();
    return Response.json({ site: saved });
  } catch (err) {
    const msg = err instanceof Error ? err.message : "Failed to update site project";
    return Response.json({ error: msg }, { status: 400 });
  }
}

export async function GET(request: Request) {
  const tenantId = new URL(request.url).searchParams.get("tenantId");
  if (!tenantId) return Response.json({ error: "tenantId query param is required" }, { status: 400 });

  const ctx = await requireTenantContext(tenantId);
  if (!ctx.ok) return Response.json({ error: ctx.error }, { status: ctx.status });

  const { supabase: serviceDb } = getTenantServiceContext();
  const { data: sites, error } = await serviceDb.from("site_projects").select("*").eq("tenant_id", tenantId).order("created_at", { ascending: false });
  if (error) return Response.json({ error: error.message }, { status: 500 });

  return Response.json({ sites: sites ?? [] }, { headers: { "Cache-Control": "no-store" } });
}
