import type { McpServerDefinition } from "./types.ts";

/**
 * Canonical Master MCP Server Registry
 * Defines the complete MCP integration architecture across all 15 provider domains.
 * Single source of truth for MCP capabilities, transports, fallbacks, and governance.
 */
export const CANONICAL_MCP_REGISTRY: readonly McpServerDefinition[] = [
  // ── 1. AWS ─────────────────────────────────────────────────────────────
  {
    mcpId: "stratxcel-aws",
    provider: "AWS",
    serverName: "mcp-server-aws",
    version: "0.4.0",
    classification: "community",
    transport: "stdio",
    executionEnvironment: "multi_environment",
    installationMethod: "npx",
    command: "npx",
    args: ["-y", "mcp-server-aws"],
    authenticationType: "cli_profile",
    envVarReferences: ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_REGION"],
    declaredCapabilities: [
      "aws.ec2_inspect",
      "aws.ssm_command",
      "aws.cloudwatch_logs",
      "aws.lambda_invoke",
      "aws.iam_read",
    ],
    supportedTools: [
      {
        name: "aws_describe_instances",
        description: "List and inspect EC2 instances across AWS regions",
        inputSchema: { type: "object", properties: { region: { type: "string" } } },
        riskLevel: "read_only",
        confirmationPolicy: "autonomous",
        requiredPermissions: ["ec2:DescribeInstances"],
      },
      {
        name: "aws_send_ssm_command",
        description: "Execute a remote command on target EC2 instances via AWS Systems Manager",
        inputSchema: {
          type: "object",
          required: ["instanceId", "command"],
          properties: { instanceId: { type: "string" }, command: { type: "string" } },
        },
        riskLevel: "destructive",
        confirmationPolicy: "confirmation_required",
        requiredPermissions: ["ssm:SendCommand"],
      },
    ],
    riskLevel: "high",
    confirmationPolicy: "confirmation_required",
    status: "auth_required",
    fallback: {
      preferredFallbackType: "cli",
      targetConnectorKey: "aws",
      description: "Fallback directly to Windows AWS IAM Root CLI or AWS SDK SSM client",
    },
    adminVisibility: true,
    description:
      "AWS Cloud Infrastructure MCP server for EC2, SSM, and CloudWatch operations. Uses local CLI profile or environment credentials.",
  },

  // ── 2. AWS S3 ──────────────────────────────────────────────────────────
  {
    mcpId: "stratxcel-s3",
    provider: "AWS S3",
    serverName: "@modelcontextprotocol/server-s3",
    version: "0.6.2",
    classification: "community",
    transport: "stdio",
    executionEnvironment: "multi_environment",
    installationMethod: "npx",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-s3"],
    authenticationType: "cli_profile",
    envVarReferences: ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_REGION", "AWS_S3_BUCKET"],
    declaredCapabilities: ["s3.list_buckets", "s3.get_object", "s3.put_object", "s3.delete_object"],
    supportedTools: [
      {
        name: "s3_list_objects",
        description: "List objects within an authorized S3 bucket prefix",
        inputSchema: { type: "object", required: ["bucket"], properties: { bucket: { type: "string" } } },
        riskLevel: "read_only",
        confirmationPolicy: "autonomous",
        requiredPermissions: ["s3:ListBucket"],
      },
      {
        name: "s3_upload_file",
        description: "Upload an asset or artifact to Amazon S3",
        inputSchema: {
          type: "object",
          required: ["bucket", "key", "content"],
          properties: { bucket: { type: "string" }, key: { type: "string" }, content: { type: "string" } },
        },
        riskLevel: "medium",
        confirmationPolicy: "autonomous",
        requiredPermissions: ["s3:PutObject"],
      },
    ],
    riskLevel: "medium",
    confirmationPolicy: "autonomous",
    status: "auth_required",
    fallback: {
      preferredFallbackType: "native_connector",
      targetConnectorKey: "s3",
      description: "Fallback to native S3 SDK client or Supabase Storage",
    },
    adminVisibility: true,
    description: "AWS S3 Object Storage MCP server for media asset, export, and backup operations.",
  },

  // ── 3. Meta / Meta for Developers ──────────────────────────────────────
  {
    mcpId: "stratxcel-meta-dev",
    provider: "Meta",
    serverName: "stratxcel-meta-developer-mcp",
    version: "1.0.0",
    classification: "custom_stratxcel",
    transport: "stdio",
    executionEnvironment: "multi_environment",
    installationMethod: "built_in",
    authenticationType: "token",
    envVarReferences: ["META_APP_ID", "META_APP_SECRET", "SOCIAL_TOKEN_ENCRYPTION_KEY"],
    declaredCapabilities: [
      "meta.app_inspect",
      "meta.webhook_verify",
      "meta.token_debug",
      "meta.page_read",
      "meta.instagram_read",
      "meta.post_publish",
    ],
    supportedTools: [
      {
        name: "meta_debug_token",
        description: "Inspect Meta Graph API access token permissions and expiration",
        inputSchema: { type: "object", required: ["inputToken"], properties: { inputToken: { type: "string" } } },
        riskLevel: "read_only",
        confirmationPolicy: "autonomous",
        requiredPermissions: ["meta:read"],
      },
      {
        name: "meta_publish_page_post",
        description: "Publish a post to an authorized Facebook Page or Instagram Business account",
        inputSchema: {
          type: "object",
          required: ["pageId", "message"],
          properties: { pageId: { type: "string" }, message: { type: "string" } },
        },
        riskLevel: "high",
        confirmationPolicy: "confirmation_required",
        requiredPermissions: ["pages_manage_posts"],
      },
    ],
    riskLevel: "high",
    confirmationPolicy: "confirmation_required",
    status: "configured",
    fallback: {
      preferredFallbackType: "native_connector",
      targetConnectorKey: "meta",
      description: "Fallback to StratXcel native Meta Graph API connector with social_tokens vault",
    },
    adminVisibility: true,
    description:
      "Meta Developer & Social Publishing MCP bridge. Meta has no official MCP package; this is StratXcel's custom, spec-compliant wrapper over Graph API v22.0.",
  },

  // ── 4. GitHub ──────────────────────────────────────────────────────────
  {
    mcpId: "stratxcel-github",
    provider: "GitHub",
    serverName: "github-mcp-server",
    version: "0.6.2",
    classification: "official",
    transport: "stdio",
    executionEnvironment: "windows",
    installationMethod: "npx",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-github"],
    authenticationType: "token",
    envVarReferences: ["GITHUB_PERSONAL_ACCESS_TOKEN"],
    declaredCapabilities: [
      "infrastructure.repo_read",
      "infrastructure.repo_write",
      "infrastructure.ci_inspect",
      "github.pr_read",
      "github.pr_write",
      "github.issue_read",
      "github.issue_write",
      "github.file_read",
      "github.file_write",
    ],
    supportedTools: [
      {
        name: "get_file_contents",
        description: "Read contents of any repository file",
        inputSchema: { type: "object", required: ["owner", "repo", "path"] },
        riskLevel: "read_only",
        confirmationPolicy: "autonomous",
        requiredPermissions: ["repo:read"],
      },
      {
        name: "create_pull_request",
        description: "Create a new pull request on GitHub",
        inputSchema: { type: "object", required: ["owner", "repo", "title", "head", "base"] },
        riskLevel: "medium",
        confirmationPolicy: "autonomous",
        requiredPermissions: ["repo:write"],
      },
      {
        name: "push_files",
        description: "Commit and push files to a GitHub repository branch",
        inputSchema: { type: "object", required: ["owner", "repo", "branch", "files", "message"] },
        riskLevel: "high",
        confirmationPolicy: "confirmation_required",
        requiredPermissions: ["repo:write"],
      },
    ],
    riskLevel: "medium",
    confirmationPolicy: "autonomous",
    status: "authorized",
    fallback: {
      preferredFallbackType: "direct_api",
      targetConnectorKey: "github",
      description: "Fallback to Octokit REST API with vaulted fine-grained PAT or local gh CLI",
    },
    adminVisibility: true,
    description:
      "Official Model Context Protocol GitHub server. Verified live on Windows with 26 tools for repository, PR, and issue management.",
  },

  // ── 5. Browser / Playwright ────────────────────────────────────────────
  {
    mcpId: "stratxcel-browser",
    provider: "Browser / Playwright",
    serverName: "Playwright",
    version: "1.63.0-alpha-2026-08-31",
    classification: "official",
    transport: "stdio",
    executionEnvironment: "windows",
    installationMethod: "npx",
    command: "npx",
    args: [
      "-y",
      "@playwright/mcp@latest",
      "--browser",
      "chrome",
      "--user-data-dir",
      "D:/pw-profile",
      "--output-dir",
      "D:/pw-output",
      "--viewport-size",
      "1440x900",
    ],
    authenticationType: "browser_session",
    envVarReferences: ["NPM_CONFIG_CACHE", "PLAYWRIGHT_BROWSERS_PATH"],
    declaredCapabilities: [
      "browser.navigate",
      "browser.click",
      "browser.type",
      "browser.screenshot",
      "browser.snapshot",
      "browser.evaluate",
      "browser.tabs",
    ],
    supportedTools: [
      {
        name: "browser_navigate",
        description: "Navigate to a URL in persistent browser session",
        inputSchema: { type: "object", required: ["url"] },
        riskLevel: "low",
        confirmationPolicy: "autonomous",
        requiredPermissions: ["browser:navigate"],
      },
      {
        name: "browser_take_screenshot",
        description: "Capture visual screenshot of current web page",
        inputSchema: { type: "object" },
        riskLevel: "read_only",
        confirmationPolicy: "autonomous",
        requiredPermissions: ["browser:screenshot"],
      },
      {
        name: "browser_click",
        description: "Click an interactive DOM element",
        inputSchema: { type: "object", required: ["selector"] },
        riskLevel: "low",
        confirmationPolicy: "autonomous",
        requiredPermissions: ["browser:interact"],
      },
    ],
    riskLevel: "low",
    confirmationPolicy: "autonomous",
    status: "authorized",
    fallback: {
      preferredFallbackType: "browser_session",
      targetConnectorKey: "founder_computer",
      description: "Fallback to Founder Computer headless Chrome CDP instance running on EC2",
    },
    adminVisibility: true,
    description:
      "Official Playwright MCP server with persistent Chromium profile at D:/pw-profile. Verified live with 24 browser automation tools.",
  },

  // ── 6. Google Services / Drive ─────────────────────────────────────────
  {
    mcpId: "stratxcel-google-drive",
    provider: "Google",
    serverName: "@modelcontextprotocol/server-google-drive",
    version: "0.6.2",
    classification: "community",
    transport: "stdio",
    executionEnvironment: "multi_environment",
    installationMethod: "npx",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-google-drive"],
    authenticationType: "oauth",
    envVarReferences: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET", "GOOGLE_REFRESH_TOKEN"],
    declaredCapabilities: ["google.drive_read", "google.drive_search", "google.drive_download"],
    supportedTools: [
      {
        name: "google_drive_search",
        description: "Search Google Drive documents, sheets, and presentations",
        inputSchema: { type: "object", required: ["query"] },
        riskLevel: "read_only",
        confirmationPolicy: "autonomous",
        requiredPermissions: ["drive.readonly"],
      },
    ],
    riskLevel: "low",
    confirmationPolicy: "autonomous",
    status: "auth_required",
    fallback: {
      preferredFallbackType: "browser_session",
      targetConnectorKey: "google",
      description: "Fallback to Founder Browser authenticated Google session on EC2 or owner_source_connections OAuth",
    },
    adminVisibility: true,
    description:
      "Google Drive document inspection and search MCP server. Backed by OAuth 2.0 refresh tokens.",
  },

  // ── 7. Supabase / PostgreSQL ───────────────────────────────────────────
  {
    mcpId: "stratxcel-supabase",
    provider: "Supabase",
    serverName: "@modelcontextprotocol/server-postgres",
    version: "0.6.2",
    classification: "community",
    transport: "stdio",
    executionEnvironment: "multi_environment",
    installationMethod: "npx",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-postgres"],
    authenticationType: "token",
    envVarReferences: ["POSTGRES_CONNECTION_STRING", "SUPABASE_DB_URL"],
    declaredCapabilities: ["data.inspect_schema", "data.read_query", "data.mutate_query"],
    supportedTools: [
      {
        name: "query_database",
        description: "Execute a read-only SQL query against the database",
        inputSchema: { type: "object", required: ["query"] },
        riskLevel: "medium",
        confirmationPolicy: "autonomous",
        requiredPermissions: ["database:read"],
      },
    ],
    riskLevel: "medium",
    confirmationPolicy: "autonomous",
    status: "auth_required",
    fallback: {
      preferredFallbackType: "native_connector",
      targetConnectorKey: "supabase",
      description: "Fallback to native Supabase PostgREST client and service role key",
    },
    adminVisibility: true,
    description:
      "PostgreSQL / Supabase database MCP server for schema inspection and controlled query execution.",
  },

  // ── 8. Vercel ──────────────────────────────────────────────────────────
  {
    mcpId: "stratxcel-vercel",
    provider: "Vercel",
    serverName: "vercel-mcp",
    version: "0.2.0",
    classification: "community",
    transport: "stdio",
    executionEnvironment: "multi_environment",
    installationMethod: "npx",
    command: "npx",
    args: ["-y", "vercel-mcp"],
    authenticationType: "token",
    envVarReferences: ["VERCEL_API_TOKEN", "VERCEL_TEAM_ID"],
    declaredCapabilities: ["website.deploy_status", "website.domain_status", "website.deploy_inspect"],
    supportedTools: [
      {
        name: "vercel_get_deployment",
        description: "Get deployment status, build logs, and URL for a Vercel project",
        inputSchema: { type: "object", required: ["deploymentId"] },
        riskLevel: "read_only",
        confirmationPolicy: "autonomous",
        requiredPermissions: ["vercel:read"],
      },
    ],
    riskLevel: "low",
    confirmationPolicy: "autonomous",
    status: "auth_required",
    fallback: {
      preferredFallbackType: "direct_api",
      targetConnectorKey: "vercel",
      description: "Fallback to Vercel REST API or Vercel CLI",
    },
    adminVisibility: true,
    description: "Vercel hosting and deployment management MCP server.",
  },

  // ── 9. OpenAI ──────────────────────────────────────────────────────────
  {
    mcpId: "stratxcel-openai",
    provider: "OpenAI",
    serverName: "openai-api-connector",
    version: "1.0.0",
    classification: "no_native_mcp",
    transport: "stdio",
    executionEnvironment: "multi_environment",
    installationMethod: "built_in",
    authenticationType: "token",
    envVarReferences: ["OPENAI_API_KEY"],
    declaredCapabilities: ["ai.chat", "ai.reasoning", "ai.embeddings"],
    supportedTools: [],
    riskLevel: "low",
    confirmationPolicy: "autonomous",
    status: "configured",
    fallback: {
      preferredFallbackType: "direct_api",
      description: "OpenAI is an LLM inference provider; routes through @stratxcel/ai-runtime",
    },
    adminVisibility: true,
    description:
      "OpenAI LLM inference integration. OpenAI provides model APIs, not a tool MCP server; fallback is direct Chat Completions API.",
  },

  // ── 10. CodeCraft ──────────────────────────────────────────────────────
  {
    mcpId: "stratxcel-codecraft",
    provider: "CodeCraft",
    serverName: "stratxcel-codecraft-mcp",
    version: "1.0.0",
    classification: "custom_stratxcel",
    transport: "stdio",
    executionEnvironment: "windows",
    installationMethod: "built_in",
    authenticationType: "token",
    envVarReferences: ["CODECRAFT_API_KEY"],
    declaredCapabilities: ["codecraft.analyze", "codecraft.generate"],
    supportedTools: [
      {
        name: "codecraft_generate",
        description: "Generate codebase modifications via CodeCraft engine",
        inputSchema: { type: "object", required: ["prompt"] },
        riskLevel: "medium",
        confirmationPolicy: "autonomous",
        requiredPermissions: ["codecraft:execute"],
      },
    ],
    riskLevel: "medium",
    confirmationPolicy: "autonomous",
    status: "auth_required",
    fallback: {
      preferredFallbackType: "direct_api",
      description: "Fallback to CodeCraft REST API using CODECRAFT_API_KEY",
    },
    adminVisibility: true,
    description: "StratXcel custom MCP wrapper for CodeCraft automated coding tools.",
  },

  // ── 11. Claude / Claude Code ───────────────────────────────────────────
  {
    mcpId: "stratxcel-claude",
    provider: "Claude",
    serverName: "claude-client-host",
    version: "2.1.207",
    classification: "no_native_mcp",
    transport: "stdio",
    executionEnvironment: "windows",
    installationMethod: "binary",
    authenticationType: "oauth",
    envVarReferences: [],
    declaredCapabilities: ["claude.terminal_agent"],
    supportedTools: [],
    riskLevel: "high",
    confirmationPolicy: "confirmation_required",
    status: "configured",
    fallback: {
      preferredFallbackType: "cli",
      description: "Claude Code is an MCP Client/Host, not an MCP Server; accessed via Claude CLI",
    },
    adminVisibility: false,
    description: "Claude Code terminal coding agent. Acts as an MCP consumer/client rather than a server.",
  },

  // ── 12. Telegram ───────────────────────────────────────────────────────
  {
    mcpId: "stratxcel-telegram",
    provider: "Telegram",
    serverName: "telegram-mcp",
    version: "0.3.0",
    classification: "community",
    transport: "stdio",
    executionEnvironment: "aws_linux",
    installationMethod: "npx",
    command: "npx",
    args: ["-y", "telegram-mcp"],
    authenticationType: "token",
    envVarReferences: ["TELEGRAM_BOT_TOKEN", "TELEGRAM_CHAT_ID"],
    declaredCapabilities: ["telegram.send_message", "telegram.read_updates"],
    supportedTools: [
      {
        name: "telegram_send_alert",
        description: "Send operational notification or alert to Founder Telegram channel",
        inputSchema: { type: "object", required: ["message"] },
        riskLevel: "low",
        confirmationPolicy: "autonomous",
        requiredPermissions: ["telegram:send"],
      },
    ],
    riskLevel: "low",
    confirmationPolicy: "autonomous",
    status: "auth_required",
    fallback: {
      preferredFallbackType: "direct_api",
      description: "Fallback to Telegram Bot HTTP API",
    },
    adminVisibility: true,
    description: "Telegram Bot notification and alert dispatch MCP server.",
  },

  // ── 13. Apollo.io ──────────────────────────────────────────────────────
  {
    mcpId: "stratxcel-apollo",
    provider: "Apollo.io",
    serverName: "stratxcel-apollo-mcp",
    version: "1.0.0",
    classification: "custom_stratxcel",
    transport: "stdio",
    executionEnvironment: "aws_linux",
    installationMethod: "built_in",
    authenticationType: "token",
    envVarReferences: ["APOLLO_API_KEY"],
    declaredCapabilities: ["leads.search", "leads.enrich", "leads.verify"],
    supportedTools: [
      {
        name: "apollo_search_people",
        description: "Search B2B leads by industry, title, and location",
        inputSchema: { type: "object", required: ["query"] },
        riskLevel: "low",
        confirmationPolicy: "autonomous",
        requiredPermissions: ["apollo:read"],
      },
    ],
    riskLevel: "low",
    confirmationPolicy: "autonomous",
    status: "auth_required",
    fallback: {
      preferredFallbackType: "direct_api",
      description: "Fallback to Apollo.io REST API v1",
    },
    adminVisibility: true,
    description: "Apollo.io B2B lead discovery and enrichment MCP bridge.",
  },

  // ── 14. WhatsApp Cloud API ─────────────────────────────────────────────
  {
    mcpId: "stratxcel-whatsapp",
    provider: "WhatsApp",
    serverName: "stratxcel-whatsapp-mcp",
    version: "1.0.0",
    classification: "custom_stratxcel",
    transport: "stdio",
    executionEnvironment: "aws_linux",
    installationMethod: "built_in",
    authenticationType: "token",
    envVarReferences: ["WHATSAPP_TOKEN", "WHATSAPP_PHONE_NUMBER_ID"],
    declaredCapabilities: ["messaging.send", "messaging.templates", "messaging.inbox_read"],
    supportedTools: [
      {
        name: "whatsapp_send_template",
        description: "Send pre-approved WhatsApp template message to a verified contact",
        inputSchema: { type: "object", required: ["to", "templateName"] },
        riskLevel: "high",
        confirmationPolicy: "confirmation_required",
        requiredPermissions: ["whatsapp:send"],
      },
    ],
    riskLevel: "high",
    confirmationPolicy: "confirmation_required",
    status: "configured",
    fallback: {
      preferredFallbackType: "native_connector",
      targetConnectorKey: "whatsapp",
      description: "Fallback to native WhatsApp processor daemon and Cloud API v22.0",
    },
    adminVisibility: true,
    description:
      "Meta WhatsApp Cloud API messaging MCP bridge. Managed via whatsapp_phone_bindings and processor worker.",
  },

  // ── 15. StratXcel Hermes Internal Gateway ──────────────────────────────
  {
    mcpId: "stratxcel-hermes",
    provider: "StratXcel Hermes",
    serverName: "stratxcel",
    version: "0.1.0",
    classification: "custom_stratxcel",
    transport: "streamable_http",
    executionEnvironment: "aws_linux",
    installationMethod: "built_in",
    endpointUrl: "http://127.0.0.1:8082/mcp",
    authenticationType: "bearer",
    envVarReferences: ["STRATXCEL_MCP_BRIDGE_SECRET", "HERMES_GATEWAY_SECRET"],
    declaredCapabilities: [
      "hermes.brand_brain",
      "hermes.service_definition",
      "hermes.draft_artifact",
      "hermes.progress_update",
      "hermes.approvals",
      "hermes.handoffs",
      "hermes.crm_lead",
      "hermes.research_evidence",
      "hermes.growth_status",
      "hermes.website_status",
    ],
    supportedTools: [
      {
        name: "get_brand_context",
        description: "Fetch tenant current Brand Brain (voice, offers, facts)",
        inputSchema: { type: "object", required: ["missionCapability"] },
        riskLevel: "read_only",
        confirmationPolicy: "autonomous",
        requiredPermissions: ["hermes:brand_read"],
      },
      {
        name: "create_draft_artifact",
        description: "Save a draft output artifact for this mission",
        inputSchema: { type: "object", required: ["kind", "storageRef", "missionCapability"] },
        riskLevel: "low",
        confirmationPolicy: "autonomous",
        requiredPermissions: ["hermes:artifact_write"],
      },
      {
        name: "request_approval",
        description: "Ask a human to approve a sensitive action before taking it",
        inputSchema: { type: "object", required: ["kind", "subject", "missionCapability"] },
        riskLevel: "medium",
        confirmationPolicy: "autonomous",
        requiredPermissions: ["hermes:approval_request"],
      },
      {
        name: "create_crm_lead",
        description: "Record a new CRM lead generated by autonomous mission",
        inputSchema: { type: "object", required: ["contactName", "missionCapability"] },
        riskLevel: "medium",
        confirmationPolicy: "autonomous",
        requiredPermissions: ["crm:write"],
      },
      {
        name: "check_growth_status",
        description: "Read real currently-stored SEO/AEO/GEO opportunities for tenant",
        inputSchema: { type: "object", required: ["missionCapability"] },
        riskLevel: "read_only",
        confirmationPolicy: "autonomous",
        requiredPermissions: ["growth:read"],
      },
      {
        name: "check_website_status",
        description: "Inspect real currently-stored StratXcel-built websites for tenant",
        inputSchema: { type: "object", required: ["missionCapability"] },
        riskLevel: "read_only",
        confirmationPolicy: "autonomous",
        requiredPermissions: ["websites:read"],
      },
    ],
    riskLevel: "low",
    confirmationPolicy: "autonomous",
    status: "authorized",
    fallback: {
      preferredFallbackType: "native_connector",
      description: "Fallback to in-process Native Hermes Adapter (HERMES_MODE=native)",
    },
    adminVisibility: true,
    description:
      "Official StratXcel Hermes Gateway MCP server running on EC2. Streamable HTTP transport pinning @modelcontextprotocol/sdk 1.30.0.",
  },
];

export function getMcpDefinition(mcpId: string): McpServerDefinition | undefined {
  return CANONICAL_MCP_REGISTRY.find((m) => m.mcpId === mcpId);
}

export function listMcpDefinitionsByEnvironment(
  env: McpServerDefinition["executionEnvironment"]
): McpServerDefinition[] {
  return CANONICAL_MCP_REGISTRY.filter(
    (m) => m.executionEnvironment === env || m.executionEnvironment === "multi_environment"
  );
}
