import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { AUDIT_PRODUCT, FAIR_USE_POLICY, formatGstInclusivePrice, PLAN_LIMITS, PLANS, PUBLIC_PLAN_IDS, SELF_CHECKOUT_PLAN_IDS, USAGE_WARNING_THRESHOLDS } from "../index.ts";
const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "..", "..");
const read = (...parts: string[]) => fs.readFileSync(path.join(root, ...parts), "utf8");
assert.deepEqual(PUBLIC_PLAN_IDS, ["free", "starter", "growth", "business", "scale"]);
assert.deepEqual([PLANS.free.priceCents, PLANS.starter.priceCents, PLANS.growth.priceCents, PLANS.business.priceCents, PLANS.scale.priceCents], [0, 499900, 999900, 1999900, null]);
assert.equal(PLANS.growth.recommended, true);
assert.equal(PLANS.scale.priceLabel, "₹34,999+");
assert.equal(AUDIT_PRODUCT.priceCents, 99900);
assert.deepEqual(SELF_CHECKOUT_PLAN_IDS, ["starter", "growth", "business"]);
assert.deepEqual(USAGE_WARNING_THRESHOLDS, [80, 90, 100]);
assert.match(formatGstInclusivePrice(PLANS.starter), /₹4,999\/month · GST included/);
assert.ok(PLAN_LIMITS.business.whatsapp_contacts > PLAN_LIMITS.growth.whatsapp_contacts);
assert.equal(PLANS.starter.entitlements.aiHandledLeads, 100);
assert.equal(PLANS.growth.entitlements.aiHandledLeads, 500);
assert.equal(PLANS.business.entitlements.aiHandledLeads, 1500);
assert.match(FAIR_USE_POLICY.noSurpriseOverages, /No automatic overage charges/);
assert.match(FAIR_USE_POLICY.leadContinuity, /inbound leads are still captured/);
assert.match(FAIR_USE_POLICY.whatsappUnit, /not a CRM contact or raw message/);
assert.match(FAIR_USE_POLICY.whatsappProviderSeparation, /charges are separate/);
const pricing = read("app", "pricing", "page.tsx");
for (const old of ["₹2,999", "₹7,999", "₹9,499", "₹18,999", "₹23,999", "₹24,999", "₹49,999", "AI Agency", "Autonomous"]) assert.equal(pricing.includes(old), false, `public pricing must not contain ${old}`);
assert.equal(/per token|API calls|unlimited WhatsApp|\$\d/i.test(pricing), false);
const route = read("app", "api", "platform", "subscriptions", "route.ts");
assert.ok(route.indexOf('isPaymentFeatureEnabled("PAYMENTS_SUBSCRIPTIONS_ENABLED")') < route.indexOf("request.json"));
assert.ok(route.includes('planTier === "scale"') && route.includes("requires a reviewed quote"));
assert.equal(route.includes("launch: 949900"), false);
console.log("plans.test.ts: ALL PASS (Notion v1 catalog, GST, WhatsApp separation, fair use, gate, quote-only Scale, superseded public pricing removed)");
