import type { Metadata } from "next";
import { LegalDocument, LegalList, LegalSection } from "../legal/LegalDocument";
export const metadata: Metadata = { title: "Domain & Website Terms — Stratxcel", description: "Terms for domain, DNS, website, hosting, content, and transfer services." };
export default function DomainWebsiteTermsPage() { return <LegalDocument eyebrow="Product terms" title="Domain & Website Terms" intro="These additional terms govern domain search, registration, renewal, DNS, hosting, website creation, publication, maintenance, and transfer services supported by Stratxcel.">
  <LegalSection title="Registration and ownership"><p>Domain availability is not guaranteed until the registry confirms registration. You must provide accurate registrant information, satisfy registry eligibility rules, and keep contact details current. A domain is licensed under registry and registrar rules, not owned as absolute property. The registrant recorded with the provider controls the name, subject to those rules.</p></LegalSection>
  <LegalSection title="Fees, renewal, expiry, and transfer"><LegalList><li>Registry, registrar, premium-name, tax, privacy, redemption, renewal, and transfer charges may change and are generally non-refundable once incurred.</li><li>You are responsible for renewal. Reminders and auto-renewal are convenience features, not guarantees; failed payment, stale contact details, provider action, or registry rules may cause expiry or loss.</li><li>Transfers require eligibility, verification, unlock codes, and provider processing. We may withhold transfer assistance only where law, provider rules, fraud, disputes, or unpaid amounts permit.</li></LegalList></LegalSection>
  <LegalSection title="Websites, content, and approvals"><p>You are responsible for content, claims, products, accessibility, cookies, privacy notices, licences, consumer disclosures, and legal compliance. You must review and approve the site, domain, DNS, forms, analytics, and integrations before publication. AI-generated or migrated material may contain errors or third-party material requiring clearance.</p></LegalSection>
  <LegalSection title="DNS, hosting, email, and outages"><p>DNS and provider changes can take time to propagate and may affect websites, email, authentication, and connected services. Keep independent backups and provide accurate records. We are not liable for registry, registrar, hosting, certificate, network, search-engine, email, or third-party outages or policy action beyond our reasonable control.</p></LegalSection>
  <LegalSection title="Abuse and takedown"><p>We may suspend publication, DNS management, or assistance for phishing, malware, unlawful content, infringement claims, security threats, court or authority requests, or provider requirements. We may share necessary registration or abuse information as permitted by law.</p></LegalSection>
  <LegalSection title="Client-procured domains"><p>If Stratxcel procures a domain for you, the applicable order must identify the intended registrant and transfer arrangement. <strong>[PLACEHOLDER — approve registrar, registrant-of-record, renewal, credentials, and post-termination transfer procedure before enabling production domain sales]</strong>.</p></LegalSection>
</LegalDocument>; }
