import type { Metadata } from "next";
import { LegalDocument, LegalList, LegalSection } from "../legal/LegalDocument";
export const metadata: Metadata = { title: "Refund & Cancellation Policy — Stratxcel", description: "Cancellation, refund, domain, subscription, and service-credit rules for Stratxcel." };
export default function RefundCancellationPage() { return <LegalDocument eyebrow="Commercial terms" title="Refund & Cancellation Policy" intro="This Policy applies unless a written order, plan, invoice, or mandatory law gives you different rights. It does not itself activate or alter any payment, subscription, wallet, refund, or domain workflow.">
  <LegalSection title="Before purchase"><p>Review the stated scope, deliverables, dependencies, fees, taxes, renewal terms, and third-party charges. Custom implementation begins after confirmation and may reserve staff or provider capacity.</p></LegalSection>
  <LegalSection title="Subscriptions"><p>You may cancel through an available account control or the verified contact form. Cancellation prevents the next renewal only if received before the applicable renewal is processed and takes effect at the end of the paid term, unless the order or law states otherwise. We do not prorate or refund unused time merely because you stop using a Service.</p></LegalSection>
  <LegalSection title="Implementation and one-time services"><p>Setup, consulting, migration, creative, website, automation, and other custom-service fees are non-refundable once the relevant work, procurement, or reserved capacity begins, except for our uncured material failure to deliver the agreed scope or where mandatory law requires otherwise. Approved change requests and client-caused delays may affect timing and price.</p></LegalSection>
  <LegalSection title="Refund eligibility"><p>We may approve a refund for a verified duplicate charge, an incorrect amount, a payment taken after timely effective cancellation, or a paid Service we cancel without providing the applicable value. Requests must identify the transaction and reason. Approval is subject to provider records and law.</p></LegalSection>
  <LegalSection title="Non-refundable items"><LegalList><li>Consumed usage, completed milestones, approved work, onboarding, and implementation already performed.</li><li>Domain registration, renewal, redemption, transfer, registry, hosting, advertising, messaging, AI, payment-processing, and other third-party charges once incurred.</li><li>Wallet or promotional credits, except where mandatory law or the written offer states otherwise.</li><li>Loss caused by client instructions, missing access, delayed approvals, policy violations, third-party suspension, or unsupported provider changes.</li></LegalList></LegalSection>
  <LegalSection title="Processing and chargebacks"><p>Approved refunds are returned through the original payment method where reasonably possible. Banks and payment providers control settlement timing and fees. Contact us before initiating a chargeback so we can investigate; fraudulent or abusive disputes may lead to suspension and recovery of reasonable costs, subject to law.</p><p><strong>[PLACEHOLDER — confirm the production cancellation channel, request window, review SLA, and refund settlement estimate before launch]</strong>.</p></LegalSection>
</LegalDocument>; }
