"use client";

import { useCallback, useEffect, useState } from "react";
import { Card, CardHeading, CardRow } from "@/components/ui/Card";
import { Metric } from "@/components/ui/Metric";
import { StatusChip, type ChipState } from "@/components/ui/StatusChip";
import type { HermesTelemetry, SignalState } from "@/lib/hermes/mission-control";

const CHIP: Record<SignalState, ChipState> = { healthy:"success",degraded:"warning",offline:"danger",unavailable:"dashed",not_monitored:"neutral" };
const fmt=(v:number|null,suffix="")=>v==null?"Unavailable":`${v.toLocaleString()}${suffix}`;
const short=(id:string|null)=>id?`${id.slice(0,8)}…`:"Unavailable";
function Spark({ values, tone="stroke-sx-ai" }:{values:number[];tone?:string}) { const max=Math.max(1,...values); const points=values.map((v,i)=>`${i/(Math.max(1,values.length-1))*100},${28-v/max*25}`).join(" "); return <svg viewBox="0 0 100 30" className="h-16 w-full" preserveAspectRatio="none" aria-hidden><polyline fill="none" className={tone} strokeWidth="1.5" points={points}/></svg>; }
function State({state,label}:{state:SignalState;label:string}){return <StatusChip state={CHIP[state]} pulse={state==="healthy"}>{label.replaceAll("_"," ")}</StatusChip>}

export default function HermesMissionControl(){
  const [data,setData]=useState<HermesTelemetry|null>(null); const [error,setError]=useState<string|null>(null); const [refreshing,setRefreshing]=useState(false);
  const load=useCallback(async()=>{setRefreshing(true);try{const r=await fetch("/api/platform/admin/hermes/telemetry",{cache:"no-store"});if(!r.ok)throw new Error(`Telemetry unavailable (HTTP ${r.status})`);setData(await r.json());setError(null);}catch(e){setError(e instanceof Error?e.message:"Telemetry unavailable");}finally{setRefreshing(false)}},[]);
  useEffect(()=>{void load();const timer=setInterval(()=>{if(document.visibilityState==="visible")void load()},10000);return()=>clearInterval(timer)},[load]);
  const stale=data?Date.now()-new Date(data.generatedAt).getTime()>30000:false;
  if(!data)return <Card><CardHeading>Hermes Mission Control</CardHeading><p className="mt-3 text-sm text-sx-text-muted">{error??"Loading real telemetry…"}</p></Card>;
  const recent=data.trends.slice(-24); const statusEntries=[['Hermes Engine',data.status.engine],['Mission Worker',data.status.missionWorker],['MCP Gateway',data.status.mcpGateway],['Provider',data.status.provider],['Queue',data.status.queue]] as const;
  return <div className="flex flex-col gap-5">
    <header className="flex flex-wrap items-end justify-between gap-3"><div><p className="font-sx-mono text-[10px] uppercase tracking-[.12em] text-sx-ai">Operations / Hermes</p><h1 className="mt-1 font-sx-sans text-2xl font-semibold text-sx-text">Hermes Mission Control</h1><p className="mt-1 text-sm text-sx-text-muted">Live, evidence-backed observability for the production mission engine.</p></div><div className="text-right font-sx-mono text-[10px] text-sx-text-subtle"><p>{refreshing?"Refreshing…":stale?"Stale":"Current"}</p><p>Last updated {new Date(data.generatedAt).toLocaleTimeString()}</p>{error&&<p className="text-[#FF8A90]">{error}</p>}</div></header>
    <Card variant="ai" className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{statusEntries.map(([name,s])=><div key={name}><p className="mb-1.5 text-[10px] uppercase tracking-wider text-sx-text-muted">{name}</p><State state={s.state} label={s.label}/></div>)}<div><p className="mb-1.5 text-[10px] uppercase tracking-wider text-sx-text-muted">Last heartbeat</p><p className="font-sx-mono text-xs text-sx-text">{data.workers.map(w=>w.lastHeartbeatAt).filter(Boolean).sort().at(-1)?new Date(data.workers.map(w=>w.lastHeartbeatAt).filter(Boolean).sort().at(-1)!).toLocaleTimeString():"Unavailable"}</p></div></Card>
    <section className="grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-6"><Metric label="Runs today" value={fmt(data.kpis.runsToday)}/><Metric label="Success rate" value={fmt(data.kpis.successRate,"%")}/><Metric label="Avg / P95 latency" value={data.kpis.avgLatencyMs==null?"Unavailable":`${data.kpis.avgLatencyMs} / ${data.kpis.p95LatencyMs??"—"} ms`}/><Metric label="Active missions" value={fmt(data.kpis.activeMissions)} ai/><Metric label="Tool success" value={fmt(data.kpis.toolSuccessRate,"%")}/><Metric label="Denied tools" value={fmt(data.kpis.deniedToolCalls)}/><Metric label="Retries" value={fmt(data.kpis.retries)}/><Metric label="DLQ" value={fmt(data.kpis.dlq)}/><Metric label="Token usage" value={fmt(data.kpis.tokenUsage)}/><Metric label="Measured cost" value={data.kpis.estimatedCostCents==null?"Unavailable":`₹${(data.kpis.estimatedCostCents/100).toFixed(2)}`}/></section>
    <section className="grid gap-3 lg:grid-cols-3"><Card><CardHeading>24h success vs failure</CardHeading><Spark values={recent.map(x=>x.success)}/><Spark values={recent.map(x=>x.failure)} tone="stroke-sx-danger"/><p className="text-[10px] text-sx-text-subtle">Successful and failed terminal missions per hour</p></Card><Card><CardHeading>Latency trend</CardHeading><Spark values={recent.map(x=>x.avgLatencyMs??0)} tone="stroke-sx-accent"/><p className="text-[10px] text-sx-text-subtle">Average measured queue execution latency; gaps mean no data</p></Card><Card><CardHeading>Missions / hour</CardHeading><Spark values={recent.map(x=>x.missions)} tone="stroke-sx-success"/><p className="text-[10px] text-sx-text-subtle">Created mission throughput</p></Card></section>
    <section className="grid gap-3 xl:grid-cols-[1.6fr_1fr]"><Card><div className="flex items-center justify-between"><CardHeading>Live mission lane</CardHeading><span className="text-[10px] text-sx-text-subtle">QUEUED → RUNNING → HERMES → MCP TOOL → APPROVAL → TERMINAL</span></div><div className="mt-3">{data.missions.length?data.missions.map(m=><CardRow key={m.id} className="flex-wrap"><StatusChip state={m.state==="COMPLETED"?"success":m.state==="FAILED"||m.state==="BLOCKED"?"danger":m.state==="RUNNING"?"ai":"accent"}>{m.state}</StatusChip><div className="min-w-[150px] flex-1"><p className="font-sx-mono text-xs text-sx-text">Mission {short(m.id)} · Run {short(m.runId)}</p><p className="text-[11px] text-sx-text-subtle">{m.currentStep??"Current step unavailable"} · correlation {short(m.correlationId)} · {Math.max(0,Math.round((Date.now()-new Date(m.createdAt).getTime())/60000))}m elapsed</p></div></CardRow>):<p className="text-sm text-sx-text-muted">No mission data in the last 7 days.</p>}</div></Card>
    <Card><CardHeading>MCP / tool activity</CardHeading><div className="mt-3 grid grid-cols-2 gap-2 text-xs"><p>Registered <b>{fmt(data.tools.registered)}</b></p><p>Successful <b>{fmt(data.tools.successful)}</b></p><p>Denied <b>{fmt(data.tools.denied)}</b></p><p>Auth failures <b>{fmt(data.tools.authFailures)}</b></p><p>Latency <b>{fmt(data.tools.avgLatencyMs," ms")}</b></p><p>Controlled tools <b>Not monitored</b></p></div><div className="mt-3">{data.tools.byType.slice(0,8).map(t=><CardRow key={t.name}><span className="flex-1 truncate">{t.name}</span><span className="font-sx-mono">{t.calls}</span></CardRow>)}</div></Card></section>
    <section className="grid gap-3 lg:grid-cols-3"><Card><CardHeading>Infrastructure</CardHeading><div className="mt-3">{data.workers.map(w=><CardRow key={w.type}><div className="flex-1"><p>{w.type}</p><p className="text-[10px] text-sx-text-subtle">Heartbeat {w.lastHeartbeatAt?new Date(w.lastHeartbeatAt).toLocaleString():"Unavailable"} · backlog {w.backlog??"Unavailable"}</p></div><State state={w.state} label={w.status}/></CardRow>)}</div><CardRow><span className="flex-1">Hermes host / restart signal</span><StatusChip state="dashed">Not monitored</StatusChip></CardRow></Card>
    <Card><CardHeading>Security & kill switches</CardHeading><div className="mt-3"><CardRow><span className="flex-1">Mission capability enforcement</span><StatusChip state="success">Enforced</StatusChip></CardRow><CardRow><span className="flex-1">MCP transport auth</span><StatusChip state={data.tools.authFailures?"warning":"dashed"}>{data.tools.authFailures?`${data.tools.authFailures} failures`:"No data"}</StatusChip></CardRow><CardRow><span className="flex-1">Built-in Hermes tools</span><StatusChip state="neutral">Disabled by architecture</StatusChip></CardRow>{data.killSwitches.length?data.killSwitches.map((s,i)=><CardRow key={`${s.scope}:${s.scopeId}:${i}`}><span className="flex-1">{s.scope}{s.scopeId?` / ${short(s.scopeId)}`:""}</span><StatusChip state={s.enabled?"danger":"success"}>{s.enabled?"Active":"Open"}</StatusChip></CardRow>):<CardRow><span className="flex-1">Kill switches</span><StatusChip state="dashed">Unavailable / no data</StatusChip></CardRow>}</div></Card>
    <Card><CardHeading>Provider / model usage</CardHeading><div className="mt-3">{data.providers.length?data.providers.map((p,i)=><CardRow key={`${p.provider}:${p.model}:${i}`}><div className="flex-1"><p>{p.provider} {p.model?`/ ${p.model}`:""}</p><p className="text-[10px] text-sx-text-subtle">{p.calls} calls · units {p.units??"Unavailable"} · cost {p.costCents==null?"Unavailable":`₹${(p.costCents/100).toFixed(2)}`}</p></div></CardRow>):<p className="text-sm text-sx-text-muted">No provider/model telemetry available.</p>}</div></Card></section>
    <Card><CardHeading>Recent incidents</CardHeading><div className="mt-3">{data.incidents.length?data.incidents.map(i=><CardRow key={i.id}><StatusChip state="danger">{i.kind}</StatusChip><div className="min-w-0 flex-1"><p className="truncate text-xs text-sx-text">{i.summary}</p><p className="text-[10px] text-sx-text-subtle">{new Date(i.occurredAt).toLocaleString()} · mission {short(i.missionId)}</p></div></CardRow>):<p className="text-sm text-sx-text-muted">No recent incident evidence.</p>}</div></Card>
  </div>;
}
