import { lookup } from "node:dns/promises";
import { isIP } from "node:net";
import type { TechnicalPage } from "./types.ts";
export interface CrawlLimits { maxPages: number; maxDepth: number; requestTimeoutMs: number; totalTimeoutMs: number; maxRedirects: number; maxResponseBytes: number; concurrency: number; }
export const HARD_CRAWL_CEILING = 500;
export const CRAWL_LIMITS = { free: 5, starter: 30, growth: 100, business: 250, scale: 400 } as const;
export const DEFAULT_CRAWL_LIMITS: CrawlLimits = { maxPages: 30, maxDepth: 3, requestTimeoutMs: 8_000, totalTimeoutMs: 45_000, maxRedirects: 5, maxResponseBytes: 2_000_000, concurrency: 2 };
const BLOCKED_PATH = /\/(login|logout|signout|cart|checkout|session|admin|wp-admin)(\/|$)/i;
export function normalizeCrawlUrl(value: string, root?: URL): URL { const url = new URL(value, root); url.hash = ""; url.username = ""; url.password = ""; url.search = ""; url.pathname = url.pathname.replace(/\/{2,}/g, "/").replace(/\/$/, "") || "/"; return url; }
function isPrivateIp(ip: string): boolean { if (ip === "::1" || ip.startsWith("fe80:") || ip.startsWith("fc") || ip.startsWith("fd")) return true; const parts = ip.split(".").map(Number); return parts.length === 4 && (parts[0] === 10 || parts[0] === 127 || parts[0] === 0 || (parts[0] === 169 && parts[1] === 254) || (parts[0] === 172 && parts[1] >= 16 && parts[1] <= 31) || (parts[0] === 192 && parts[1] === 168)); }
export async function assertPublicHttpTarget(url: URL, resolver = lookup): Promise<void> { if (!['https:', 'http:'].includes(url.protocol) || (url.protocol === 'http:' && url.port && url.port !== '80') || (url.protocol === 'https:' && url.port && url.port !== '443')) throw new Error("CRAWL_TARGET_NOT_ALLOWED"); const host = url.hostname.toLowerCase(); if (host === "localhost" || host.endsWith(".local") || host.endsWith(".internal")) throw new Error("CRAWL_PRIVATE_TARGET_BLOCKED"); if (isIP(host)) { if (isPrivateIp(host)) throw new Error("CRAWL_PRIVATE_TARGET_BLOCKED"); return; } const addresses = await resolver(host, { all: true }); if (!addresses.length || addresses.some((a) => isPrivateIp(a.address))) throw new Error("CRAWL_PRIVATE_TARGET_BLOCKED"); }
function text(html: string, regex: RegExp): string | undefined { return regex.exec(html)?.[1]?.replace(/\s+/g, " ").trim(); }
export function extractSeoPage(url: string, status: number, html: string): TechnicalPage { const canonical = text(html, /<link[^>]+rel=["'][^"']*canonical[^"']*["'][^>]+href=["']([^"']+)/i) ?? text(html, /<link[^>]+href=["']([^"']+)["'][^>]+rel=["'][^"']*canonical/i); const robots = text(html, /<meta[^>]+name=["']robots["'][^>]+content=["']([^"']+)/i); const links = [...html.matchAll(/<a[^>]+href=["']([^"']+)["']/gi)].map((m) => m[1]); const images = [...html.matchAll(/<img\b[^>]*>/gi)].map((m) => m[0]); const schemas = [...html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)].flatMap((m) => { try { const parsed = JSON.parse(m[1]); const entries = Array.isArray(parsed) ? parsed : [parsed]; return entries.map((v) => v?.["@type"]).filter(Boolean); } catch { return ["INVALID_JSON_LD"]; } }); return { url, status, indexable: status < 400 && !/noindex/i.test(robots ?? ""), robots, canonical, title: text(html, /<title[^>]*>([\s\S]*?)<\/title>/i), metaDescription: text(html, /<meta[^>]+name=["']description["'][^>]+content=["']([^"']+)/i), h1Count: (html.match(/<h1\b/gi) ?? []).length, imageCount: images.length, imagesWithAlt: images.filter((tag) => /\balt=["'][^"']*["']/i.test(tag)).length, structuredDataTypes: schemas, internalLinks: links } as TechnicalPage; }
export async function crawlWebsite(rootValue: string, options: { limits?: Partial<CrawlLimits>; fetcher?: typeof fetch; resolver?: typeof lookup; signal?: AbortSignal } = {}): Promise<{ pages: TechnicalPage[]; errors: Array<{ url: string; error: string }>; truncated: boolean; robotsPresent: boolean; sitemapPresent: boolean }> { const root = normalizeCrawlUrl(rootValue); await assertPublicHttpTarget(root, options.resolver); const configured = { ...DEFAULT_CRAWL_LIMITS, ...options.limits }; const limits = { ...configured, maxPages: Math.min(HARD_CRAWL_CEILING, Math.max(1, configured.maxPages)), concurrency: Math.min(4, Math.max(1, configured.concurrency)) }; const fetcher = options.fetcher ?? fetch; const queue: Array<{ url: URL; depth: number }> = [{ url: root, depth: 0 }]; const seen = new Set<string>(); const pages: TechnicalPage[] = []; const errors: Array<{ url: string; error: string }> = []; const deadline = Date.now() + limits.totalTimeoutMs; let robotsPresent = false; let sitemapPresent = false; const disallowed: string[] = [];
  try { const robotsResponse = await fetcher(new URL("/robots.txt", root), { redirect: "manual", headers: { "User-Agent": "StratxcelSearchAudit/1.0 (+https://stratxcel.in/support)" } }); if (robotsResponse.ok) { robotsPresent = true; const robotsText = (await robotsResponse.text()).slice(0, 200_000); let relevant = false; for (const line of robotsText.split(/\r?\n/)) { const [rawKey, ...rest] = line.split(":"); const key = rawKey.trim().toLowerCase(); const value = rest.join(":").trim(); if (key === "user-agent") relevant = value === "*" || /stratxcel/i.test(value); else if (relevant && key === "disallow" && value) disallowed.push(value); else if (key === "sitemap" && value) sitemapPresent = true; } } } catch { /* robots unavailable is reported, not fatal */ }
  if (!sitemapPresent) try { const sitemapResponse = await fetcher(new URL("/sitemap.xml", root), { redirect: "manual", headers: { "User-Agent": "StratxcelSearchAudit/1.0 (+https://stratxcel.in/support)" } }); sitemapPresent = sitemapResponse.ok && /xml|text/i.test(sitemapResponse.headers.get("content-type") ?? ""); } catch { /* sitemap unavailable */ }
  while (queue.length && pages.length < limits.maxPages && Date.now() < deadline) { const item = queue.shift()!; const normalized = normalizeCrawlUrl(item.url.href); if (seen.has(normalized.href) || normalized.origin !== root.origin || BLOCKED_PATH.test(normalized.pathname) || disallowed.some((path) => normalized.pathname.startsWith(path))) continue; seen.add(normalized.href); try { await assertPublicHttpTarget(normalized, options.resolver); const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), limits.requestTimeoutMs); const response = await fetcher(normalized, { redirect: "manual", headers: { "User-Agent": "StratxcelSearchAudit/1.0 (+https://stratxcel.in/support)", Accept: "text/html" }, signal: options.signal ?? controller.signal }); clearTimeout(timer); if (response.status >= 300 && response.status < 400) { const location = response.headers.get("location"); if (!location) throw new Error("REDIRECT_WITHOUT_LOCATION"); let next = normalizeCrawlUrl(location, normalized); for (let redirects = 0; redirects < limits.maxRedirects; redirects++) { if (next.origin !== root.origin) throw new Error("CROSS_ORIGIN_REDIRECT_BLOCKED"); await assertPublicHttpTarget(next, options.resolver); const redirected = await fetcher(next, { redirect: "manual", headers: { "User-Agent": "StratxcelSearchAudit/1.0 (+https://stratxcel.in/support)", Accept: "text/html" } }); if (!(redirected.status >= 300 && redirected.status < 400)) { const type = redirected.headers.get("content-type") ?? ""; if (!type.includes("text/html")) throw new Error("NON_HTML_SKIPPED"); const html = (await redirected.text()).slice(0, limits.maxResponseBytes); pages.push(extractSeoPage(next.href, redirected.status, html)); break; } const target = redirected.headers.get("location"); if (!target) throw new Error("REDIRECT_WITHOUT_LOCATION"); next = normalizeCrawlUrl(target, next); if (redirects === limits.maxRedirects - 1) throw new Error("REDIRECT_LIMIT_EXCEEDED"); } continue; } const type = response.headers.get("content-type") ?? ""; if (!type.includes("text/html")) continue; const length = Number(response.headers.get("content-length") ?? 0); if (length > limits.maxResponseBytes) throw new Error("RESPONSE_TOO_LARGE"); const html = (await response.text()).slice(0, limits.maxResponseBytes); const page = extractSeoPage(normalized.href, response.status, html); pages.push(page); if (item.depth < limits.maxDepth) for (const link of page.internalLinks ?? []) { try { const next = normalizeCrawlUrl(link, normalized); if (next.origin === root.origin && !seen.has(next.href)) queue.push({ url: next, depth: item.depth + 1 }); } catch { /* malformed link */ } } } catch (error) { errors.push({ url: normalized.href, error: error instanceof Error ? error.message : "CRAWL_FAILED" }); } }
  return { pages, errors, truncated: queue.length > 0 || Date.now() >= deadline, robotsPresent, sitemapPresent };
}
