import { createHash } from "node:crypto";
export interface SearchDb { from(table: string): any; }
export const ACTIVE_OPPORTUNITY_STATES = ["NEW", "ACTIVE", "ACTION_PROPOSED", "AWAITING_APPROVAL", "IN_PROGRESS"] as const;
export function stableFingerprint(parts: Array<string | null | undefined>): string { return createHash("sha256").update(parts.map((p) => (p ?? "").trim().toLowerCase()).join("\u001f")).digest("hex"); }
export async function ensureSearchProject(db: SearchDb, input: { tenantId: string; propertyUrl: string; name: string }) { const { data, error } = await db.from("search_projects").upsert({ tenant_id: input.tenantId, property_url: input.propertyUrl, name: input.name, updated_at: new Date().toISOString() }, { onConflict: "tenant_id,property_url" }).select("*").single(); if (error) throw new Error(`SEARCH_PROJECT_SAVE_FAILED: ${error.message}`); return data; }
export async function startAnalysisRun(db: SearchDb, input: { tenantId: string; projectId: string; runType: string; triggerSource: string; idempotencyKey: string }) { const { data, error } = await db.from("search_analysis_runs").upsert({ tenant_id: input.tenantId, project_id: input.projectId, run_type: input.runType, trigger_source: input.triggerSource, idempotency_key: input.idempotencyKey }, { onConflict: "tenant_id,idempotency_key", ignoreDuplicates: true }).select("*").maybeSingle(); if (error) throw new Error(`SEARCH_RUN_CREATE_FAILED: ${error.message}`); if (data) return { run: data, duplicate: false }; const existing = await db.from("search_analysis_runs").select("*").eq("tenant_id", input.tenantId).eq("idempotency_key", input.idempotencyKey).single(); if (existing.error) throw new Error(`SEARCH_RUN_LOOKUP_FAILED: ${existing.error.message}`); return { run: existing.data, duplicate: true }; }
export async function claimAnalysisRun(db: SearchDb, tenantId: string, runId: string, leaseMinutes = 10) { const now = new Date(); const lease = new Date(now.getTime() + leaseMinutes * 60_000).toISOString(); const { data, error } = await db.from("search_analysis_runs").update({ state: "RUNNING", started_at: now.toISOString(), heartbeat_at: now.toISOString(), lease_expires_at: lease }).eq("id", runId).eq("tenant_id", tenantId).in("state", ["CREATED", "RETRY_WAIT"]).lt("attempt_count", 3).select("*").maybeSingle(); if (error) throw new Error(`SEARCH_RUN_CLAIM_FAILED: ${error.message}`); return data ?? null; }
export async function completeAnalysisRun(db: SearchDb, input: { tenantId: string; runId: string; partial?: boolean; summaryCounts: Record<string, number>; providerAvailability: Record<string, unknown> }) { const { data, error } = await db.from("search_analysis_runs").update({ state: input.partial ? "PARTIAL" : "COMPLETED", completed_at: new Date().toISOString(), lease_expires_at: null, summary_counts: input.summaryCounts, provider_availability: input.providerAvailability, failure_reason: null }).eq("id", input.runId).eq("tenant_id", input.tenantId).select("*").single(); if (error) throw new Error(`SEARCH_RUN_COMPLETE_FAILED: ${error.message}`); return data; }
export async function failAnalysisRun(db: SearchDb, input: { tenantId: string; runId: string; reason: string; attemptCount: number }) { const terminal = input.attemptCount >= 3; const { data, error } = await db.from("search_analysis_runs").update({ state: terminal ? "FAILED" : "RETRY_WAIT", attempt_count: input.attemptCount, completed_at: terminal ? new Date().toISOString() : null, lease_expires_at: null, failure_reason: input.reason.slice(0, 500) }).eq("id", input.runId).eq("tenant_id", input.tenantId).select("*").single(); if (error) throw new Error(`SEARCH_RUN_FAIL_FAILED: ${error.message}`); return data; }
export async function saveOpportunities(db: SearchDb, input: { tenantId: string; projectId: string; runId: string; opportunities: Array<{ fingerprint: string; category: string; severity: string; priority: number; evidence: unknown; affectedUrl?: string; affectedQuery?: string; businessRationale: string; proposedAction: string }> }) { const now = new Date().toISOString(); const seen = input.opportunities.map((o) => o.fingerprint); for (const o of input.opportunities) { const existing = await db.from("search_opportunities").select("status,recurrence_count").eq("tenant_id", input.tenantId).eq("project_id", input.projectId).eq("fingerprint", o.fingerprint).maybeSingle(); if (existing.error) throw new Error(`SEARCH_OPPORTUNITY_LOOKUP_FAILED: ${existing.error.message}`); const recurrence = existing.data && ["RESOLVED", "SUPERSEDED"].includes(existing.data.status) ? (existing.data.recurrence_count ?? 0) + 1 : (existing.data?.recurrence_count ?? 0); const { error } = await db.from("search_opportunities").upsert({ tenant_id: input.tenantId, project_id: input.projectId, source_run_id: input.runId, fingerprint: o.fingerprint, category: o.category, severity: o.severity, priority: o.priority, evidence: o.evidence, affected_url: o.affectedUrl ?? null, affected_query: o.affectedQuery ?? null, business_rationale: o.businessRationale, proposed_action: o.proposedAction, status: "ACTIVE", recurrence_count: recurrence, last_seen_at: now, resolved_at: null, updated_at: now }, { onConflict: "tenant_id,project_id,fingerprint" }); if (error) throw new Error(`SEARCH_OPPORTUNITY_SAVE_FAILED: ${error.message}`); }
  let stale = db.from("search_opportunities").update({ status: "RESOLVED", resolved_at: now, updated_at: now }).eq("tenant_id", input.tenantId).eq("project_id", input.projectId).in("status", [...ACTIVE_OPPORTUNITY_STATES]); if (seen.length) stale = stale.not("fingerprint", "in", `(${seen.join(",")})`); const { error } = await stale; if (error) throw new Error(`SEARCH_OPPORTUNITY_RESOLVE_FAILED: ${error.message}`); }
export async function saveRecommendation(db: SearchDb, input: { tenantId: string; opportunityId: string; runId: string; fingerprint: string; evidence: unknown; proposedChange: unknown; actionClass: string }) { const { data, error } = await db.from("search_recommendations").upsert({ tenant_id: input.tenantId, opportunity_id: input.opportunityId, source_run_id: input.runId, fingerprint: input.fingerprint, evidence: input.evidence, proposed_change: input.proposedChange, action_class: input.actionClass, status: "ACTIVE" }, { onConflict: "tenant_id,opportunity_id,fingerprint" }).select("*").single(); if (error) throw new Error(`SEARCH_RECOMMENDATION_SAVE_FAILED: ${error.message}`); return data; }
export async function createSearchAction(db: SearchDb, input: { tenantId: string; recommendationId: string; actionClass: string; approvalId?: string }) { const state = input.actionClass === "approval_required" ? "AWAITING_APPROVAL" : input.actionClass === "manual_provider_required" ? "MANUAL_REQUIRED" : "PROPOSED"; const { data, error } = await db.from("search_actions").upsert({ tenant_id: input.tenantId, recommendation_id: input.recommendationId, action_class: input.actionClass, approval_id: input.approvalId ?? null, state }, { onConflict: "tenant_id,recommendation_id", ignoreDuplicates: true }).select("*").maybeSingle(); if (error) throw new Error(`SEARCH_ACTION_CREATE_FAILED: ${error.message}`); if (data) return data; const existing = await db.from("search_actions").select("*").eq("tenant_id", input.tenantId).eq("recommendation_id", input.recommendationId).single(); if (existing.error) throw new Error(`SEARCH_ACTION_LOOKUP_FAILED: ${existing.error.message}`); return existing.data; }
export async function recordActionResult(db: SearchDb, input: { tenantId: string; actionId: string; state: "COMPLETED" | "FAILED"; result: unknown; afterEvidence?: unknown }) { const { data, error } = await db.from("search_actions").update({ state: input.state, execution_result: input.result, after_evidence: input.afterEvidence ?? {}, completed_at: new Date().toISOString(), updated_at: new Date().toISOString() }).eq("id", input.actionId).eq("tenant_id", input.tenantId).select("*").single(); if (error) throw new Error(`SEARCH_ACTION_RESULT_FAILED: ${error.message}`); return data; }
export async function saveMeasurementSnapshot(db: SearchDb, input: { tenantId: string; projectId: string; runId: string; source: string; dimensions: unknown; values: unknown; availabilityState: string; unavailableReason?: string; fingerprint: string; periodStart?: string; periodEnd?: string }) { const { data, error } = await db.from("search_measurement_snapshots").upsert({ tenant_id: input.tenantId, project_id: input.projectId, source_run_id: input.runId, source: input.source, dimensions: input.dimensions, values: input.values, availability_state: input.availabilityState, unavailable_reason: input.unavailableReason ?? null, fingerprint: input.fingerprint, period_start: input.periodStart ?? null, period_end: input.periodEnd ?? null, captured_at: new Date().toISOString() }, { onConflict: "tenant_id,project_id,fingerprint" }).select("*").single(); if (error) throw new Error(`SEARCH_SNAPSHOT_SAVE_FAILED: ${error.message}`); return data; }
export async function listSearchState(db: SearchDb, tenantId: string) {
  const [projects, runs, opportunities, recommendations, actions, snapshots] = await Promise.all([
    db.from("search_projects").select("id, name, property_url, updated_at").eq("tenant_id", tenantId).order("updated_at", { ascending: false }).limit(5),
    db.from("search_analysis_runs").select("id, run_type, trigger_source, state, summary_counts, failure_reason, created_at").eq("tenant_id", tenantId).order("created_at", { ascending: false }).limit(10),
    db.from("search_opportunities").select("id, category, severity, priority, business_rationale, proposed_action, status").eq("tenant_id", tenantId).order("priority", { ascending: false }).limit(50),
    db.from("search_recommendations").select("id, opportunity_id, action_class, status, created_at").eq("tenant_id", tenantId).order("created_at", { ascending: false }).limit(50),
    db.from("search_actions").select("id, recommendation_id, action_class, state, created_at").eq("tenant_id", tenantId).order("created_at", { ascending: false }).limit(50),
    db.from("search_measurement_snapshots").select("id, source, dimensions, values, availability_state, unavailable_reason, captured_at").eq("tenant_id", tenantId).order("captured_at", { ascending: false }).limit(20)
  ]);
  for (const result of [projects, runs, opportunities, recommendations, actions, snapshots]) {
    if (result.error) throw new Error(`SEARCH_STATE_READ_FAILED: ${result.error.message}`);
  }
  return {
    projects: projects.data ?? [],
    runs: runs.data ?? [],
    opportunities: opportunities.data ?? [],
    recommendations: recommendations.data ?? [],
    actions: actions.data ?? [],
    snapshots: snapshots.data ?? []
  };
}
export const SEARCH_RETENTION_POLICY = { rawHtmlPersisted: false, terminalRunDays: 400, recommendationAndActionHistory: "preserved", snapshotStrategy: "daily source fingerprints replace duplicates" } as const;
export async function compactSearchHistory(db: SearchDb, tenantId: string, cutoff = new Date(Date.now() - SEARCH_RETENTION_POLICY.terminalRunDays * 86_400_000).toISOString()) { const { error } = await db.from("search_analysis_runs").delete().eq("tenant_id", tenantId).in("state", ["COMPLETED", "PARTIAL", "FAILED"]).lt("completed_at", cutoff); if (error) throw new Error(`SEARCH_HISTORY_COMPACTION_FAILED: ${error.message}`); }
