import { recordAuditEvent } from "@stratxcel/audit";
import { requestApproval } from "@stratxcel/approvals";
import { analyzeTechnicalSeo } from "./technical.ts";
import { CRAWL_LIMITS, crawlWebsite } from "./crawler.ts";
import { completeAnalysisRun, createSearchAction, ensureSearchProject, failAnalysisRun, saveMeasurementSnapshot, saveOpportunities, saveRecommendation, stableFingerprint, startAnalysisRun, type SearchDb } from "./repository.ts";
import type { ProviderConnection, TechnicalPage } from "./types.ts";
export const SEARCH_RUNTIME_FLAGS = { schedulerEnabled: process.env.SEARCH_DISCOVERY_SCHEDULER_ENABLED === "true", crawlEnabled: process.env.SEARCH_DISCOVERY_CRAWL_ENABLED === "true" } as const;
export const SEARCH_MAX_ATTEMPTS = 3;
export type RuntimePlan = keyof typeof CRAWL_LIMITS;
export interface SearchRuntimeInput { tenantId: string; actorUserId?: string; propertyUrl: string; propertyName: string; plan: RuntimePlan; runType: "lightweight" | "weekly" | "monthly" | "manual"; triggerSource: "manual" | "scheduler" | "internal"; idempotencyKey: string; }
async function event(db: SearchDb, input: SearchRuntimeInput, action: string, runId: string, metadata: Record<string, unknown> = {}) { await recordAuditEvent(db as any, { tenantId: input.tenantId, actorUserId: input.actorUserId, actorKind: input.actorUserId ? "user" : "system", action, targetType: "search_analysis_run", targetId: runId, metadata }); }
export interface ProviderSnapshotInput { dimensions: unknown; values: unknown; periodStart?: string; periodEnd?: string }
export async function runSearchAnalysis(db: SearchDb, input: SearchRuntimeInput, options: { pages?: TechnicalPage[]; crawl?: typeof crawlWebsite; providerStates?: ProviderConnection[]; providerSnapshots?: Record<string, ProviderSnapshotInput> } = {}) { const project = await ensureSearchProject(db, { tenantId: input.tenantId, propertyUrl: input.propertyUrl, name: input.propertyName }); const started = await startAnalysisRun(db, { tenantId: input.tenantId, projectId: project.id, runType: input.runType, triggerSource: input.triggerSource, idempotencyKey: input.idempotencyKey }); if (started.duplicate) return { run: started.run, duplicate: true };
  const run = started.run; await db.from("search_analysis_runs").update({ state: "RUNNING", started_at: new Date().toISOString(), attempt_count: 1, lease_expires_at: new Date(Date.now() + 10 * 60_000).toISOString(), heartbeat_at: new Date().toISOString() }).eq("id", run.id).eq("tenant_id", input.tenantId); await event(db, input, "SEARCH_RUN_CREATED", run.id); await event(db, input, "SEARCH_RUN_STARTED", run.id);
  try { let pages = options.pages ?? []; let crawlErrors: Array<{ url: string; error: string }> = []; let robotsPresent = false; let sitemapPresent = false; if (!pages.length && SEARCH_RUNTIME_FLAGS.crawlEnabled && project.ownership_verified) { await event(db, input, "SEARCH_CRAWL_STARTED", run.id); const result = await (options.crawl ?? crawlWebsite)(input.propertyUrl, { limits: { maxPages: CRAWL_LIMITS[input.plan] } }); pages = result.pages; crawlErrors = result.errors; robotsPresent = result.robotsPresent; sitemapPresent = result.sitemapPresent; await event(db, input, "SEARCH_CRAWL_COMPLETED", run.id, { pages: pages.length, errors: crawlErrors.length, truncated: result.truncated }); } else if (!pages.length) await event(db, input, "SEARCH_PROVIDER_SKIPPED", run.id, { provider: "first_party_crawl", state: project.ownership_verified ? "configuration_required" : "permission_required" }); else { robotsPresent = true; sitemapPresent = true; }
    const issues = analyzeTechnicalSeo(pages, { https: input.propertyUrl.startsWith("https://"), robotsPresent, sitemapPresent }); const opportunities = issues.map((issue) => ({ fingerprint: stableFingerprint([input.tenantId, input.propertyUrl, issue.code, issue.affectedUrl]), category: `technical:${issue.code}`, severity: issue.severity, priority: issue.severity === "Critical" ? 100 : issue.severity === "High" ? 80 : issue.severity === "Medium" ? 55 : 30, evidence: { evidence: issue.evidence }, affectedUrl: issue.affectedUrl, businessRationale: issue.whyItMatters, proposedAction: issue.recommendedAction })); await saveOpportunities(db, { tenantId: input.tenantId, projectId: project.id, runId: run.id, opportunities });
    for (const issue of issues) { const opportunityFingerprint = stableFingerprint([input.tenantId, input.propertyUrl, issue.code, issue.affectedUrl]); const opportunityResult = await db.from("search_opportunities").select("id").eq("tenant_id", input.tenantId).eq("project_id", project.id).eq("fingerprint", opportunityFingerprint).single(); if (opportunityResult.error) throw new Error(`SEARCH_OPPORTUNITY_LOOKUP_FAILED: ${opportunityResult.error.message}`); const actionClass = issue.approvalRequired ? "approval_required" : "safe_preparatory"; const recommendation = await saveRecommendation(db, { tenantId: input.tenantId, opportunityId: opportunityResult.data.id, runId: run.id, fingerprint: stableFingerprint([opportunityFingerprint, issue.recommendedAction]), evidence: { evidence: issue.evidence }, proposedChange: { recommendation: issue.recommendedAction, affectedUrl: issue.affectedUrl }, actionClass }); const existingAction = await db.from("search_actions").select("id").eq("tenant_id", input.tenantId).eq("recommendation_id", recommendation.id).maybeSingle(); if (!existingAction.data) { let approvalId: string | undefined; if (actionClass === "approval_required") { const approval = await requestApproval(db as any, { tenantId: input.tenantId, kind: "other", requestedBy: input.actorUserId, subject: { type: "search_recommendation", recommendationId: recommendation.id, affectedUrl: issue.affectedUrl, proposedChange: issue.recommendedAction } }); approvalId = approval.id; } await createSearchAction(db, { tenantId: input.tenantId, recommendationId: recommendation.id, actionClass, approvalId }); } await db.from("search_opportunities").update({ status: actionClass === "approval_required" ? "AWAITING_APPROVAL" : "ACTION_PROPOSED", updated_at: new Date().toISOString() }).eq("id", opportunityResult.data.id).eq("tenant_id", input.tenantId); }
    const providerStates = options.providerStates ?? [{ provider: "search_console", state: "not_connected", reason: "No tenant-scoped authenticated connection." }, { provider: "ga4", state: "not_connected", reason: "No tenant-scoped authenticated connection." }, { provider: "google_business_profile", state: "configuration_required", reason: "Owner connection required." }, { provider: "meta", state: "permission_required", reason: "Reporting permission required." }] as ProviderConnection[]; for (const provider of providerStates) { const snapshot = options.providerSnapshots?.[provider.provider]; await saveMeasurementSnapshot(db, { tenantId: input.tenantId, projectId: project.id, runId: run.id, source: provider.provider, dimensions: snapshot?.dimensions ?? {}, values: snapshot?.values ?? {}, availabilityState: provider.state, unavailableReason: provider.reason, fingerprint: stableFingerprint([provider.provider, new Date().toISOString().slice(0, 10)]), periodStart: snapshot?.periodStart, periodEnd: snapshot?.periodEnd }); if (provider.state !== "connected") await event(db, input, "SEARCH_PROVIDER_SKIPPED", run.id, { provider: provider.provider, state: provider.state }); }
    await event(db, input, "SEARCH_RECOMMENDATIONS_CREATED", run.id, { opportunities: opportunities.length }); const completed = await completeAnalysisRun(db, { tenantId: input.tenantId, runId: run.id, partial: crawlErrors.length > 0 || !pages.length, summaryCounts: { pages: pages.length, issues: issues.length, crawlErrors: crawlErrors.length }, providerAvailability: Object.fromEntries(providerStates.map((p) => [p.provider, p.state])) }); await event(db, input, "SEARCH_RUN_COMPLETED", run.id, { state: completed.state }); return { run: completed, duplicate: false };
  } catch (error) { const reason = error instanceof Error ? error.message : "SEARCH_ANALYSIS_FAILED"; const failed = await failAnalysisRun(db, { tenantId: input.tenantId, runId: run.id, reason, attemptCount: 1 }); await event(db, input, "SEARCH_RUN_FAILED", run.id, { reason }); return { run: failed, duplicate: false }; }
}
export const SEARCH_SCHEDULES = [{ cadence: "daily", runType: "lightweight" }, { cadence: "weekly", runType: "weekly" }, { cadence: "monthly", runType: "monthly" }] as const;
export function schedulerCanRun(): boolean { return SEARCH_RUNTIME_FLAGS.schedulerEnabled; }
export function retryDelayMs(attempt: number): number | null { if (attempt >= SEARCH_MAX_ATTEMPTS) return null; return Math.min(60_000, 1_000 * 2 ** Math.max(0, attempt - 1)); }
