export const SOLUTION_OUTCOMES = [
  { id: "more-leads", title: "Get more leads", tagline: "Turn more enquiries into customers.", description: "Capture inquiries from your website, campaigns, and WhatsApp in one place.", capabilities: ["Lead capture", "CRM pipeline", "WhatsApp follow-up"], lifecycleId: "convert" },
  { id: "grow-social", title: "Grow on social media", tagline: "Show up consistently where your customers scroll.", description: "Plan social content around your Brand Brain with approval before publish.", capabilities: ["Content planning", "Social Autopilot", "Brand Brain"], lifecycleId: "attention" },
  { id: "rank-google", title: "Rank on Google", tagline: "Help the right people find you when they search.", description: "Review search visibility and prioritize improvements you can measure.", capabilities: ["Search & discovery", "Website", "Performance reports"], lifecycleId: "discovered" },
  { id: "automate-whatsapp", title: "Automate WhatsApp", tagline: "Reply faster without losing the personal touch.", description: "Route WhatsApp into your workspace with consent and opt-out rules intact.", capabilities: ["WhatsApp inbox", "Follow-up sequences", "CRM"], lifecycleId: "convert" },
  { id: "improve-website", title: "Build or improve my website", tagline: "Make your site clearer and easier to trust.", description: "Scope website updates with explicit approval before changes go live.", capabilities: ["Website builder", "Domains", "Search readiness"], lifecycleId: "discovered" },
  { id: "manage-customers", title: "Manage customers", tagline: "Know who enquired and what happens next.", description: "Keep leads and follow-up visible in one CRM view.", capabilities: ["CRM", "Conversation history", "Team assignment"], lifecycleId: "manage" },
  { id: "better-content", title: "Create better content", tagline: "Say the right thing in your voice.", description: "Draft posts and campaigns from reviewed brand context.", capabilities: ["Creative studio", "Brand Brain", "Content calendar"], lifecycleId: "attention" },
  { id: "understand-business", title: "Understand my business", tagline: "See what is working before you spend more.", description: "Pull performance signals into reports you can act on.", capabilities: ["Analytics", "Reports", "Brand Brain context"], lifecycleId: "performance" },
  { id: "automate-work", title: "Automate repetitive work", tagline: "Stop doing the same tasks by hand every week.", description: "Use missions and automations with human approval where it matters.", capabilities: ["Missions", "Automations", "AI workforce"], lifecycleId: "automate" },
  { id: "launch-grow", title: "Launch or grow a business", tagline: "Start with clarity, then build momentum.", description: "Begin with research and a prioritized roadmap.", capabilities: ["Business Growth Audit", "Strategy", "Connected execution"], lifecycleId: "discovered" },
] as const;
export function getOutcomeById(id: string) { return SOLUTION_OUTCOMES.find((o) => o.id === id); }

export type SolutionOutcomeId = (typeof SOLUTION_OUTCOMES)[number]["id"];
