import type { DepartmentDefinition, DepartmentKey } from "./types.ts";
import { DEPARTMENT_KEYS, isDepartmentKey } from "./types.ts";

type DeptInput = Omit<DepartmentDefinition, "key"> & { key: DepartmentKey };

function dept(d: DeptInput): DepartmentDefinition {
  return d;
}

function roles(entries: Array<[string, string, string]>) {
  return entries.map(([key, label, purpose]) => ({ key, label, purpose }));
}

const DEFINITIONS: DeptInput[] = [
  dept({
    key: "executive",
    label: "Executive",
    mission: "Align missions to business outcomes and record accountable decisions.",
    responsibilities: ["Translate leadership intent into mission scope", "Prioritize cross-department work", "Record decisions and trade-offs", "Ensure missions stay within policy guardrails"],
    specialistRoles: roles([["ceo_delegate", "CEO delegate", "Represents executive intent and approves mission direction."], ["mission_coordinator", "Mission coordinator", "Orchestrates mission scope, owners, and handoffs."], ["decision_recorder", "Decision recorder", "Captures decisions, rationale, and accountability."]]),
    acceptedInputArtifactClasses: ["mission_brief", "strategy_memo", "executive_request"],
    outputArtifactClasses: ["mission_charter", "decision_log", "executive_summary"],
    defaultQualityGates: ["strategic_alignment", "scope_clarity", "policy_fit"],
    requestableCapabilityClasses: ["analytics.read", "report.generate"],
    riskLevel: "low",
    externalMutationEverPermitted: false,
    defaultMaxRevisionCount: 2,
    defaultEvidenceRequirement: "recommended",
    releaseClassification: "foundation",
  }),
  dept({
    key: "strategy",
    label: "Strategy",
    mission: "Design channel and growth strategy that guides downstream execution.",
    responsibilities: ["Define audience and channel priorities", "Translate business goals into campaign plans", "Align brand and paid plans to strategic bets", "Recommend sequencing and learning milestones"],
    specialistRoles: roles([["growth_strategist", "Growth strategist", "Designs growth bets and measurable outcomes."], ["channel_strategist", "Channel strategist", "Selects and prioritizes channels."], ["campaign_planner", "Campaign planner", "Builds campaign architecture and dependencies."]]),
    acceptedInputArtifactClasses: ["mission_brief", "market_context", "performance_snapshot"],
    outputArtifactClasses: ["strategy_memo", "campaign_plan", "channel_plan"],
    defaultQualityGates: ["strategic_alignment", "audience_fit", "feasibility"],
    requestableCapabilityClasses: ["research.web", "analytics.read", "report.generate"],
    riskLevel: "medium",
    externalMutationEverPermitted: false,
    defaultMaxRevisionCount: 3,
    defaultEvidenceRequirement: "recommended",
    releaseClassification: "foundation",
  }),
  dept({
    key: "research",
    label: "Research",
    mission: "Produce evidence-backed insight that de-risks strategy and creative choices.",
    responsibilities: ["Gather and cite market and audience signals", "Validate claims before customer-facing work", "Surface trends with traceable sources", "Review evidence quality before handoff"],
    specialistRoles: roles([["market_researcher", "Market researcher", "Maps market size and category dynamics."], ["audience_researcher", "Audience researcher", "Profiles audience needs and intent."], ["competitor_researcher", "Competitor researcher", "Analyzes competitor positioning."], ["trend_researcher", "Trend researcher", "Tracks emerging trends."], ["evidence_reviewer", "Evidence reviewer", "Validates source quality and citations."]]),
    acceptedInputArtifactClasses: ["research_brief", "keyword_brief", "competitor_list"],
    outputArtifactClasses: ["research_evidence", "research_summary", "serp_evidence"],
    defaultQualityGates: ["evidence_sufficiency", "source_quality", "claim_accuracy"],
    requestableCapabilityClasses: ["research.web", "research.serp", "analytics.read"],
    riskLevel: "low",
    externalMutationEverPermitted: false,
    defaultMaxRevisionCount: 2,
    defaultEvidenceRequirement: "required",
    releaseClassification: "foundation",
  }),
  dept({
    key: "brand",
    label: "Brand",
    mission: "Protect and express brand identity, voice, and offer positioning.",
    responsibilities: ["Maintain voice and messaging guardrails", "Position offers against competitive context", "Review creative for brand consistency", "Provide brand slices to downstream teams"],
    specialistRoles: roles([["brand_strategist", "Brand strategist", "Defines brand narrative and differentiation."], ["voice_guardian", "Voice guardian", "Enforces tone and messaging rules."], ["offer_positioning_specialist", "Offer positioning specialist", "Frames offers for clarity and fit."]]),
    acceptedInputArtifactClasses: ["brand_slice", "offer_brief", "research_summary"],
    outputArtifactClasses: ["brand_guidance", "positioning_memo", "voice_rules"],
    defaultQualityGates: ["brand_fit", "message_clarity", "differentiation"],
    requestableCapabilityClasses: ["research.web", "content.shortform", "content.longform"],
    riskLevel: "medium",
    externalMutationEverPermitted: false,
    defaultMaxRevisionCount: 3,
    defaultEvidenceRequirement: "recommended",
    releaseClassification: "foundation",
  }),
  dept({
    key: "creative",
    label: "Creative",
    mission: "Develop concepts and art direction that express strategy in memorable form.",
    responsibilities: ["Translate briefs into creative territories", "Define visual direction for assets", "Collaborate on cohesive storytelling", "Iterate against brand feedback"],
    specialistRoles: roles([["creative_director", "Creative director", "Sets creative vision and approves direction."], ["concept_developer", "Concept developer", "Explores territories and campaign ideas."], ["art_director", "Art director", "Defines visual systems and asset direction."]]),
    acceptedInputArtifactClasses: ["content_brief", "brand_slice", "campaign_plan"],
    outputArtifactClasses: ["creative_concept", "art_direction", "moodboard"],
    defaultQualityGates: ["brand_fit", "concept_clarity", "visual_quality"],
    requestableCapabilityClasses: ["media.image_generation", "media.carousel_generation", "content.shortform"],
    riskLevel: "medium",
    externalMutationEverPermitted: false,
    defaultMaxRevisionCount: 4,
    defaultEvidenceRequirement: "none",
    releaseClassification: "foundation",
  }),
  dept({
    key: "content",
    label: "Content",
    mission: "Write persuasive copy and narratives aligned to brand and channel needs.",
    responsibilities: ["Produce short-form and long-form copy", "Adapt messaging for channel and audience", "Edit for clarity and brand fit", "Collaborate with SEO and social"],
    specialistRoles: roles([["copywriter", "Copywriter", "Writes hooks, captions, and conversion copy."], ["scriptwriter", "Scriptwriter", "Drafts scripts for video and audio."], ["longform_writer", "Long-form writer", "Produces articles and guides."], ["editor", "Editor", "Refines structure, tone, and readability."]]),
    acceptedInputArtifactClasses: ["content_brief", "brand_slice", "seo_brief"],
    outputArtifactClasses: ["shortform_copy", "longform_draft", "script", "caption_set"],
    defaultQualityGates: ["brand_fit", "message_clarity", "claim_accuracy"],
    requestableCapabilityClasses: ["content.shortform", "content.longform", "seo.article"],
    riskLevel: "medium",
    externalMutationEverPermitted: false,
    defaultMaxRevisionCount: 4,
    defaultEvidenceRequirement: "recommended",
    releaseClassification: "foundation",
  }),
  dept({
    key: "media",
    label: "Media",
    mission: "Produce image, carousel, and video assets that meet brand and channel specs.",
    responsibilities: ["Generate still, carousel, and motion creatives", "Follow art direction and format constraints", "Prepare assets for social and ads", "Coordinate storyboards for video work"],
    specialistRoles: roles([["image_producer", "Image producer", "Creates still image assets."], ["carousel_designer", "Carousel designer", "Builds multi-slide carousel creatives."], ["video_producer", "Video producer", "Produces short-form video assets."], ["reel_producer", "Reel producer", "Optimizes vertical short video."], ["storyboard_artist", "Storyboard artist", "Plans shot sequences for video."]]),
    acceptedInputArtifactClasses: ["art_direction", "image_brief", "carousel_brief", "video_brief", "storyboard"],
    outputArtifactClasses: ["image_candidate", "image_final", "carousel_candidate", "video_candidate", "reel_candidate"],
    defaultQualityGates: ["brand_fit", "visual_quality", "format_compliance"],
    requestableCapabilityClasses: ["media.image_generation", "media.carousel_generation", "media.video_generation"],
    riskLevel: "medium",
    externalMutationEverPermitted: false,
    defaultMaxRevisionCount: 4,
    defaultEvidenceRequirement: "recommended",
    releaseClassification: "foundation",
  }),
  dept({
    key: "social",
    label: "Social",
    mission: "Plan, schedule, and publish social content with governed external mutation.",
    responsibilities: ["Define social calendars and adaptations", "Schedule and publish approved content", "Monitor engagement signals", "Coordinate performance loops"],
    specialistRoles: roles([["social_strategist", "Social strategist", "Plans platform mix and cadence."], ["community_manager", "Community manager", "Guides community tone and responses."], ["scheduling_specialist", "Scheduling specialist", "Schedules approved posts."], ["engagement_analyst", "Engagement analyst", "Interprets engagement metrics."]]),
    acceptedInputArtifactClasses: ["social_brief", "social_final", "content_brief"],
    outputArtifactClasses: ["social_plan", "schedule_receipt", "publish_receipt"],
    defaultQualityGates: ["brand_fit", "platform_compliance", "timing_fit"],
    requestableCapabilityClasses: ["social.schedule", "social.publish", "analytics.read"],
    riskLevel: "critical",
    externalMutationEverPermitted: true,
    defaultMaxRevisionCount: 3,
    defaultEvidenceRequirement: "recommended",
    releaseClassification: "foundation",
  }),
  dept({
    key: "seo",
    label: "SEO",
    mission: "Improve discoverability through keyword research and on-page optimization.",
    responsibilities: ["Research keywords and search intent", "Audit on-page SEO", "Produce search-oriented articles", "Plan internal linking structure"],
    specialistRoles: roles([["keyword_researcher", "Keyword researcher", "Builds keyword maps."], ["serp_researcher", "SERP researcher", "Analyzes SERP composition."], ["seo_writer", "SEO writer", "Drafts search-oriented articles."], ["onpage_optimizer", "On-page optimizer", "Optimizes titles and metadata."], ["internal_linking_specialist", "Internal linking specialist", "Designs internal link architecture."]]),
    acceptedInputArtifactClasses: ["seo_brief", "keyword_brief", "website_snapshot"],
    outputArtifactClasses: ["keyword_map", "seo_audit_report", "seo_article_draft"],
    defaultQualityGates: ["search_intent_fit", "technical_correctness", "content_quality"],
    requestableCapabilityClasses: ["research.serp", "seo.audit", "seo.article"],
    riskLevel: "low",
    externalMutationEverPermitted: false,
    defaultMaxRevisionCount: 3,
    defaultEvidenceRequirement: "recommended",
    releaseClassification: "foundation",
  }),
  dept({
    key: "website",
    label: "Website",
    mission: "Design, generate, and deploy landing experiences under governed release controls.",
    responsibilities: ["Architect page structure and UX flows", "Generate landing page drafts", "Coordinate copy and media requirements", "Deploy approved website changes"],
    specialistRoles: roles([["ux_architect", "UX architect", "Designs page structure and flows."], ["page_copy_specialist", "Page copy specialist", "Writes landing page copy."], ["landing_page_builder", "Landing page builder", "Assembles page drafts."], ["deploy_coordinator", "Deploy coordinator", "Coordinates governed deployment."]]),
    acceptedInputArtifactClasses: ["page_brief", "website_draft", "website_approved"],
    outputArtifactClasses: ["website_draft", "website_approved", "deploy_receipt"],
    defaultQualityGates: ["brand_fit", "ux_clarity", "conversion_fit"],
    requestableCapabilityClasses: ["website.generate", "website.deploy", "content.longform"],
    riskLevel: "critical",
    externalMutationEverPermitted: true,
    defaultMaxRevisionCount: 4,
    defaultEvidenceRequirement: "recommended",
    releaseClassification: "foundation",
  }),
  dept({
    key: "advertising",
    label: "Advertising",
    mission: "Plan and publish paid campaigns with spend and creative governance.",
    responsibilities: ["Build media plans and targeting structures", "Write and test ad copy variants", "Manage bid strategy recommendations", "Publish spend through approved workflows"],
    specialistRoles: roles([["media_planner", "Media planner", "Plans budgets and channel mix."], ["ad_copywriter", "Ad copywriter", "Writes ad copy variants."], ["bid_strategist", "Bid strategist", "Recommends bidding tactics."], ["creative_tester", "Creative tester", "Designs creative tests."]]),
    acceptedInputArtifactClasses: ["campaign_brief", "ads_plan", "ads_plan_approved"],
    outputArtifactClasses: ["ads_plan", "ads_publish_receipt", "creative_test_plan"],
    defaultQualityGates: ["brand_fit", "policy_compliance", "audience_fit"],
    requestableCapabilityClasses: ["ads.plan", "ads.publish", "analytics.read"],
    riskLevel: "critical",
    externalMutationEverPermitted: true,
    defaultMaxRevisionCount: 3,
    defaultEvidenceRequirement: "recommended",
    releaseClassification: "foundation",
  }),
  dept({
    key: "growth",
    label: "Growth",
    mission: "Design funnels, experiments, and retention loops that compound measurable growth.",
    responsibilities: ["Map funnel stages and drop-offs", "Design experiments with clear hypotheses", "Align acquisition and retention initiatives", "Recommend iteration priorities"],
    specialistRoles: roles([["funnel_architect", "Funnel architect", "Maps funnel stages and metrics."], ["experiment_designer", "Experiment designer", "Designs tests with measurement plans."], ["retention_strategist", "Retention strategist", "Plans lifecycle improvement programs."]]),
    acceptedInputArtifactClasses: ["growth_brief", "analytics_evidence", "funnel_snapshot"],
    outputArtifactClasses: ["funnel_map", "experiment_plan", "retention_playbook"],
    defaultQualityGates: ["metric_clarity", "hypothesis_strength", "feasibility"],
    requestableCapabilityClasses: ["analytics.read", "report.generate", "crm.read"],
    riskLevel: "medium",
    externalMutationEverPermitted: false,
    defaultMaxRevisionCount: 3,
    defaultEvidenceRequirement: "recommended",
    releaseClassification: "foundation",
  }),
  dept({
    key: "sales",
    label: "Sales",
    mission: "Enable outreach, proposals, and pipeline motion with governed customer contact.",
    responsibilities: ["Define sales plays and qualification criteria", "Draft outreach and proposal artifacts", "Align messaging with brand and CRM context", "Update pipeline through approved CRM mutations"],
    specialistRoles: roles([["sales_strategist", "Sales strategist", "Designs sales motions and playbooks."], ["outreach_specialist", "Outreach specialist", "Drafts personalized outreach sequences."], ["proposal_writer", "Proposal writer", "Produces proposal drafts."]]),
    acceptedInputArtifactClasses: ["sales_brief", "crm_snapshot", "offer_brief"],
    outputArtifactClasses: ["outreach_sequence", "proposal_draft", "crm_write_receipt"],
    defaultQualityGates: ["brand_fit", "personalization_fit", "claim_accuracy"],
    requestableCapabilityClasses: ["crm.read", "crm.write", "content.longform"],
    riskLevel: "high",
    externalMutationEverPermitted: true,
    defaultMaxRevisionCount: 3,
    defaultEvidenceRequirement: "recommended",
    releaseClassification: "foundation",
  }),
  dept({
    key: "crm",
    label: "CRM",
    mission: "Maintain accurate lead lifecycle data and segmentation within tenant CRM scope.",
    responsibilities: ["Read and interpret CRM snapshots", "Update lead status and lifecycle stages", "Design segments from agreed criteria", "Coordinate record hygiene with sales"],
    specialistRoles: roles([["crm_analyst", "CRM analyst", "Analyzes CRM data quality and trends."], ["lead_lifecycle_specialist", "Lead lifecycle specialist", "Manages stage transitions."], ["segmentation_specialist", "Segmentation specialist", "Builds audience segments."]]),
    acceptedInputArtifactClasses: ["crm_query", "crm_snapshot", "crm_mutation_request"],
    outputArtifactClasses: ["crm_snapshot", "segment_definition", "crm_write_receipt"],
    defaultQualityGates: ["data_accuracy", "policy_compliance", "segment_clarity"],
    requestableCapabilityClasses: ["crm.read", "crm.write", "analytics.read"],
    riskLevel: "high",
    externalMutationEverPermitted: true,
    defaultMaxRevisionCount: 2,
    defaultEvidenceRequirement: "recommended",
    releaseClassification: "foundation",
  }),
  dept({
    key: "whatsapp",
    label: "WhatsApp",
    mission: "Design and send WhatsApp conversations under consent and approval policy.",
    responsibilities: ["Design conversation flows and templates", "Draft messages respecting consent rules", "Send approved messages through governed channels", "Monitor delivery outcomes"],
    specialistRoles: roles([["conversation_designer", "Conversation designer", "Designs WhatsApp flows and templates."], ["followup_specialist", "Follow-up specialist", "Plans timed follow-ups."], ["consent_guardian", "Consent guardian", "Verifies consent before send actions."]]),
    acceptedInputArtifactClasses: ["whatsapp_brief", "whatsapp_message_draft", "consent_record"],
    outputArtifactClasses: ["conversation_flow", "whatsapp_message_draft", "whatsapp_send_receipt"],
    defaultQualityGates: ["consent_compliance", "brand_fit", "message_clarity"],
    requestableCapabilityClasses: ["whatsapp.send", "crm.read"],
    riskLevel: "critical",
    externalMutationEverPermitted: true,
    defaultMaxRevisionCount: 2,
    defaultEvidenceRequirement: "required",
    releaseClassification: "foundation",
  }),
  dept({
    key: "conversion",
    label: "Conversion",
    mission: "Improve conversion rates through offer, CTA, and page optimization.",
    responsibilities: ["Audit conversion paths", "Optimize offers and CTAs", "Recommend tests from analytics evidence", "Collaborate on landing improvements"],
    specialistRoles: roles([["cro_specialist", "CRO specialist", "Diagnoses conversion leaks."], ["offer_optimizer", "Offer optimizer", "Refines offers and value framing."], ["cta_strategist", "CTA strategist", "Designs CTA hierarchy and copy."]]),
    acceptedInputArtifactClasses: ["page_brief", "funnel_map", "analytics_evidence"],
    outputArtifactClasses: ["cro_audit", "offer_variant", "cta_recommendation"],
    defaultQualityGates: ["conversion_fit", "clarity", "brand_fit"],
    requestableCapabilityClasses: ["analytics.read", "website.generate", "content.shortform"],
    riskLevel: "medium",
    externalMutationEverPermitted: false,
    defaultMaxRevisionCount: 3,
    defaultEvidenceRequirement: "recommended",
    releaseClassification: "foundation",
  }),
  dept({
    key: "analytics",
    label: "Analytics",
    mission: "Turn measured performance signals into actionable insight for the workforce.",
    responsibilities: ["Query and interpret analytics", "Attribute outcomes across channels", "Synthesize decision-ready evidence", "Support reporting and optimization"],
    specialistRoles: roles([["performance_analyst", "Performance analyst", "Tracks KPI trends and anomalies."], ["attribution_analyst", "Attribution analyst", "Attributes outcomes across touchpoints."], ["insight_synthesizer", "Insight synthesizer", "Turns metrics into insights."]]),
    acceptedInputArtifactClasses: ["analytics_query", "campaign_plan", "funnel_map"],
    outputArtifactClasses: ["analytics_evidence", "insight_memo", "metric_snapshot"],
    defaultQualityGates: ["metric_accuracy", "interpretation_clarity", "evidence_sufficiency"],
    requestableCapabilityClasses: ["analytics.read"],
    riskLevel: "low",
    externalMutationEverPermitted: false,
    defaultMaxRevisionCount: 2,
    defaultEvidenceRequirement: "required",
    releaseClassification: "foundation",
  }),
  dept({
    key: "reporting",
    label: "Reporting",
    mission: "Compile structured reports and executive summaries from verified evidence.",
    responsibilities: ["Assemble performance reports", "Curate dashboards for stakeholders", "Summarize outcomes and learnings", "Ensure reports cite sources"],
    specialistRoles: roles([["report_writer", "Report writer", "Compiles structured reports."], ["dashboard_curator", "Dashboard curator", "Organizes metrics into dashboards."], ["executive_summarizer", "Executive summarizer", "Distills outcomes into summaries."]]),
    acceptedInputArtifactClasses: ["report_brief", "analytics_evidence", "mission_charter"],
    outputArtifactClasses: ["report_artifact", "dashboard_spec", "executive_summary"],
    defaultQualityGates: ["accuracy", "narrative_clarity", "evidence_sufficiency"],
    requestableCapabilityClasses: ["analytics.read", "report.generate"],
    riskLevel: "low",
    externalMutationEverPermitted: false,
    defaultMaxRevisionCount: 2,
    defaultEvidenceRequirement: "required",
    releaseClassification: "foundation",
  }),
  dept({
    key: "optimization",
    label: "Optimization",
    mission: "Close learning loops by analyzing experiments and planning iterations.",
    responsibilities: ["Analyze experiment results", "Plan next iterations from evidence", "Synthesize learnings across channels", "Recommend what to scale or pause"],
    specialistRoles: roles([["experiment_analyst", "Experiment analyst", "Evaluates experiment outcomes."], ["iteration_planner", "Iteration planner", "Plans next test cycles."], ["learning_synthesizer", "Learning synthesizer", "Consolidates cross-channel learnings."]]),
    acceptedInputArtifactClasses: ["experiment_plan", "analytics_evidence", "creative_test_plan"],
    outputArtifactClasses: ["experiment_result", "iteration_plan", "learning_memo"],
    defaultQualityGates: ["methodological_rigor", "actionability", "evidence_sufficiency"],
    requestableCapabilityClasses: ["analytics.read", "report.generate"],
    riskLevel: "medium",
    externalMutationEverPermitted: false,
    defaultMaxRevisionCount: 2,
    defaultEvidenceRequirement: "recommended",
    releaseClassification: "foundation",
  }),
  dept({
    key: "quality",
    label: "Quality",
    mission: "Review creative and final outputs before release against quality standards.",
    responsibilities: ["Critique creative work for clarity and fit", "Perform final review before release", "Conduct visual QA on media artifacts", "Escalate defects with specificity"],
    specialistRoles: roles([["creative_critic", "Creative critic", "Reviews concepts and copy for quality."], ["final_reviewer", "Final reviewer", "Performs last-pass review before release."], ["visual_qa", "Visual QA", "Checks visual assets for defects."]]),
    acceptedInputArtifactClasses: ["shortform_copy", "image_final", "social_final", "website_approved"],
    outputArtifactClasses: ["qa_report", "revision_request", "approval_stamp"],
    defaultQualityGates: ["brand_fit", "visual_quality", "completeness"],
    requestableCapabilityClasses: [],
    riskLevel: "low",
    externalMutationEverPermitted: false,
    defaultMaxRevisionCount: 1,
    defaultEvidenceRequirement: "recommended",
    releaseClassification: "foundation",
  }),
  dept({
    key: "compliance",
    label: "Compliance",
    mission: "Verify claims, policies, and brand rules before external-facing release.",
    responsibilities: ["Check marketing claims against evidence", "Validate tenant and regulatory constraints", "Enforce brand rule compliance", "Block releases that fail compliance gates"],
    specialistRoles: roles([["claim_checker", "Claim checker", "Verifies claims are supported."], ["policy_checker", "Policy checker", "Checks outputs against policy."], ["brand_rule_checker", "Brand rule checker", "Ensures artifacts follow brand rules."]]),
    acceptedInputArtifactClasses: ["shortform_copy", "longform_draft", "ads_plan", "whatsapp_message_draft"],
    outputArtifactClasses: ["compliance_report", "claim_review", "policy_clearance"],
    defaultQualityGates: ["claim_accuracy", "policy_compliance", "brand_fit"],
    requestableCapabilityClasses: ["research.web"],
    riskLevel: "medium",
    externalMutationEverPermitted: false,
    defaultMaxRevisionCount: 1,
    defaultEvidenceRequirement: "required",
    releaseClassification: "foundation",
  }),
  dept({
    key: "customer_success",
    label: "Customer success",
    mission: "Support onboarding, retention, and success outcomes for active customers.",
    responsibilities: ["Design onboarding paths and milestones", "Advise on retention plays", "Coordinate with CRM on health signals", "Align success messaging with brand rules"],
    specialistRoles: roles([["success_strategist", "Success strategist", "Defines success plans and milestones."], ["onboarding_specialist", "Onboarding specialist", "Designs onboarding journeys."], ["retention_advisor", "Retention advisor", "Recommends retention interventions."]]),
    acceptedInputArtifactClasses: ["customer_profile", "crm_snapshot", "success_brief"],
    outputArtifactClasses: ["success_plan", "onboarding_playbook", "retention_recommendation"],
    defaultQualityGates: ["customer_fit", "clarity", "policy_compliance"],
    requestableCapabilityClasses: ["crm.read", "content.longform", "whatsapp.send"],
    riskLevel: "medium",
    externalMutationEverPermitted: false,
    defaultMaxRevisionCount: 3,
    defaultEvidenceRequirement: "recommended",
    releaseClassification: "foundation",
  }),
  dept({
    key: "operations",
    label: "Operations",
    mission: "Coordinate capacity, process integrity, and mission execution logistics.",
    responsibilities: ["Coordinate cross-department handoffs", "Plan workforce capacity against demand", "Audit processes for bottlenecks", "Maintain operational visibility"],
    specialistRoles: roles([["ops_coordinator", "Ops coordinator", "Coordinates timelines and logistics."], ["capacity_planner", "Capacity planner", "Balances workload against capacity."], ["process_auditor", "Process auditor", "Audits workflows for gaps."]]),
    acceptedInputArtifactClasses: ["mission_charter", "workflow_snapshot", "capacity_request"],
    outputArtifactClasses: ["ops_plan", "capacity_report", "process_audit"],
    defaultQualityGates: ["feasibility", "timeline_clarity", "dependency_coverage"],
    requestableCapabilityClasses: ["analytics.read", "report.generate"],
    riskLevel: "low",
    externalMutationEverPermitted: false,
    defaultMaxRevisionCount: 2,
    defaultEvidenceRequirement: "none",
    releaseClassification: "foundation",
  }),
  dept({
    key: "engineering",
    label: "Engineering",
    mission: "Design integrations, solutions, and reliability safeguards for workforce execution.",
    responsibilities: ["Architect technical solutions", "Implement and review integrations", "Assess reliability and rollback posture", "Support governed deployment requirements"],
    specialistRoles: roles([["solution_architect", "Solution architect", "Designs technical solutions."], ["integration_specialist", "Integration specialist", "Implements system integrations."], ["reliability_reviewer", "Reliability reviewer", "Reviews failure modes and observability."]]),
    acceptedInputArtifactClasses: ["technical_brief", "integration_spec", "deploy_receipt"],
    outputArtifactClasses: ["solution_design", "integration_plan", "reliability_review"],
    defaultQualityGates: ["technical_correctness", "security_posture", "operational_readiness"],
    requestableCapabilityClasses: ["website.deploy"],
    riskLevel: "medium",
    externalMutationEverPermitted: false,
    defaultMaxRevisionCount: 2,
    defaultEvidenceRequirement: "recommended",
    releaseClassification: "foundation",
  }),
  dept({
    key: "finance",
    label: "Finance",
    mission: "Guard budgets, commercial compliance, and cost discipline across missions.",
    responsibilities: ["Analyze budget allocation against plans", "Monitor spend guardrails", "Review commercial terms and constraints", "Flag financial risk before external mutation"],
    specialistRoles: roles([["budget_analyst", "Budget analyst", "Tracks budgets and allocation."], ["cost_guardian", "Cost guardian", "Enforces spend guardrails."], ["commercial_compliance_reviewer", "Commercial compliance reviewer", "Reviews commercial terms."]]),
    acceptedInputArtifactClasses: ["budget_brief", "ads_plan", "mission_charter"],
    outputArtifactClasses: ["budget_report", "spend_clearance", "commercial_review"],
    defaultQualityGates: ["budget_compliance", "commercial_compliance", "cost_transparency"],
    requestableCapabilityClasses: ["analytics.read", "report.generate", "ads.plan"],
    riskLevel: "medium",
    externalMutationEverPermitted: false,
    defaultMaxRevisionCount: 1,
    defaultEvidenceRequirement: "recommended",
    releaseClassification: "foundation",
  }),
];

export const DEPARTMENT_REGISTRY = Object.fromEntries(
  DEFINITIONS.map((d) => [d.key, d]),
) as Record<DepartmentKey, DepartmentDefinition>;

export function getDepartment(key: string): DepartmentDefinition | undefined {
  if (!isDepartmentKey(key)) return undefined;
  return DEPARTMENT_REGISTRY[key];
}

export function listDepartments(): DepartmentDefinition[] {
  return DEPARTMENT_KEYS.map((k) => DEPARTMENT_REGISTRY[k]);
}

export function assertDepartment(key: string): DepartmentDefinition {
  const deptDef = getDepartment(key);
  if (!deptDef) throw new Error(`unknown_department:${key}`);
  return deptDef;
}
