import type { Metadata } from "next";
import { LegalDocument, LegalList, LegalSection } from "../legal/LegalDocument";
export const metadata: Metadata = { title: "Data Processing Terms — Stratxcel", description: "Data processing terms for supported Stratxcel business services." };
export default function DataProcessingTermsPage() { return <LegalDocument eyebrow="Business privacy" title="Data Processing Terms" intro="These terms apply when Stratxcel processes personal data on behalf of a business client through a supported Service. They supplement the Terms of Service and do not replace a separately signed data-processing agreement.">
  <LegalSection title="Roles and instructions"><p>The client is the controller/data fiduciary or authorized processor for client personal data; Stratxcel is its processor/data processor unless law requires otherwise. The client instructs us to process data to provide, secure, support, and improve the contracted Service, as configured by authorized users and documented in the agreement.</p></LegalSection>
  <LegalSection title="Client obligations"><p>The client must ensure lawful instructions, notices, consents, rights, accuracy, minimization, retention settings, recipient permissions, and a lawful basis for collection, upload, analysis, messaging, disclosure, and international transfer. The client must not instruct processing that violates law or these Terms.</p></LegalSection>
  <LegalSection title="Confidentiality and security"><p>We will ensure persons authorized to process client personal data are bound by confidentiality and will maintain technical and organizational measures appropriate to the nature and risk of the supported Service. Measures may include access controls, tenant scoping, private storage, audit logging, credential protection, and incident procedures. They do not guarantee absolute security.</p></LegalSection>
  <LegalSection title="Subprocessors"><p>The client gives general authorization for subprocessors needed to deliver the Service. We remain responsible for imposing appropriate data-protection obligations on subprocessors to the extent required by law. Material production subprocessors must be identified in the approved provider list; the client may raise a reasonable data-protection objection to a new material subprocessor.</p></LegalSection>
  <LegalSection title="Requests, incidents, and compliance assistance"><LegalList><li>Taking into account the nature of processing, we will provide reasonable assistance for verified individual rights requests that the client cannot fulfil through the Service.</li><li>We will notify the client without undue delay after confirming a personal-data breach affecting client personal data, and provide available information reasonably needed for the client’s obligations.</li><li>We will provide information reasonably necessary to demonstrate compliance and cooperate with proportionate audits, subject to confidentiality, security, scope, frequency, and cost safeguards.</li></LegalList></LegalSection>
  <LegalSection title="Transfers, return, and deletion"><p>Processing may occur where approved subprocessors operate, subject to applicable transfer safeguards. At termination or on documented request, we will delete or return client personal data as supported by the Service, except data retained by law, security needs, backup cycles, or the agreement. Retained data remains protected and isolated from ordinary use.</p></LegalSection>
  <LegalSection title="Processing details"><p><strong>[PLACEHOLDER — complete for each production order: subject matter, duration, nature, purpose, data-subject categories, personal-data categories, sensitive-data restrictions, approved subprocessors, locations, security schedule, deletion period, and client contact]</strong>. Until completed, these terms cover only the processing demonstrably required by enabled app features.</p></LegalSection>
</LegalDocument>; }
