import type { Metadata } from "next";
import Link from "next/link";
import { PublicHeader } from "@/app/components/PublicHeader";
import { PublicFooter } from "@/app/components/PublicFooter";
import { CUSTOMER_OPERATIONS_CONTACTS, DATA_OPERATION_DEFAULTS, OAUTH_OPERATION_DEFAULTS } from "@stratxcel/human-handoff";
export const metadata: Metadata = { title: "Customer Support — Stratxcel", description: "Contact Stratxcel support, billing, security, or grievance operations." };
const channels = [
  { title: "Product and account support", email: CUSTOMER_OPERATIONS_CONTACTS.support, detail: "Onboarding, integrations, provider connections, domains, websites, and Human Assist." },
  { title: "Billing and refunds", email: CUSTOMER_OPERATIONS_CONTACTS.billing, detail: "Invoices, charges, cancellations, payment disputes, and refund requests." },
  { title: "Security and privacy incidents", email: CUSTOMER_OPERATIONS_CONTACTS.security, detail: "Suspected compromise, unauthorized access, vulnerabilities, or urgent privacy incidents." },
  { title: "Grievances and data rights", email: CUSTOMER_OPERATIONS_CONTACTS.grievance, detail: "Formal grievances and verified export, correction, or deletion requests." },
] as const;
export default function SupportPage() { return <div className="flex min-h-screen flex-col bg-sx-bg text-sx-text"><PublicHeader /><main className="mx-auto w-full max-w-6xl flex-1 px-4 py-16 sm:px-6"><p className="font-sx-mono text-xs font-bold uppercase tracking-widest text-sx-accent">Customer operations</p><h1 className="mt-2 text-4xl font-extrabold">How can we help?</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-sx-text-muted">Start with the contact form or the relevant mailbox below. Do not send passwords, OTPs, API keys, access tokens, card details, WABA IDs, phone-number IDs, or webhook URLs.</p><Link href="/contact" className="mt-6 inline-block rounded-sx-sm bg-sx-accent px-6 py-3 text-sm font-bold text-sx-accent-on">Open support request</Link><div className="mt-10 grid gap-4 md:grid-cols-2">{channels.map(c => <section key={c.email} className="rounded-sx-md border border-sx-border bg-sx-surface-1 p-6"><h2 className="font-bold">{c.title}</h2><p className="mt-2 text-sm text-sx-text-muted">{c.detail}</p><a className="mt-3 inline-block text-sm font-semibold text-sx-accent hover:underline" href={`mailto:${c.email}`}>{c.email}</a></section>)}</div><section className="mt-10 rounded-sx-md border border-sx-border bg-sx-surface-1 p-6"><h2 className="font-bold">Disconnect, export, and deletion</h2><p className="mt-2 text-sm leading-6 text-sx-text-muted">{OAUTH_OPERATION_DEFAULTS.disconnect} {OAUTH_OPERATION_DEFAULTS.historicalData}</p><p className="mt-2 text-sm leading-6 text-sx-text-muted">After termination, the default recovery/export window is {DATA_OPERATION_DEFAULTS.recoveryWindowDays} days. Eligible verified deletion is targeted within {DATA_OPERATION_DEFAULTS.deletionTargetDays} days where operationally reasonable; backups normally age out around {DATA_OPERATION_DEFAULTS.backupAgeOutDays} days, subject to lawful exceptions.</p></section><p className="mt-8 text-xs text-sx-text-subtle">Response times depend on issue complexity and available staffing. No guaranteed response SLA is promised on this page.</p></main><PublicFooter /></div>; }
