-- Records the real Agent Factory MVP (agent_definitions table, dynamic
-- toolNameAllowlist resolver, governed create_agent_definition, real
-- AGENT:<key>: dispatch on both WhatsApp and Admin/Client Web Copilot) and
-- the extra-tools registry drift fix found while building it. Applied live
-- via Supabase MCP on 2026-09-02; this file makes it reproducible from a
-- fresh database.

update public.capability_registry
set status = 'REAL_EXPOSED',
    status_notes = 'BUILT FOR REAL 2026-09-02 (not faked): the four missing pieces this row originally identified are now all real. (1) Persisted agent-definition record: agent_definitions table (supabase/migrations/20260902530000_agent_definitions.sql), real CHECK constraints (key shape, non-empty tool list -- the non-empty check was found live, via a real transactional dry-run, to silently admit an empty array because Postgres array_length() returns NULL not 0 for one; fixed in the same migration before any real row existed). (2) Dynamic tool-resolver: packages/agent-core/src/tools/registry.ts gained an additive, opt-in toolNameAllowlist (ResolveToolsOptions), applied BEFORE the existing permission filter so it can only ever narrow a principal''s real tool set, never widen it -- zero behavior change for every existing caller that omits it (13 pre-existing tests + 5 new tool-allowlist.test.ts assertions confirm this). (3) Governed creation flow: create_agent_definition (lib/agent-core/agent-factory-tools.ts) computes the CREATING principal''s own real, permission-filtered tool set via resolveAgentTools and rejects any requested tool name outside it -- real subset enforcement, not a promised one -- gated by a new agent:mutate:agent_definitions permission deliberately restricted to platform_owner only (narrower than this session''s usual owner/admin parity, since this defines OTHER agents'' governed scope). (4) Real dispatch surface: a deterministic "AGENT:<key>: <message>" prefix (lib/agent-core/agent-dispatch.ts, pure parser split into agent-dispatch-parser.ts for standalone testability, 7 test assertions) checked before RESET/CONFIRM/CANCEL/social-mission routing on BOTH WhatsApp and Admin/Client Web Copilot -- a real staff member can create a real, narrower-scoped agent and actually reach it from either channel today. v1 is deliberately staff-only (agent_definitions.tenant_id stays null for every row; no client-created/dispatched agents yet) and create/list only (no edit/disable tool yet -- disabling a bad definition currently needs a direct DB update). Honestly incomplete in that specific, narrow sense; the core "can the architecture actually instantiate a new agent" bar this row was blocked on is now demonstrably met, verified end-to-end (tsc clean, lint clean, full test:agent-core-lib + test:agent-core zero regressions, real NODE_ENV=production build, and a live transactional dry-run insert/rollback against the real schema).',
    external_blocker = null,
    last_verified_at = now(), last_verified_by = 'claude_session_2026-09-02'
where capability_key = 'capability:agent_factory_dynamic_composition';

insert into public.capability_registry
  (capability_key, name, description, category, skill, agent_tool_name, package_or_module, department, connection, required_permission, read_write, tenant_scope, cost_profile, risk, verification_method, status, status_notes, external_blocker, last_verified_at, last_verified_by)
values
  ('capability:extra_tools_registry_drift_fix', 'Fixed a real drift: WhatsApp and Admin/Client Web Copilot had independently-maintained extra-tool arrays that had already diverged', 'Found while building the Agent Factory''s subset-enforcement (needed ONE real source of truth for "every tool a principal could hold" to validate against). WhatsApp''s own EXTRA_TOOLS literal (app/api/internal/agent/whatsapp/route.ts) included SOCIAL_DELEGATION_TOOLS, which lib/agent-core/copilot-actions.ts''s array never had -- Admin Copilot staff could not ask about connected social accounts even though WhatsApp staff could. And copilot-actions.ts had just gained AUDIT_REPORT_LINK_TOOL (Update 58) while the WhatsApp route''s separate literal was never updated -- get_paid_audit_report_link was silently NOT reachable from WhatsApp, directly contradicting this session''s own "wired into both, every time, zero exceptions" discipline. Fixed by extracting lib/agent-core/all-tools.ts (ALL_EXTRA_TOOLS) as the one shared array both real call sites now import -- this class of drift is structurally impossible going forward.', 'ecosystem', null, null, 'lib/agent-core/all-tools.ts', 'Engineering', null, null, 'read', 'platform_only', 'free', 'read', 'Direct comparison of both files'' extra-tool arrays before the fix (confirmed a two-way drift); full-repo tsc --noEmit clean, lint clean, full test:agent-core-lib + test:agent-core suites pass (zero regressions) after consolidating to the shared array.', 'REAL_EXPOSED', 'Both real callers (WhatsApp route, Admin/Client Web Copilot) now import the same ALL_EXTRA_TOOLS array; get_paid_audit_report_link and SOCIAL_DELEGATION_TOOLS are now reachable from both channels.', null, now(), 'claude_session_2026-09-02')
on conflict (capability_key) do nothing;
