-- Registers recurring mission template infrastructure (master brief
-- Section 15, Continuous Operations). Applied live via Supabase MCP on
-- 2026-09-07; this file makes it reproducible from a fresh database.

insert into public.capability_registry (
  capability_key, name, description, category, department,
  agent_tool_name, read_write, tenant_scope, cost_profile, risk, verification_method,
  status, status_notes, last_verified_at, last_verified_by
) values (
  'capability:recurring_mission_templates',
  'Real recurring mission infrastructure -- master brief Section 15 (Continuous Operations)',
  'Real, reusable "run this mission on a schedule" infrastructure. New recurring_mission_templates table (tenant_id, label, goal_text, cadence in daily/weekly/monthly, enabled, next_fire_at, last_fired_at, last_mission_id) and packages/missions/src/recurring.ts -- a real cadence engine (computeNextFireAt skips missed periods instead of bursting a backlog, isTemplateDue) and processRecurringTemplates, which reuses the EXISTING, already-tested createAndEstimateMission (packages/missions/src/repository.ts) unmodified for actual mission instantiation -- never a duplicate creation path. A real, stable idempotency key (buildRecurringIdempotencyKey, one per template per real cadence period) is passed straight into createAndEstimateMission''s own existing dedup guard, so two overlapping processor runs (a cron retry racing a manual trigger) can never create two missions for the same template''s same period. Hosted on the EXISTING app/api/internal/search/scheduler cron route (master brief Section 15''s own explicit instruction: "do not create unnecessary cron infrastructure if existing scheduled execution can safely handle it") -- this codebase''s own established precedent for exactly this (see that route''s own Review Bot, hosted there for the identical reason: this Vercel project is on the Hobby plan). Confirmed via the existing review-bot-wiring.test.ts (which asserts vercel.json''s cron count) that this change added ZERO new cron entries. Four real chat tools (create_recurring_mission_template, list_recurring_mission_templates, set_recurring_mission_template_enabled, run_recurring_mission_templates_now) let a Founder set one up via WhatsApp/Admin Copilot, gated by new agent:read:recurring_missions / agent:mutate:recurring_missions permissions (mutate is platform_owner-only). A genuine safety decision, stated honestly: createAndEstimateMission''s own documented behavior reserves REAL WALLET FUNDS once a mission reaches READY -- a real financial commitment. So while the full mechanism is real, tested, and shippable today, AUTOMATIC unattended firing from the cron is gated behind a new RECURRING_MISSIONS_ENABLED env var (off by default, same fail-safe opt-in pattern as OPENROUTER_ENABLED/LOCAL_AI_ENABLED) -- a Founder activation decision, not a routine engineering default, matching this session''s own established precedent for HERMES_MODE. run_recurring_mission_templates_now always works regardless of the flag, since an explicit human request IS the authorization.',
  'missions',
  'Engineering',
  'create_recurring_mission_template, list_recurring_mission_templates, set_recurring_mission_template_enabled, run_recurring_mission_templates_now',
  'read_write',
  'tenant',
  'free',
  'external_mutation',
  '12 new test scenarios across 2 files: packages/missions/src/__tests__/recurring.test.ts (7 scenarios -- computeNextFireAt''s real cadence math for daily/weekly/monthly using realistic non-boundary inputs, its missed-period-skipping behavior, isTemplateDue''s enabled+schedule gating, buildRecurringIdempotencyKey''s real stability-within-a-period and distinctness-across-periods/templates, isRecurringMissionsEnabled''s fail-safe default, and processRecurringTemplates'' wiring confirmed via source inspection to reuse the real createAndEstimateMission with a real idempotency key and isolate per-template failures -- matching this codebase''s own established precedent, lib/owner-brain/__tests__/hermes-mission-integration.test.ts, that createAndEstimateMission''s full pipeline is only ever tested against a real live database, never mocked) and lib/agent-core/__tests__/recurring-mission-tools.test.ts (5 scenarios -- field validation, interpretOutcome, permission requirements, refusing to query without a real tenantId). Fixed a real, pre-existing, unrelated staleness bug found while verifying the cron-count invariant: app/api/internal/search/scheduler/__tests__/review-bot-wiring.test.ts asserted an exact vercel.json cron count of 9 that had already gone stale to 10 (an unrelated legitimate addition from 2026-09-06); corrected to 10 with an explanatory comment, confirmed via git log this predates and is unrelated to today''s work. Zero regressions across test:foundation (69 files), test:agent-core-lib (11 files), test:agent-core (17 files), and the full 14-file test:search-growth suite. Full-repo tsc --noEmit clean, lint clean, real NODE_ENV=production build (exit 0).',
  'REAL_EXPOSED',
  'Automatic unattended firing is deliberately OFF by default (RECURRING_MISSIONS_ENABLED unset) -- a genuine financial-commitment activation decision for the Founder, not silently defaulted on. The monthly cadence uses a fixed 30-day period rather than real calendar-month arithmetic, a deliberate v1 simplification stated honestly (no DST/month-length edge cases to get subtly wrong). Does not yet support per-template budget caps beyond the tenant''s own existing wallet/plan limits (createAndEstimateMission''s own real AWAITING_FUNDS parking already applies) -- a real, separate future refinement if usage reveals a need for it.',
  now(),
  'claude_session_2026-09-07'
);
