-- Records a real Growth Opportunities card added to Admin Home (master
-- brief section 17), using the same diagnosis pipeline
-- check_business_priorities uses. Applied live via Supabase MCP on
-- 2026-09-02; this file makes that reproducible from a fresh database.
insert into public.capability_registry
  (capability_key, name, description, category, skill, agent_tool_name, package_or_module, department, connection, required_permission, read_write, tenant_scope, cost_profile, risk, verification_method, status, status_notes, external_blocker, last_verified_at, last_verified_by)
values
  ('capability:admin_home_growth_opportunities_card', 'Admin Home now shows a real, evidence-gated Growth Opportunities card for the active tenant -- the same diagnosis pipeline check_business_priorities uses', 'Master brief section 17 ("what opportunities exist / what should happen next"). app/admin/(shell)/page.tsx now calls the exact same real functions Update 38''s check_business_priorities tool uses (computeRealBusinessSignals, computeRealEntitlementSnapshot, getCurrentBrandBrain, loadIntegrationsStatusData, diagnoseBusinessGrowth, deriveBottlenecks) directly, rendering the top 3 real, evidence-backed bottlenecks with real severity chips -- never a decorative or hardcoded card. Degrades honestly: a real computation failure shows "couldn''t compute a diagnosis right now" rather than breaking the page or fabricating content; zero bottlenecks (a tenant with too little real signal data) shows an honest "no evidence-backed bottleneck found yet" message, not an empty silent gap.', 'ecosystem', null, null, 'app/admin/(shell)/page.tsx', 'Engineering', null, null, 'read', 'tenant', 'free', 'read', 'Full-repo tsc --noEmit clean, lint clean, real NODE_ENV=production next build exit 0.', 'REAL_EXPOSED', 'One real, concrete slice of the Admin Home rebuild (section 17). The rest of that page (Missions/Approvals/Integration cards) was already real from before this session; this adds the one card that was previously entirely missing.', null, now(), 'claude_session_2026-09-02')
on conflict (capability_key) do nothing;
