-- Records the real BusinessSignals -> diagnoseBusinessGrowth ->
-- deriveBottlenecks pipeline, exposed as check_business_priorities, plus the
-- follow-up note on capability:business_growth_planner_pipeline reflecting
-- that its diagnosis half is now real progress (the full plan-generation
-- half remains open). Applied live via Supabase MCP on 2026-09-02; this file
-- makes that reproducible from a fresh database.
insert into public.capability_registry
  (capability_key, name, description, category, skill, agent_tool_name, package_or_module, department, connection, required_permission, read_write, tenant_scope, cost_profile, risk, verification_method, status, status_notes, external_blocker, last_verified_at, last_verified_by)
values
  ('capability:business_priorities_pipeline', 'Real BusinessSignals -> diagnoseBusinessGrowth -> deriveBottlenecks pipeline, exposed as check_business_priorities', 'Wires the previously-unexposed diagnoseBusinessGrowth/deriveBottlenecks pipeline (packages/workforce-core/src/planning/diagnosis.ts) to real inputs for the first time: real BusinessSignals (computeRealBusinessSignals), a real BusinessGrowthEntitlementSnapshot built live from subscriptions/usage_entitlements/audit_orders (lib/agent-core/business-priorities.ts -- allocationPolicy honestly UNKNOWN, no per-tenant contract composition policy exists in this schema), the real current Brand Brain (getCurrentBrandBrain, @stratxcel/brand-brain), and real connection state (loadIntegrationsStatusData, the same engine check_connections already uses). Exposed as a new read-only agent tool, check_business_priorities (lib/agent-core/business-priorities-tool.ts), answering "what is the most important thing to do next" from a prioritized, evidence-gated bottleneck list -- never a prompt-only guess. Fields diagnoseBusinessGrowth/deriveBottlenecks never read (productsServices beyond brand brain services, businessGoals, previousPerformance, activeCampaigns, availableCapabilities, budgetEnvelope, missionId, timezone) are filled with honest, clearly-inert placeholders (empty arrays, a synthetic non-persisted missionId, a zeroed MissionBudgetEnvelope) that cannot influence the diagnosis -- confirmed by reading the two functions'' source directly before writing this. Deliberately does not call the heavier planBusinessGrowth (thirty-day-planner.ts), which needs proposedStages/proposedWeeklyStrategy this read-only diagnostic tool has no business generating.', 'ecosystem', null, 'check_business_priorities', 'lib/agent-core/business-priorities.ts, lib/agent-core/business-priorities-tool.ts', 'Engineering', null, 'agent:read:research', 'read', 'tenant', 'free', 'read', 'business-priorities.test.ts (new, 4 real assertions incl. active-vs-cancelled-subscription selection and incomplete-audit-order exclusion), full-repo tsc --noEmit clean, lint clean, real NODE_ENV=production next build exit 0', 'REAL_EXPOSED', 'diagnoseBusinessGrowth and deriveBottlenecks are now genuinely reachable via WhatsApp/Admin/Client Copilot with real evidence-backed inputs. The heavier planBusinessGrowth/reviseThirtyDayPlan (full 30-day plan generation, weekly strategy, workforce staging) remains REAL_NOT_EXPOSED -- a separate, larger integration that belongs with a real mission-creation flow, not this read-only diagnostic.', null, now(), 'claude_session_2026-09-02')
on conflict (capability_key) do nothing;

update public.capability_registry
set status_notes = status_notes || ' UPDATE (same day, next pass): the diagnoseBusinessGrowth/deriveBottlenecks half of this pipeline is now genuinely wired to real inputs and exposed as check_business_priorities -- see capability:business_priorities_pipeline. Still open and still REAL_NOT_EXPOSED: planBusinessGrowth/reviseThirtyDayPlan themselves (full 30-day plan generation, weekly strategy, workforce staging, proposedStages) -- these need a real mission-creation flow this diagnostic tool intentionally does not provide.',
    last_verified_at = now(),
    last_verified_by = 'claude_session_2026-09-02'
where capability_key = 'capability:business_growth_planner_pipeline';
