-- Records the first real production caller of planBusinessGrowth (the full
-- 30-day plan engine), exposed as preview_growth_plan -- master brief
-- sections 4/15 -- plus reclassifying capability:business_growth_planner_pipeline
-- to REAL_EXPOSED now that it's genuinely reachable. Applied live via
-- Supabase MCP on 2026-09-02; this file makes that reproducible from a
-- fresh database.
insert into public.capability_registry
  (capability_key, name, description, category, skill, agent_tool_name, package_or_module, department, connection, required_permission, read_write, tenant_scope, cost_profile, risk, verification_method, status, status_notes, external_blocker, last_verified_at, last_verified_by)
values
  ('capability:preview_growth_plan_tool', 'preview_growth_plan: the first real production caller of planBusinessGrowth (the full 30-day plan engine) -- weekly strategy, staged work items, customer-facing summary, all real', 'Master brief sections 4/15 (Priority Engine full pipeline; Learning''s upstream dependency). Re-investigated the earlier assumption (recorded in Update 38 and the Final Completion Matrix) that planBusinessGrowth "needs" caller-supplied proposedStages/proposedWeeklyStrategy to avoid fabrication -- read buildWorkflowStages (packages/workforce-core/src/planning/workflows.ts) directly and confirmed proposedStages is genuinely optional: when absent, the function falls through to its own real default stage generation keyed by workflowFocus. There was no field forcing fabrication after all -- the earlier caution was itself over-cautious, corrected here after actually reading the source. New lib/agent-core/business-growth-input.ts (assembleBusinessGrowthPlannerInput) extracts the real input-assembly logic shared with check_business_priorities so both call one implementation. preview_growth_plan (lib/agent-core/growth-plan-tool.ts) calls planBusinessGrowth with zero fabricated business logic input -- entirely real signals/entitlements/Brand Brain/connections. Deliberately a PREVIEW only: nothing is persisted to workforce_plans, no mission is linked or created -- committing a plan for real still requires an explicit create_mission call and remains a separate, larger, honestly-open capability (the full persisted-plan + revision + learning-loop cycle).', 'ecosystem', null, 'preview_growth_plan', 'lib/agent-core/growth-plan-tool.ts, business-growth-input.ts', 'Engineering', null, 'agent:read:research', 'read', 'tenant', 'free', 'read', 'Full-repo tsc --noEmit clean, lint clean, test:agent-core-lib and test:workforce-core (19 files incl. business-growth.test.ts, planner.test.ts) pass unchanged, real NODE_ENV=production next build exit 0.', 'REAL_EXPOSED', 'planBusinessGrowth is now genuinely reachable via WhatsApp/Admin/Client Copilot as a real preview capability. Persisting a plan for real, linking it to a mission, and the learning loop revising it remain the honestly-open next layer.', null, now(), 'claude_session_2026-09-02')
on conflict (capability_key) do nothing;

update public.capability_registry
set status = 'REAL_EXPOSED',
    status_notes = status_notes || ' UPDATE 2026-09-02 (later pass, same day): FIXED, and the earlier caution here was itself corrected. planBusinessGrowth is now genuinely reachable -- see capability:preview_growth_plan_tool. The earlier assumption (recorded here and in Update 38) that proposedStages/proposedWeeklyStrategy would need fabricating was wrong: buildWorkflowStages has real default generation when they are absent, confirmed by reading the source directly this pass rather than re-assuming the earlier note. Still honestly open: persisting a generated plan to workforce_plans, linking it to a real mission, and the learning loop revising a real persisted plan -- preview_growth_plan deliberately never does any of that.',
    last_verified_at = now(),
    last_verified_by = 'claude_session_2026-09-02'
where capability_key = 'capability:business_growth_planner_pipeline';
