-- Additive capability_registry rows documenting two more real-but-unbridged
-- engines found while tracing packages/workforce-core for Update 17 --
-- honest bookkeeping, not new capability. Applied live via Supabase MCP on
-- 2026-09-02; this file makes that reproducible from a fresh database.
insert into public.capability_registry
  (capability_key, name, description, category, skill, agent_tool_name, package_or_module, department, connection, required_permission, read_write, tenant_scope, cost_profile, risk, verification_method, status, status_notes, external_blocker, last_verified_at, last_verified_by)
values
  ('engine:learning_loop', 'Performance learning-loop revision engine', 'Real, typed functions (applyLearningRevision, recommendationToLearningEvent, observationToMeasuredSignal) that turn measured performance signals into recorded learning events and department/role revisions.', 'ecosystem', null, null, 'packages/workforce-core/src/performance/learning-loop.ts', 'Engineering', null, null, 'read', 'platform_only', 'free', 'read', 'none (not yet bridged)', 'REAL_NOT_EXPOSED', 'Same shape as engine:revenue_ops: a pure computation library that takes already-gathered performance data as input and returns a derived result -- it owns no table of its own. Bridging it as an agent tool would mean inventing new orchestration logic to gather real inputs, which breaks the "zero new business logic" discipline every other bridge in this session followed. Real foundation for a future Learning capability, not itself one yet.', null, now(), 'claude_session_2026-09-02'),
  ('engine:priority_recommendations', 'Growth/plan recommendation engine', 'Real, typed functions (buildGrowthRecommendations, buildPlanRecommendations) that derive prioritized recommendations from supplied growth/performance context.', 'ecosystem', null, null, 'packages/workforce-core/src/planning/recommendations.ts', 'Engineering', null, null, 'read', 'platform_only', 'free', 'read', 'none (not yet bridged)', 'REAL_NOT_EXPOSED', 'Same shape as engine:revenue_ops and engine:learning_loop: pure computation over caller-supplied input, owns no table of its own. Real foundation for a future Priority Engine capability, not itself independently bridgeable without new orchestration logic.', null, now(), 'claude_session_2026-09-02');
