-- Records a fixed fully non-functional "Search ⌘K" button in the shared
-- top command bar (master brief section 20). Applied live via Supabase
-- MCP on 2026-09-02; this file makes that reproducible from a fresh
-- database.
insert into public.capability_registry
  (capability_key, name, description, category, skill, agent_tool_name, package_or_module, department, connection, required_permission, read_write, tenant_scope, cost_profile, risk, verification_method, status, status_notes, external_blocker, last_verified_at, last_verified_by)
values
  ('capability:admin_search_pill_fixed', 'Fixed a fully non-functional "Search ⌘K" button in the shared top command bar -- it had no onClick and no keyboard listener at all', 'Master brief section 20 ("no hardcoded fake actions") and section 15 ("remove fake/empty metrics"). components/shell/TopCommandBar.tsx (shared by /admin and /app, though this pill only ever renders for /admin -- showSearch={product !== "App"}) rendered a plain <button>Search ⌘K</button> with zero onClick handler and no keyboard listener -- a visible, prominent, always-present control on every admin page that did literally nothing when clicked or when Cmd/Ctrl+K was pressed, despite visually promising both. New components/shell/SearchCommandPill.tsx (a small "use client" island, keeping TopCommandBar itself a Server Component) makes it genuinely real: clicking it, or pressing Cmd/Ctrl+K anywhere outside a text input, navigates to /admin/copilot -- the real Admin Copilot chat already wired to every real agent tool this session built (check_business_priorities, check_google_business, check_revenue_diagnostics, edit_website, etc.), rather than building a second, separate, fake command palette that would just duplicate what Copilot already does for real. TopCommandBar gained a searchHref prop (default "/admin/copilot") rather than a hardcoded path, so a future customer-facing use of this pill is not silently wrong.', 'ecosystem', null, null, 'components/shell/TopCommandBar.tsx, components/shell/SearchCommandPill.tsx', 'Engineering', null, null, 'read', 'platform_only', 'free', 'read', 'Full-repo tsc --noEmit clean, lint clean, real NODE_ENV=production next build exit 0. No test previously referenced the old dead SearchPill (confirmed via grep) so none needed updating.', 'REAL_EXPOSED', 'This is itself the fix. Directly satisfies the master brief''s Admin Command/Query requirement (section 20) by pointing at the real, already-built command/query interface (Admin Copilot) rather than requiring a separate new command-palette UI to be built from scratch.', null, now(), 'claude_session_2026-09-02')
on conflict (capability_key) do nothing;
