-- Records a real security hardening finding + fix: PreviewManager's
-- hardcoded fallback HMAC secret removed before anything wires it up.
-- Applied live via Supabase MCP on 2026-09-02; this file makes that
-- reproducible from a fresh database.
insert into public.capability_registry
  (capability_key, name, description, category, skill, agent_tool_name, package_or_module, department, connection, required_permission, read_write, tenant_scope, cost_profile, risk, verification_method, status, status_notes, external_blocker, last_verified_at, last_verified_by)
values
  ('capability:preview_manager_hardcoded_secret_fixed', 'Preview URL HMAC signing: hardcoded fallback secret removed (real security hardening)', 'While investigating a signed-URL mechanism to bridge the paid-audit PDF report, found PreviewManager (packages/websites-and-domains/src/preview/preview-manager.ts) fell back to a hardcoded, source-visible constant secret ("stratxcel_preview_hmac_secret_2026") whenever PREVIEW_SECRET_KEY was not configured -- a real anti-pattern per the master build brief''s own rule 3 ("do not expose secret values in code"). Traced every real app/ route before concluding severity: confirmed zero live routes currently call this class (only its own smoke-test and unit test do) -- the real, live preview page (app/app/website/[siteId]/preview) uses genuine Supabase session auth instead, unaffected. Not an active exploit, but a real risk if this class were ever wired to a live route without someone remembering to set the real secret. Fixed proactively, before that happens -- mirrors config/production-gate.ts''s own established fail-closed pattern exactly (hard throw in production if genuinely unconfigured; a real, unpredictable, non-constant random secret in every other environment, so tests keep working without a real secret configured).', 'ecosystem', null, null, 'packages/websites-and-domains/src/preview/preview-manager.ts', 'Engineering', null, null, 'read', 'platform_only', 'free', 'read', 'preview-secret-fail-closed.test.ts (new, 5 assertions), full test:website-factory suite (23 files) exit 0, full-repo tsc --noEmit clean, lint clean', 'REAL_EXPOSED', 'This finding and fix are themselves the capability -- the underlying PreviewManager class remains genuinely unused by any live route (a separate, correctly-classified REAL_NOT_EXPOSED concern, not fabricated as bridged here).', null, now(), 'claude_session_2026-09-02')
on conflict (capability_key) do nothing;
