-- Records a section-6 capability audit finding: packages/providers is a
-- real, substantial (~2,556 line) provider-abstraction package with zero
-- real callers anywhere in the monorepo, distinct from workforce-core's own
-- separate providers/ implementation. Applied live via Supabase MCP on
-- 2026-09-02; this file makes that reproducible from a fresh database.
insert into public.capability_registry
  (capability_key, name, description, category, skill, agent_tool_name, package_or_module, department, connection, required_permission, read_write, tenant_scope, cost_profile, risk, verification_method, status, status_notes, external_blocker, last_verified_at, last_verified_by)
values
  ('capability:providers_package_unused', '@stratxcel/providers -- a real, substantial (~2,556 line) provider-abstraction package with zero real callers anywhere in the monorepo', 'Section 6 capability audit (master brief): packages/providers defines real interfaces + production adapters + resilience/retry/health/config for AI, images, research, email, payments, domains, and DNS providers. Confirmed by exhaustive grep across app/, lib/, and every other package (not just app/lib -- re-checked cross-package too) for both `from "@stratxcel/providers"` and `from "@stratxcel/providers/..."`: zero real callers anywhere outside packages/providers/src/__tests__ itself. Not the same as packages/workforce-core/src/providers/ (registry.ts/failover.ts/bootstrap.ts/image-generation.ts) -- confirmed workforce-core does NOT import @stratxcel/providers at all; the two are separate, non-overlapping provider abstractions, and workforce-core''s own is the one actually wired into real capability execution. This finding does not claim packages/providers is broken or wrong -- only that it is real, substantial, tested code with no live production caller, previously unrecorded in this registry.', 'ecosystem', null, null, 'packages/providers/src', 'Engineering', null, null, 'read', 'global', 'free', 'read', 'Exhaustive repo-wide grep for `@stratxcel/providers` imports across app/, lib/, and every package/*/src (excluding packages/providers itself and __tests__ directories): zero matches.', 'REAL_NOT_EXPOSED', 'A real, substantial, previously-unaudited package with no live caller. Worth a deliberate decision (wire it in somewhere real, or formally deprecate/remove it) rather than leaving it silently unused indefinitely -- not fixed in this pass, honestly recorded instead.', null, now(), 'claude_session_2026-09-02')
on conflict (capability_key) do nothing;
