-- Records get_paid_audit_report_link (the real bridge closing
-- capability:paid_audit_pdf_report from Update 21) plus three real findings
-- from tracing engine:audit_engine end to end: the paid audit_orders
-- generation pipeline is real and already live via a Vercel Cron + Postgres
-- queue (correcting a false "packages/audit-engine writes public_audit_
-- requests" claim carried since Update 15/40); the free/prospect Audit
-- product has NO automated generation pipeline at all (real, honest
-- NOT_BUILT); and every Vercel Cron in this project -- not just the audit
-- worker -- is capped at once-daily by the account's Hobby plan tier, a real
-- external/billing blocker, not an engineering gap. Applied live via
-- Supabase MCP on 2026-09-02; this file makes it reproducible from a fresh
-- database.

insert into public.capability_registry
  (capability_key, name, description, category, skill, agent_tool_name, package_or_module, department, connection, required_permission, read_write, tenant_scope, cost_profile, risk, verification_method, status, status_notes, external_blocker, last_verified_at, last_verified_by)
values
  ('capability:audit_report_share_link_tool', 'get_paid_audit_report_link: real bridge to the paid Audit report share-link mechanism', 'Closes capability:paid_audit_pdf_report, precisely recorded in Update 21: the paid audit_orders product has a real, working, already-authenticated-dashboard-facing signed-URL sharing mechanism (lib/audit/v1/whatsapp-send.ts getOrCreateAuditShareUrl/createAuditShareUrl, backed by the real audit_share_tokens table -- token-hashed, 14-day expiry, revocable, view-counted -- and a real, already-built /audit/share/[token] page), but it was cookie-session-scoped only (app/api/platform/audit/report/share/route.ts), unreachable from a service-role WhatsApp/Admin agent call. This tool resolves the caller''s current completed Audit order the same way the authenticated route does (resolveCurrentAuditOrderId, with the same real fallback to the latest completed order) but scoped by a resolved tenantId instead of a cookie session, then calls the exact same getOrCreateAuditShareUrl the dashboard route calls -- one mechanism, two entry points, never two competing ones. Classified low_mutation (not read): the first call for a given order mints a real, durable 14-day bearer-token row, so it is confirm-gated over WhatsApp, correctly.', 'ecosystem', null, 'get_paid_audit_report_link', 'lib/agent-core/audit-report-link-tool.ts', 'Engineering', null, 'agent:mutate:audit_reports', 'read_write', 'tenant', 'free', 'low_mutation', 'Full-repo tsc --noEmit clean, lint clean, full test:agent-core-lib and test:agent-core suites pass unchanged (zero regressions), real NODE_ENV=production next build (exit 0), plus a real transactional dry-run insert against the live audit_share_tokens/audit_delivery_events tables (rolled back, zero permanent data) confirming the exact schema mapping createAuditShareUrl uses is correct.', 'REAL_EXPOSED', null, null, now(), 'claude_session_2026-09-02')
on conflict (capability_key) do nothing;

update public.capability_registry
set status = 'REAL_EXPOSED',
    status_notes = coalesce(status_notes, '') || ' RESOLVED 2026-09-02 (final convergence pass): capability:audit_report_share_link_tool (get_paid_audit_report_link) is the real bridge this row called for -- built, verified, and shipped.',
    last_verified_at = now(), last_verified_by = 'claude_session_2026-09-02'
where capability_key = 'capability:paid_audit_pdf_report';

update public.capability_registry
set status = 'REAL_EXPOSED',
    status_notes = 'CORRECTED 2026-09-02 (final convergence pass): the prior "ambiguous which of packages/audit-engine or lib/audit/v1 is canonical" framing was wrong -- they are not competing implementations of the same thing. packages/audit-engine''s runAutomaticAuditGeneration is the real, live-in-production generation pipeline for the PAID audit_orders/audit_generation_runs flow -- confirmed by reading createLiveAutomaticAuditExecutor (packages/audit-engine/src/live.ts) directly, which calls it; that executor is invoked by a real Vercel Cron (app/api/platform/audit/worker/route.ts, CRON_SECRET-authorized, registered in vercel.json, claiming AUDIT_GENERATION_JOB_TYPE jobs from a real Postgres queue). lib/audit/v1 is a separate, also-real downstream layer (WhatsApp delivery, PDF-report share links -- see capability:audit_report_share_link_tool) that operates on an already-completed order, not a second generation engine. Also corrects a real factual error carried in this doc since Update 15/40: packages/audit-engine does NOT write into public_audit_requests -- that claim was checked directly this pass (grep for every writer of public_audit_requests.job_status) and is false; see capability:prospect_audit_automated_pipeline for the real, distinct, honestly-unbuilt finding this exposed. "WhatsApp synthesizes an audit from analyze_website directly, bypassing this engine" (the original note) is correct behavior, not a gap: the chat agent should not silently create a billable audit_orders row from a casual question. A new, real, previously-undocumented finding from this pass: the actual generation-run pickup latency for a PAID Audit is bounded by the Vercel account''s plan tier, not by anything in this codebase -- see capability:vercel_cron_hobby_tier_daily_cap.',
    external_blocker = null,
    last_verified_at = now(), last_verified_by = 'claude_session_2026-09-02'
where capability_key = 'engine:audit_engine';

insert into public.capability_registry
  (capability_key, name, description, category, skill, agent_tool_name, package_or_module, department, connection, required_permission, read_write, tenant_scope, cost_profile, risk, verification_method, status, status_notes, external_blocker, last_verified_at, last_verified_by)
values
  ('capability:prospect_audit_automated_pipeline', 'Automated generation for the FREE/prospect Audit product (public_audit_requests) -- genuinely never built', 'Distinct from the paid audit_orders flow (engine:audit_engine, REAL_EXPOSED). public_audit_requests carries job_status/progress_percentage/report_data/evidence_data columns (added 2026-08-05, supabase/migrations/20260805160000_authenticated_audit_jobs.sql) that read as if a real automated pipeline populates them -- it does not. Verified directly: the only writer of these rows is app/api/public/audit-requests/route.ts (intake, sets job_status default "draft"/status "new" and nothing else, ever) and app/api/platform/audit-requests/route.ts (a staff PATCH endpoint that only advances a manual CRM-style status enum -- new/contacted/qualified/paid/audit_in_progress/completed/converted/rejected -- by hand). No code path anywhere calls packages/audit-engine or any other engine against a public_audit_requests row. The real, current process for a free/prospect Audit is entirely staff-worked by hand; check_audit_status (WhatsApp/Admin) can only read whatever a human has manually recorded, never a real automated job''s progress, because no such job exists. Not a fabrication risk in itself (the tool reads real, honest columns) but the columns'' own names invite the false impression of automation that was never built.', 'ecosystem', null, null, 'packages/audit-engine (not applicable to this table); app/api/public/audit-requests/route.ts; app/api/platform/audit-requests/route.ts', 'Engineering', null, null, 'read_write', 'tenant', 'free', 'read', 'Verified by direct grep for every writer of public_audit_requests across the repository (2 real writers found, both manual/static, zero automated ones) and by reading packages/audit-engine''s real table writes directly (audit_generation_runs/audit_orders/audit_discovery_snapshots -- never public_audit_requests).', 'NOT_BUILT', 'No automated generation pipeline exists for the free/prospect Audit product. Building one (a real free-tier equivalent of packages/audit-engine, budget-capped appropriately for a zero-revenue product) is a genuine, scoped, buildable next step -- not attempted this pass to keep this reconciliation pass honest about what it actually verified versus what it built.', null, now(), 'claude_session_2026-09-02')
on conflict (capability_key) do nothing;

insert into public.capability_registry
  (capability_key, name, description, category, skill, agent_tool_name, package_or_module, department, connection, required_permission, read_write, tenant_scope, cost_profile, risk, verification_method, status, status_notes, external_blocker, last_verified_at, last_verified_by)
values
  ('capability:vercel_cron_hobby_tier_daily_cap', 'Every Vercel Cron in this project (including the paid Audit generation worker) is capped at once-daily by the Hobby plan tier', 'Real, previously-undocumented, platform-wide finding. app/api/platform/audit/worker/route.ts''s own header comment and apps/mission-worker/src/worker.ts''s 2026-08-19 finding both describe an intended "every 5 min" (*/5 * * * *) cron cadence for AUDIT_GENERATION_JOB_TYPE pickup. The actual live vercel.json registers it as "0 8 * * *" -- once daily -- and confirmed via the Vercel MCP (list_teams) that the linked team (jack160699''s projects) is on plan "hobby". Vercel''s Hobby tier caps Cron Jobs at once-per-day, full stop; every other cron in this same vercel.json (social/package-producer, social/worker, subscriptions/renew, operating-brain/worker, operating-brain cron/*, search/scheduler) is ALSO once-daily, confirming this is a platform-tier ceiling affecting the whole app, not a regression specific to the audit worker. Practical effect: a customer who completes payment for a paid Audit can wait up to ~24h worst-case before generation is even picked up (the job is enqueued instantly at checkout via start_automatic_audit_generation_v1, but nothing claims it until the next daily cron tick). Not fixable in-session: raising cron frequency requires upgrading the Vercel team to a paid (Pro+) plan, a real billing decision for the account owner, not an engineering task -- and editing vercel.json to a sub-daily schedule against a Hobby-tier team would not "fix" anything (Vercel enforces the cap server-side).', 'ecosystem', null, null, 'vercel.json', 'Engineering', 'vercel', null, 'read', 'platform_only', 'free', 'read', 'Confirmed live via Vercel MCP list_teams (plan: "hobby") cross-referenced against the actual deployed vercel.json crons array (every entry in the file is a once-daily schedule) and against two independent pieces of code documentation (audit worker route header, mission-worker.ts 2026-08-19 comment) that both assumed a 5-minute cadence.', 'EXTERNAL_REQUIRED', null, 'vercel_pro_plan_upgrade_required_for_sub_daily_cron', now(), 'claude_session_2026-09-02')
on conflict (capability_key) do nothing;
