-- Records a real fix + a real, honestly-recorded open gap found while
-- sweeping the customer Growth dashboard for the same "unconditional
-- success" pattern just fixed in the website editor (Updates 29-32).
-- Applied live via Supabase MCP on 2026-09-02; this file makes that
-- reproducible from a fresh database.
insert into public.capability_registry
  (capability_key, name, description, category, skill, agent_tool_name, package_or_module, department, connection, required_permission, read_write, tenant_scope, cost_profile, risk, verification_method, status, status_notes, external_blocker, last_verified_at, last_verified_by)
values
  ('capability:growth_page_mission_outcome_labeling', 'Growth dashboard mission outcome labeling (fixed) + What Needs Attention gap (open)', 'Swept app/app/growth/page.tsx (the customer Growth dashboard) for the same "unconditional success" pattern just fixed in the website editor. Found and fixed: PARTIALLY_COMPLETED missions (some sub-tasks did not finish) were labeled an unqualified "Completed successfully" in the "What Improved" card, identical wording to a genuinely COMPLETED mission. Fixed by reusing the existing MISSION_STATE_CHIP label ("Partially completed") already used correctly on the Missions page, plus an explicit "some parts may need review" note -- real, minimal, reuses existing wording rather than inventing new copy.', 'ecosystem', null, null, 'app/app/growth/page.tsx', 'Engineering', null, null, 'read', 'tenant', 'free', 'read', 'lib/rbac/__tests__/customer-app-bugfixes-polish.test.ts (2 new source-text assertions), tsc --noEmit clean, lint clean', 'PARTIAL', 'Larger, NOT fixed this pass: the "What Needs Attention" card next to it is entirely generic/hardcoded copy (a fixed Google Business Profile tip, a fixed content-scheduling tip, and a real approvalsCount badge) -- it is not driven by real per-mission FAILED/BLOCKED/AWAITING_FUNDS/PARTIALLY_COMPLETED data at all, so a customer with a genuinely failed or stalled mission sees no mission-specific callout anywhere on this page. A real fix needs actual per-mission failure summaries, judged out of scope for a same-pass follow-up sweep rather than rushed here.', null, now(), 'claude_session_2026-09-02')
on conflict (capability_key) do nothing;
