-- ==============================================================================
-- Migration: 20260814210000_safe_customer_tenant_deletion_rpc.sql
-- Description: DEFINITIVE atomic privileged customer tenant deletion.
-- This version is reverse-engineered from the LIVE production schema.
-- DO NOT edit this file one-FK-at-a-time. All dependencies verified via:
--   SELECT * FROM information_schema.columns WHERE column_name = 'tenant_id'
--   + RESTRICT FK graph from information_schema.referential_constraints
-- ==============================================================================

-- ==============================================================================
-- 1. Update promo_redemptions_immutable trigger function
--    Respects both session-level allow flag and service_role DELETE bypass
-- ==============================================================================
CREATE OR REPLACE FUNCTION public.promo_redemptions_immutable()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
BEGIN
  -- Allow deletion when executing inside delete_customer_tenant_v1 or service_role
  IF current_setting('stratxcel.allow_tenant_deletion', true) = 'on'
     OR (auth.role() = 'service_role' AND TG_OP = 'DELETE') THEN
    RETURN OLD;
  END IF;
  RAISE EXCEPTION 'promo_redemptions are immutable';
END;
$$;

-- ==============================================================================
-- 2. Update prevent_completed_audit_rewrite trigger function
--    Allows service_role to nullify promo_redemption_id during customer deletion
-- ==============================================================================
CREATE OR REPLACE FUNCTION public.prevent_completed_audit_rewrite()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
BEGIN
  -- Allow all changes during tenant deletion transaction
  IF current_setting('stratxcel.allow_tenant_deletion', true) = 'on' THEN
    RETURN NEW;
  END IF;
  -- Allow service_role to nullify promo_redemption_id only
  IF auth.role() = 'service_role'
     AND NEW.promo_redemption_id IS NULL
     AND OLD.promo_redemption_id IS NOT NULL THEN
    RETURN NEW;
  END IF;

  IF OLD.audit_completed_at IS NOT NULL AND (
    NEW.completed_by IS DISTINCT FROM OLD.completed_by OR
    NEW.audit_completed_at IS DISTINCT FROM OLD.audit_completed_at OR
    NEW.delivered_at IS DISTINCT FROM OLD.delivered_at OR
    NEW.audit_fee_cents IS DISTINCT FROM OLD.audit_fee_cents OR
    NEW.credit_eligible_from IS DISTINCT FROM OLD.credit_eligible_from OR
    NEW.credit_expires_at IS DISTINCT FROM OLD.credit_expires_at OR
    NEW.fulfilment_source IS DISTINCT FROM OLD.fulfilment_source OR
    NEW.promo_redemption_id IS DISTINCT FROM OLD.promo_redemption_id OR
    NEW.actual_paid_cents IS DISTINCT FROM OLD.actual_paid_cents OR
    NEW.list_price_cents IS DISTINCT FROM OLD.list_price_cents OR
    NEW.discount_cents IS DISTINCT FROM OLD.discount_cents
  ) THEN
    RAISE EXCEPTION 'completed audit fields are immutable';
  END IF;

  IF OLD.fulfilment_source IS NOT NULL
     AND NEW.fulfilment_source IS DISTINCT FROM OLD.fulfilment_source THEN
    RAISE EXCEPTION 'audit fulfilment_source is immutable once set';
  END IF;
  IF OLD.promo_redemption_id IS NOT NULL
     AND NEW.promo_redemption_id IS DISTINCT FROM OLD.promo_redemption_id THEN
    RAISE EXCEPTION 'audit promo_redemption_id is immutable once set';
  END IF;

  RETURN NEW;
END;
$$;

-- ==============================================================================
-- 3. Ensure service_role has necessary permissions on audit/commercial tables
--    (verified against live production schema)
-- ==============================================================================
GRANT SELECT, INSERT, UPDATE, DELETE ON public.promo_redemptions TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.tenant_current_audits TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.audit_free_eligibility_events TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.audit_discovery_snapshots TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.audit_share_tokens TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.audit_delivery_events TO service_role;
-- audit_reset_snapshots has NO tenant_id — it's a platform archive, no deletion by tenant needed
GRANT SELECT, INSERT ON public.audit_reset_snapshots TO service_role;

-- ==============================================================================
-- 4. THE CANONICAL CUSTOMER TENANT DELETION FUNCTION
--    Built from the complete LIVE production schema:
--    - Tables with tenant_id: verified via information_schema
--    - RESTRICT FKs: verified via referential_constraints
--    - audit_reset_snapshots: confirmed NO tenant_id column
-- ==============================================================================
CREATE OR REPLACE FUNCTION public.delete_customer_tenant_v1(
  p_tenant_id UUID,
  p_actor TEXT DEFAULT 'admin'
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_tenant RECORD;
  v_is_platform_sender BOOLEAN := FALSE;
  v_order_ids UUID[];
BEGIN
  -- ============================================================
  -- GUARD 1: Tenant must exist
  -- ============================================================
  SELECT id, slug, name INTO v_tenant
  FROM public.tenants
  WHERE id = p_tenant_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'TENANT_NOT_FOUND: Tenant with ID % does not exist', p_tenant_id;
  END IF;

  -- ============================================================
  -- GUARD 2: Never delete platform/system tenants by slug
  -- ============================================================
  IF LOWER(v_tenant.slug) IN ('stratxcel', 'platform', 'staff-workspace', 'system') THEN
    RAISE EXCEPTION 'PROTECTED_TENANT: System workspace % (%) cannot be deleted', v_tenant.name, v_tenant.slug;
  END IF;

  -- ============================================================
  -- GUARD 3: Never delete the platform shared WhatsApp sender
  -- ============================================================
  SELECT EXISTS (
    SELECT 1 FROM public.whatsapp_phone_bindings
    WHERE tenant_id = p_tenant_id
      AND source = 'platform_shared_sender'
  ) INTO v_is_platform_sender;

  IF v_is_platform_sender THEN
    RAISE EXCEPTION 'PROTECTED_TENANT_WHATSAPP_SENDER: Tenant % is the platform shared WhatsApp sender', v_tenant.name;
  END IF;

  -- ============================================================
  -- Enable transaction-local bypass for immutable triggers
  -- ============================================================
  PERFORM set_config('stratxcel.allow_tenant_deletion', 'on', true);

  -- ============================================================
  -- Gather all audit order IDs for this tenant
  -- ============================================================
  SELECT COALESCE(ARRAY_AGG(id), '{}'::UUID[]) INTO v_order_ids
  FROM public.audit_orders
  WHERE tenant_id = p_tenant_id;

  -- ============================================================
  -- STEP 1: Neutralize tenant_current_audits FIRST
  --   FK: tenant_current_audits.current_audit_order_id → audit_orders(id) RESTRICT
  --   FK: tenant_current_audits.previous_audit_order_id → audit_orders(id) RESTRICT
  --   FK: tenant_current_audits.tenant_id → tenants(id) RESTRICT
  --   Must be done BEFORE deleting audit_orders
  -- ============================================================
  DELETE FROM public.tenant_current_audits WHERE tenant_id = p_tenant_id;

  -- ============================================================
  -- STEP 2: Delete audit_free_eligibility_events by BOTH tenant_id and audit_order_id
  --   FK: audit_free_eligibility_events.audit_order_id → audit_orders(id) RESTRICT
  --   FK: audit_free_eligibility_events.tenant_id → tenants(id) RESTRICT
  -- ============================================================
  DELETE FROM public.audit_free_eligibility_events WHERE tenant_id = p_tenant_id;
  IF CARDINALITY(v_order_ids) > 0 THEN
    DELETE FROM public.audit_free_eligibility_events WHERE audit_order_id = ANY(v_order_ids);
  END IF;

  -- ============================================================
  -- STEP 3: Delete audit_delivery_events by BOTH tenant_id and audit_order_id
  --   FK: audit_delivery_events.audit_order_id → audit_orders(id) RESTRICT
  --   FK: audit_delivery_events.tenant_id → tenants(id) RESTRICT
  -- ============================================================
  DELETE FROM public.audit_delivery_events WHERE tenant_id = p_tenant_id;
  IF CARDINALITY(v_order_ids) > 0 THEN
    DELETE FROM public.audit_delivery_events WHERE audit_order_id = ANY(v_order_ids);
  END IF;

  -- ============================================================
  -- STEP 4: Delete audit_discovery_snapshots
  --   FK: audit_discovery_snapshots.audit_order_id → audit_orders(id) RESTRICT
  --   FK: audit_discovery_snapshots.tenant_id → tenants(id) RESTRICT
  -- ============================================================
  DELETE FROM public.audit_discovery_snapshots WHERE tenant_id = p_tenant_id;
  IF CARDINALITY(v_order_ids) > 0 THEN
    DELETE FROM public.audit_discovery_snapshots WHERE audit_order_id = ANY(v_order_ids);
  END IF;

  -- ============================================================
  -- STEP 5: Delete audit_generation_runs
  --   FK: audit_generation_runs.audit_order_id → audit_orders(id) RESTRICT
  --   FK: audit_generation_runs.tenant_id → tenants(id) RESTRICT
  -- ============================================================
  IF CARDINALITY(v_order_ids) > 0 THEN
    DELETE FROM public.audit_generation_runs WHERE audit_order_id = ANY(v_order_ids);
  END IF;
  DELETE FROM public.audit_generation_runs WHERE tenant_id = p_tenant_id;

  -- ============================================================
  -- STEP 6: Delete audit_share_tokens
  --   FK: audit_share_tokens.audit_order_id → audit_orders(id) RESTRICT
  --   FK: audit_share_tokens.tenant_id → tenants(id) RESTRICT
  -- ============================================================
  DELETE FROM public.audit_share_tokens WHERE tenant_id = p_tenant_id;
  IF CARDINALITY(v_order_ids) > 0 THEN
    DELETE FROM public.audit_share_tokens WHERE audit_order_id = ANY(v_order_ids);
  END IF;

  -- ============================================================
  -- STEP 7: Delete promo_redemptions
  --   FK: promo_redemptions.audit_order_id → audit_orders(id) RESTRICT
  --   FK: promo_redemptions.tenant_id → tenants(id) RESTRICT
  --   FK: audit_orders.promo_redemption_id → promo_redemptions(id) (mutual!)
  --   Must nullify the mutual FK first, then delete
  -- ============================================================
  -- 7a. Break the mutual FK reference audit_orders → promo_redemptions
  UPDATE public.audit_orders
    SET promo_redemption_id = NULL
    WHERE tenant_id = p_tenant_id;
  -- 7b. Delete promo_redemptions (both by tenant and by order)
  DELETE FROM public.promo_redemptions WHERE tenant_id = p_tenant_id;
  IF CARDINALITY(v_order_ids) > 0 THEN
    DELETE FROM public.promo_redemptions WHERE audit_order_id = ANY(v_order_ids);
  END IF;

  -- ============================================================
  -- STEP 8: Delete audit_whatsapp_destinations
  --   (has tenant_id, confirmed in live schema)
  -- ============================================================
  DELETE FROM public.audit_whatsapp_destinations WHERE tenant_id = p_tenant_id;

  -- ============================================================
  -- STEP 9: Delete public_audit_requests (has tenant_id, verified)
  -- ============================================================
  DELETE FROM public.public_audit_requests WHERE tenant_id = p_tenant_id;

  -- ============================================================
  -- STEP 10: Delete audit_orders (all dependents cleared above)
  -- ============================================================
  DELETE FROM public.audit_orders WHERE tenant_id = p_tenant_id;

  -- ============================================================
  -- STEP 11: Brand Brain
  -- ============================================================
  DELETE FROM public.brand_brain_versions WHERE tenant_id = p_tenant_id;
  DELETE FROM public.brand_brains WHERE tenant_id = p_tenant_id;
  -- brand_assets: may not have tenant_id (not in live schema list) — skip safely

  -- ============================================================
  -- STEP 12: Image Generation
  --   NOTE: image_generation_candidates and image_generation_references
  --   have tenant_id; verify dependency order
  -- ============================================================
  DELETE FROM public.image_generation_candidates WHERE tenant_id = p_tenant_id;
  DELETE FROM public.image_generation_references WHERE tenant_id = p_tenant_id;
  DELETE FROM public.image_generation_jobs WHERE tenant_id = p_tenant_id;

  -- ============================================================
  -- STEP 13: Social & Content
  --   verified live: social_autopilot_queue_items, social_autopilot_authorizations,
  --   social_media_assets, social_brand_profiles, social_accounts,
  --   social_whatsapp_inbound_messages, social_whatsapp_sessions
  --   NOT having tenant_id: social_tokens, social_campaigns,
  --   social_agent_actions, social_agent_run_events, social_agent_runs
  --   (these cascade via social_accounts or social_posts FKs if applicable)
  -- ============================================================
  DELETE FROM public.social_autopilot_queue_items WHERE tenant_id = p_tenant_id;
  DELETE FROM public.social_autopilot_authorizations WHERE tenant_id = p_tenant_id;
  DELETE FROM public.social_media_assets WHERE tenant_id = p_tenant_id;
  DELETE FROM public.social_brand_profiles WHERE tenant_id = p_tenant_id;
  DELETE FROM public.social_accounts WHERE tenant_id = p_tenant_id;
  DELETE FROM public.social_whatsapp_inbound_messages WHERE tenant_id = p_tenant_id;
  DELETE FROM public.social_whatsapp_sessions WHERE tenant_id = p_tenant_id;

  -- ============================================================
  -- STEP 14: Missions & Workforce & AI
  --   verified live: missions, workforce_plans, workforce_reviews, workforce_stages
  --   ai_execution_usage, ai_media_operations (both have tenant_id)
  --   mission_events, mission_artifacts: no tenant_id (cascade via missions)
  -- ============================================================
  DELETE FROM public.ai_execution_usage WHERE tenant_id = p_tenant_id;
  DELETE FROM public.ai_media_operations WHERE tenant_id = p_tenant_id;
  DELETE FROM public.missions WHERE tenant_id = p_tenant_id;
  DELETE FROM public.workforce_plans WHERE tenant_id = p_tenant_id;
  DELETE FROM public.workforce_reviews WHERE tenant_id = p_tenant_id;
  DELETE FROM public.workforce_stages WHERE tenant_id = p_tenant_id;

  -- ============================================================
  -- STEP 15: Human Handoffs
  -- ============================================================
  DELETE FROM public.human_handoffs WHERE tenant_id = p_tenant_id;

  -- ============================================================
  -- STEP 16: Search & Discovery
  -- ============================================================
  DELETE FROM public.search_actions WHERE tenant_id = p_tenant_id;
  DELETE FROM public.search_recommendations WHERE tenant_id = p_tenant_id;
  DELETE FROM public.search_opportunities WHERE tenant_id = p_tenant_id;
  DELETE FROM public.search_analysis_runs WHERE tenant_id = p_tenant_id;
  DELETE FROM public.search_projects WHERE tenant_id = p_tenant_id;
  DELETE FROM public.search_measurement_snapshots WHERE tenant_id = p_tenant_id;
  DELETE FROM public.search_google_connections WHERE tenant_id = p_tenant_id;
  -- oauth_states not confirmed to have tenant_id — skip

  -- ============================================================
  -- STEP 17: CRM & WhatsApp Customer Messaging
  -- ============================================================
  -- crm_messages not in live list — skip
  -- crm_conversations not in live list — skip
  DELETE FROM public.crm_appointments WHERE tenant_id = p_tenant_id;
  DELETE FROM public.crm_follow_ups WHERE tenant_id = p_tenant_id;
  DELETE FROM public.crm_leads WHERE tenant_id = p_tenant_id;
  DELETE FROM public.contact_consent WHERE tenant_id = p_tenant_id;
  DELETE FROM public.whatsapp_shadow_messages WHERE tenant_id = p_tenant_id;
  DELETE FROM public.whatsapp_shadow_events WHERE tenant_id = p_tenant_id;
  DELETE FROM public.whatsapp_phone_bindings
    WHERE tenant_id = p_tenant_id AND source != 'platform_shared_sender';
  DELETE FROM public.whatsapp_conversations WHERE tenant_id = p_tenant_id;
  DELETE FROM public.whatsapp_messages WHERE tenant_id = p_tenant_id;
  DELETE FROM public.whatsapp_migration_imports WHERE tenant_id = p_tenant_id;
  DELETE FROM public.whatsapp_parity_records WHERE tenant_id = p_tenant_id;
  DELETE FROM public.whatsapp_channel_pairing_codes WHERE tenant_id = p_tenant_id;
  DELETE FROM public.whatsapp_channel_principals WHERE tenant_id = p_tenant_id;
  -- whatsapp_templates: may be platform-level — delete only customer-owned ones
  DELETE FROM public.whatsapp_templates WHERE tenant_id = p_tenant_id;

  -- ============================================================
  -- STEP 18: Queue Jobs & Email Outbox
  -- ============================================================
  DELETE FROM public.queue_jobs WHERE tenant_id = p_tenant_id;
  DELETE FROM public.email_outbox WHERE tenant_id = p_tenant_id;

  -- ============================================================
  -- STEP 19: Subscriptions, Wallets & Payments
  -- ============================================================
  DELETE FROM public.payment_reconciliation_issues WHERE tenant_id = p_tenant_id;
  DELETE FROM public.payment_shadow_orders WHERE tenant_id = p_tenant_id;
  DELETE FROM public.payment_refunds WHERE tenant_id = p_tenant_id;
  DELETE FROM public.payment_orders WHERE tenant_id = p_tenant_id;
  DELETE FROM public.payment_links WHERE tenant_id = p_tenant_id;
  DELETE FROM public.invoices WHERE tenant_id = p_tenant_id;
  DELETE FROM public.credit_notes WHERE tenant_id = p_tenant_id;
  DELETE FROM public.continuation_packs WHERE tenant_id = p_tenant_id;
  DELETE FROM public.billing_profiles WHERE tenant_id = p_tenant_id;
  DELETE FROM public.subscriptions WHERE tenant_id = p_tenant_id;
  DELETE FROM public.usage_entitlements WHERE tenant_id = p_tenant_id;
  DELETE FROM public.entitlement_ledger_entries WHERE tenant_id = p_tenant_id;
  DELETE FROM public.wallet_ledger_entries WHERE tenant_id = p_tenant_id;
  DELETE FROM public.wallet_accounts WHERE tenant_id = p_tenant_id;

  -- ============================================================
  -- STEP 20: Websites, Domains, Storage
  -- ============================================================
  DELETE FROM public.site_project_versions WHERE tenant_id = p_tenant_id;
  DELETE FROM public.site_projects WHERE tenant_id = p_tenant_id;
  -- websites not in live list — skip
  DELETE FROM public.domains WHERE tenant_id = p_tenant_id;
  -- custom_domains not in live list — skip
  DELETE FROM public.storage_file_references WHERE tenant_id = p_tenant_id;
  DELETE FROM public.storage_connections WHERE tenant_id = p_tenant_id;
  -- storage_drive_connections not in live list — skip
  DELETE FROM public.tenant_provider_connections WHERE tenant_id = p_tenant_id;
  DELETE FROM public.provider_usage_events WHERE tenant_id = p_tenant_id;
  -- byok_tenant_credentials not in live list — skip

  -- ============================================================
  -- STEP 21: Memberships & Invitations
  -- ============================================================
  DELETE FROM public.tenant_invitations WHERE tenant_id = p_tenant_id;
  -- tenant_memberships not in live list — skip
  DELETE FROM public.tenant_members WHERE tenant_id = p_tenant_id;

  -- ============================================================
  -- STEP 22: Delete the tenant record itself
  -- ============================================================
  DELETE FROM public.tenants WHERE id = p_tenant_id;

  -- ============================================================
  -- STEP 23: Record auditable platform event (best-effort, non-fatal)
  -- NOTE: platform_audit_events does not exist in production schema.
  -- The deletion is fully committed without it. Logged via application layer.
  -- ============================================================

  RETURN jsonb_build_object(
    'ok', true,
    'deleted_tenant_id', p_tenant_id,
    'slug', v_tenant.slug,
    'name', v_tenant.name
  );
END;
$$;

REVOKE ALL ON FUNCTION public.delete_customer_tenant_v1(UUID, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.delete_customer_tenant_v1(UUID, TEXT) TO service_role;

-- Force PostgREST schema cache reload
NOTIFY pgrst, 'reload schema';
