-- Registers the Hermes tool-call connector/capability/autonomy
-- authorization enforcement gate (master brief Section 18). Applied live
-- via Supabase MCP on 2026-09-07 (with one live typo correction folded in
-- below); this file makes it reproducible from a fresh database.

insert into public.capability_registry (
  capability_key, name, description, category, department,
  agent_tool_name, read_write, tenant_scope, cost_profile, risk, verification_method,
  status, status_notes, last_verified_at, last_verified_by
) values (
  'capability:hermes_tool_connector_authorization_enforcement',
  'Hermes tool calls now enforce real, server-side connector/capability/autonomy authorization -- master brief Section 18',
  'Section 18, called out as "a major priority": every Hermes tool invocation must verify Company+Capability+Connector+Permission+Autonomy before execution -- never rely on UI restrictions, never trust a tool name alone. Built packages/connectors/src/authorization.ts''s assertConnectorCapabilityAuthorized and wired it into apps/hermes-gateway/src/tool-handlers.ts''s invokeTool() -- the ONE real chokepoint every Hermes tool call passes through, so this cannot be bypassed by adding a new caller. A real HERMES_TOOL_CONNECTOR_MAP maps the (currently 2) Hermes tools genuinely backed by a Connector Control Plane connector -- generate_image (gemini/media.image_generation), check_domain_status (vercel/website.domain_status) -- to their real capability key; every other tool in Hermes'' restricted vocabulary is an internal StratXcel capability with no external connector at all (CRM, memory, mission progress, growth/website status reads), deliberately left ungated since gating a tool with nothing to gate would be theater, not enforcement. The gate checks, in order: connector connected, connector healthy, a real connector_capability_assignments row exists for this capability (matching this tenant OR a platform-wide assignment), and the assignment''s autonomy is neither disabled nor approval_required (approval_required BLOCKS outright in this v1 rather than silently proceeding -- auto-routing through the existing request_approval flow and resuming the mission afterward is a real, separate, larger mission-state integration, not built here, stated honestly). A denial is recorded as a real audit_events row (hermes.tool_call.<tool>.denied) before the ConnectorNotAuthorizedError is thrown -- never silently swallowed. Honest v1 scope: Hermes missions (MissionScopedContext) carry a verified tenantId but no agent_definition_id/department (confirmed against the live missions table schema before writing this) -- so this enforces Company+Connector+Capability+Autonomy, not yet full per-agent granularity; that needs mission-to-agent association added first, a real separate future task, not silently claimed here. Real, immediate practical effect: since no connector connections/assignments exist in production yet, generate_image and check_domain_status -- both previously unconditionally callable once HERMES_MODE=native is flipped -- will now correctly require an explicit Admin connect+assign action first, matching the brief''s own "a connector being present does NOT automatically mean every agent can use it." Zero live production impact today (HERMES_MODE stays disabled).',
  'hermes',
  'Engineering',
  'generate_image, check_domain_status (gated); all other Hermes tools (ungated -- no external connector)',
  'read_write',
  'tenant',
  'free',
  'low_mutation',
  'Extended packages/connectors/src/__tests__/connectors.test.ts with 2 new scenarios using a real functional fake Supabase double (not just source-regex): assertConnectorCapabilityAuthorized''s full real decision tree (not-connected, unhealthy, no-assignment, disabled, approval_required, execute-authorized, platform-wide-assignment-matches-any-tenant, undeclared-capability-refused-before-any-lookup) all produce the correct real outcome; invokeTool is confirmed via source inspection to check the gate BEFORE calling the real handler (index comparison proves ordering), to throw ConnectorNotAuthorizedError on denial, and to record a real audit_events row for the denial. Zero regressions across test:hermes-mission-control (11 files, unaffected since they call handlers directly, bypassing invokeTool -- confirmed deliberately), test:worker-ops (3 files), and the full packages/hermes suite (http-adapter/mock-adapter/native-adapter/token, 4 files -- native-adapter.test.ts uses its own dependency-injected invokeTool mock, confirmed unaffected by the real gateway''s new logic). Full-repo tsc --noEmit clean, lint clean, real NODE_ENV=production build (exit 0).',
  'REAL_EXPOSED',
  'Deliberately does not yet auto-route an approval_required capability through the existing request_approval flow (it blocks outright instead) -- a real, separate, larger mission-state integration (pause mission -> AWAITING_APPROVAL -> resume on approval), named as a genuine future task. Does not yet enforce per-agent/per-department granularity (missions have no agent_definition_id today). Only 2 of Hermes'' ~21 tools are connector-gated because only 2 currently map to a real external connector -- this is accurate scope, not an oversight; as more connector-backed Hermes tools are added (e.g. a future AWS-infrastructure tool, a future WhatsApp-outreach tool), they should be added to HERMES_TOOL_CONNECTOR_MAP to inherit this same enforcement automatically.',
  now(),
  'claude_session_2026-09-07'
);
