-- Converts the last two open capability_registry rows from ambiguous
-- "not yet investigated" placeholders into decisive, evidence-backed final
-- determinations: providers_package_unused (confirmed fully superseded by
-- 7 real sibling packages, zero real importers anywhere) and
-- editing_module_in_memory_prototype (re-examined against the same-day
-- Value Ledger fix's precedent; confirmed NOT the same shape -- a genuine,
-- larger, precisely-scoped future task, not a same-session-safe fix).
-- Applied live via Supabase MCP on 2026-09-02; this file makes it
-- reproducible from a fresh database.

update public.capability_registry
set status_notes = status_notes || ' RESOLVED 2026-09-02 (decisive investigation, not wired): confirmed with certainty rather than left as an open question. A repo-wide grep for "@stratxcel/providers" found ZERO real importers anywhere outside its own package (only package.json/package-lock.json/tsconfig.json workspace registration) -- and every one of its 9 domains (ai, dns, domains, email, hosting, images, payments, research, storage) has a real, dedicated, already-live sibling package doing the same job with deeper integration: ai/images -> @stratxcel/ai-runtime, dns/domains/hosting -> @stratxcel/websites-and-domains, email -> @stratxcel/email-runtime, payments -> @stratxcel/payments-and-wallet, research -> @stratxcel/search-discovery (a far more mature, GA4/GSC-integrated engine than this package''s generic Serper wrapper), storage -> @stratxcel/storage. This is a fully superseded, one-to-one-redundant abstraction layer, not an unexploited real gap -- wiring it now would mean ripping out 7 working, tested, live integrations for zero functional gain, a real regression risk with no upside. Correctly staying REAL_NOT_EXPOSED is the honest, permanent answer here, not a placeholder pending a future decision. Recommendation for a future pass (not done here -- a real code deletion across ~2,556 lines plus its own test suite and workspace registration is a deliberate, separate action, not bundled into this investigation): delete packages/providers entirely as confirmed dead code, removing packages/providers/src/__tests__/providers.test.ts and production-activation.test.ts from test:website-factory and the workspace entry from the root package.json/tsconfig.json at the same time.',
    last_verified_at = now(), last_verified_by = 'claude_session_2026-09-02'
where capability_key = 'capability:providers_package_unused';

update public.capability_registry
set status_notes = status_notes || ' RE-EXAMINED 2026-09-02 (decisive scoping pass, after successfully fixing the structurally-similar Value Ledger engine the same day): checked whether this was ALSO safely fixable this pass, the way Value Ledger turned out to be -- it is not, for a precise, verified reason. Value Ledger''s in-memory methods were ALREADY declared async (the fix only swapped the internal implementation, zero caller signature changes). WebsiteVersionManager''s 7 public methods (registerInitialVersion, assertConcurrency, createVersion, getHistory, getVersionSnapshot, rollback, markVersionLive) are ALL synchronous, called synchronously throughout engine.ts/applier.ts/planner.ts/classifier.ts and a real 271-line test suite (website-editing-and-versioning.test.ts) -- converting to real DB-backed persistence means every one of those call sites must become async too, a genuinely invasive, cascading refactor across ~1,400 lines and its whole test suite, not a narrow implementation swap. Unlike capability:providers_package_unused, this is NOT redundant/safe-to-leave-permanently: it offers real version-history/rollback for individual website content edits that edit_website (the current live path, Update 42) genuinely lacks -- rollback_deployment (shipped this same pass) rolls back an entire Vercel DEPLOYMENT, a different concept from rolling back one content edit within a still-live deployment. Correctly left unattempted this pass -- a genuine, separate, scoped future task: convert WebsiteVersionManager''s 7 methods to async + a real version_snapshots table (same discipline as every other in-memory fix this session), update its ~4 internal call sites, re-verify the existing 271-assertion test suite, THEN wire a real caller (e.g. a website_edit_history / undo_website_edit agent tool). Not rushed here specifically to avoid the alternative: a hastily-broken sync-to-async conversion across a real, already-tested subsystem, which is a materially worse outcome than an honestly-scoped, precisely-documented remaining task.',
    last_verified_at = now(), last_verified_by = 'claude_session_2026-09-02'
where capability_key = 'capability:editing_module_in_memory_prototype';
