-- Sharpens engine:hermes_missions's external_blocker with the real,
-- precise picture found by investigating the "autonomous execution loop"
-- directly rather than reasserting the prior summary: apps/mission-worker
-- and apps/hermes-gateway are confirmed LIVE right now (worker_heartbeats),
-- but the third-party nousresearch/hermes-agent engine itself has never
-- been deployed anywhere, in any session. Applied live via Supabase MCP on
-- 2026-09-02; this file makes it reproducible from a fresh database.

update public.capability_registry
set external_blocker = 'nousresearch_hermes_agent_upstream_engine_never_deployed_plus_inference_provider_billing_decision',
    status_notes = status_notes || ' SHARPENED 2026-09-02 (autonomous-execution-loop investigation, same day): the prior note undersold how much of this is already real and oversimplified what remains. CONFIRMED LIVE right now via worker_heartbeats: apps/mission-worker and apps/hermes-gateway (StratExcel''s OWN queue consumer and restricted tool-callback gateway) are both deployed and actively heartbeating on the real EC2 host (staleness <30s at check time) -- this is not aspirational, it is running production infrastructure. What is genuinely, completely missing is the THIRD-PARTY autonomous engine itself: HERMES_MODE=http calls out to a self-hosted nousresearch/hermes-agent instance (infrastructure/hermes/README.md), which has never been deployed anywhere in any session -- Docker was unavailable in the session that wrote that doc, so even the documented docker-compose recipe has never been run once, not even in a dev/test capacity. Per MANUAL_SETUP_REQUIRED.md M9/M11: this needs (a) an inference-provider API key (OpenRouter recommended) -- a real billing decision this agent was explicitly told to stop at; (b) a real host for the engine itself (M11 recommends a SEPARATE small instance from the shared EC2 box, since Hermes Agent alone wants ~2GB RAM and the existing box already runs four persistent processes on ~2GB total) -- a real infra/cost decision needing approval; (c) once both exist, HERMES_MODE=http plus matching HERMES_GATEWAY_URL/HERMES_API_KEY on the mission-worker host. A genuine, unresolved architectural question also remains open per that same README: whether Hermes Agent''s tool-calling can be scoped to one mission''s allowlist rather than installation-wide is undocumented anywhere reachable, and needs verification against a REAL running instance before this could be trusted with real tool access -- not just an authorization step, a real open design question. HERMES_MODE=mock (MockHermesAdapter) IS fully real and already verified end-to-end (create_mission -> queue -> execute -> complete against simulated output, scripts/hermes-smoke-test) -- the StratExcel-side pipeline is genuinely proven; only the real upstream engine round-trip is unproven.',
    last_verified_at = now(), last_verified_by = 'claude_session_2026-09-02'
where capability_key = 'engine:hermes_missions';
