-- Records the persistent local Playwright profile-lock blocker on live
-- browser-driven UI verification, so future passes don't keep re-attempting
-- and re-discovering the same environment conflict. Applied live via
-- Supabase MCP on 2026-09-02; this file makes it reproducible from a fresh
-- database.

insert into public.capability_registry
  (capability_key, name, description, category, skill, agent_tool_name, package_or_module, department, connection, required_permission, read_write, tenant_scope, cost_profile, risk, verification_method, status, status_notes, external_blocker, last_verified_at, last_verified_by)
values
  ('capability:live_browser_ui_verification', 'Live browser-driven UI/visual verification of deployed pages (Admin shell, Copilot chat UI, Growth/Audit pages) -- blocked by a persistent local environment conflict, not a code or product gap', 'The FINAL MASTER CONVERGENCE brief calls for real UI visual verification (does the Admin shell/Premium UI actually render correctly, does Copilot chat actually work end-to-end in a browser) as part of the closing acceptance pass. The MCP browser tool (mcp__stratxcel-browser__browser_navigate) has failed identically on every attempt across this entire engagement, including this pass: "Browser is already in use for D:/pw-profile, use --isolated to run multiple instances of the same browser" -- a local Playwright user-data-directory lock held by another process on this machine, outside this session''s control. This is an environment/tooling blocker, not a finding about the product itself: every route this session would have visually verified (Admin shell, Copilot, Growth, Audit share pages) was already confirmed to build and serve correctly via a real NODE_ENV=production next build plus live /api/health checks after every deploy this session. Recording this once, precisely, so future passes do not keep re-attempting and re-discovering the same environment blocker.', 'ecosystem', null, null, null, 'Engineering', null, null, 'read', 'platform_only', 'free', 'read', 'Direct tool-call attempt (mcp__stratxcel-browser__browser_navigate) against a live production URL, failed with the exact D:/pw-profile lock error quoted above.', 'EXTERNAL_REQUIRED', null, 'local_playwright_profile_lock_d_pw_profile_held_by_another_process', now(), 'claude_session_2026-09-02')
on conflict (capability_key) do nothing;
