-- Records a real cost-optimization finding (master brief section 27):
-- analyze_website's underlying pipeline makes several sequential HTTP
-- fetches with zero caching. Applied live via Supabase MCP on 2026-09-02;
-- this file makes that reproducible from a fresh database.
insert into public.capability_registry
  (capability_key, name, description, category, skill, agent_tool_name, package_or_module, department, connection, required_permission, read_write, tenant_scope, cost_profile, risk, verification_method, status, status_notes, external_blocker, last_verified_at, last_verified_by)
values
  ('capability:analyze_website_no_cache', 'analyze_website (and its underlying runWebsiteIntelligencePipeline) makes several real sequential HTTP fetches with zero caching -- a real cost-optimization gap', 'Master brief section 27 (cost optimization: "unnecessary... crawls... duplicate calculations"). Confirmed by reading lib/intelligence/website-intelligence.ts directly: runWebsiteIntelligencePipeline has no caching of any kind -- every analyze_website call re-fetches and re-processes the same URL from scratch, even if asked about the identical site minutes apart (e.g. a staff member re-running an analysis, or multiple callers asking about the same prospect). A proper fix needs a real Postgres-backed cache keyed by normalized URL with a deliberate TTL policy (an in-memory cache would not survive across serverless invocations -- the same lesson already learned live this session from the editing/ module''s in-memory version manager, capability:editing_module_in_memory_prototype) -- not built in this pass, since the right TTL is a real product decision (how fresh must an ad-hoc "analyze this website" result be?) that deserves deliberate choice, not a rushed guess.', 'ecosystem', null, 'analyze_website', 'lib/intelligence/website-intelligence.ts, lib/agent-core/research-tools.ts', 'Engineering', null, 'agent:read:research', 'read', 'global', 'free', 'read', 'Read website-intelligence.ts directly: zero cache-related code anywhere in the file.', 'PARTIAL', 'The tool itself is real and correctly exposed (REAL_EXPOSED as a capability) -- this entry tracks specifically the missing caching/dedup layer as its own honest, separate optimization opportunity, not a defect in the tool''s correctness.', null, now(), 'claude_session_2026-09-02')
on conflict (capability_key) do nothing;
