-- Additive capability_registry row documenting the Universal Verification
-- audit (autonomous-convergence-loop mission, section 10): every mutating
-- tool in the repository was audited for the exact defect class Updates
-- 10/13 fixed live; two more real, previously-unfixed instances were found
-- and closed. Applied live via Supabase MCP on 2026-09-02; this file makes
-- that reproducible from a fresh database.
insert into public.capability_registry
  (capability_key, name, description, category, skill, agent_tool_name, package_or_module, department, connection, required_permission, read_write, tenant_scope, cost_profile, risk, verification_method, status, status_notes, external_blocker, last_verified_at, last_verified_by)
values
  ('capability:universal_verification_audit', 'Universal verification-integrity audit', 'Every mutating tool across packages/agent-core (admin + client) and lib/social''s separate Social Autopilot agent loop was audited for the exact soft-failure-reported-as-success defect class Updates 10/13 fixed live. Two more real, previously-unfixed instances found and closed: (1) create_mission (both the staff and client tools -- shared via a new interpretMissionOutcome helper) can return a mission stuck in AWAITING_FUNDS/AWAITING_APPROVAL/AWAITING_INPUT/HUMAN_HANDOFF without throwing; (2) Social Autopilot''s OWN, separate agent orchestrator (lib/social/agent/orchestrator.ts -- a distinct AgentTool contract and runAgentTurn from packages/agent-core''s canonical one) never checked generate_image''s outcome field at all, despite already having a working deterministic-override pattern for its 3 publish-intent tools (schedule_post + 2 YouTube verification tools) -- the exact Update-9/10 incident was independently live there the whole time, unaffected by every fix in this repository''s canonical agent-core path. Also closed: forget_fact silently returning forgotten:false (no matching memory) with no verification note.', 'ecosystem', null, null, 'packages/agent-core/src/tools/mission-outcome.ts + admin/mutation-tools.ts + client/tools.ts + brain/memory/tools.ts + lib/social/agent/orchestrator.ts + publish-outcome-classify.ts', 'Engineering', null, null, 'read', 'platform_only', 'free', 'read', 'mission-outcome.test.ts + image-generation-outcome.test.ts (both new)', 'REAL_EXPOSED', 'All every other mutating tool in the repository (7 admin CRM/ops tools, generate_image''s original agent-core copy, execute_growth_action, send_whatsapp_message_to_contact) was independently re-verified during this audit to either already have interpretOutcome or to only ever throw-or-succeed cleanly (updateLeadStatus/updateLead/setConversationAutomationMode/scheduleFollowUp/requestAppointment/createHumanHandoff all use .single() + throw-on-error, no soft-failure return shape exists).', null, now(), 'claude_session_2026-09-02');
