-- Records removal of a dead, fully orphaned legacy layout file
-- (app/admin/platform/layout.tsx) found while starting the Admin IA
-- rebuild. Applied live via Supabase MCP on 2026-09-02; this file makes
-- that reproducible from a fresh database.
insert into public.capability_registry
  (capability_key, name, description, category, skill, agent_tool_name, package_or_module, department, connection, required_permission, read_write, tenant_scope, cost_profile, risk, verification_method, status, status_notes, external_blocker, last_verified_at, last_verified_by)
values
  ('capability:admin_ia_cleanup_dead_platform_layout', 'Removed a dead, fully orphaned legacy layout file: app/admin/platform/layout.tsx', 'Master brief section 15/6: "remove dead/obsolete pages." Found while starting the Admin IA rebuild: app/admin/platform/layout.tsx (outside the "(shell)" route group) defined its own auth gate and an 8-item nav bar linking to tenants/missions/approvals/payments/wallet/queue/whatsapp -- but NONE of those routes, nor the segment itself, had a page.tsx anywhere in that subtree (confirmed by exhaustive file listing). The real, live, fully-functional versions of all 8 pages already exist at app/admin/(shell)/platform/* -- route groups are elided from the URL, so they serve the identical /admin/platform/* public paths. Two existing tests (platform-admin-layout-gate.test.ts, unified-shell-tenant-ux.test.ts) explicitly document this as a completed "Phase 1" migration and assert against the (shell) version, never the outer one -- confirming the outer file was a leftover the migration missed, not an intentionally-kept file. Deleted app/admin/platform/layout.tsx (and its now-empty parent directory). Verified: both relevant tests still pass, full-repo tsc --noEmit clean (after clearing a stale .next/types cache reference), real NODE_ENV=production next build exit 0 with /admin/platform/* routes still building correctly from the (shell) group alone.', 'ecosystem', null, null, 'app/admin/platform/layout.tsx (removed)', 'Engineering', null, null, 'read', 'platform_only', 'free', 'read', 'platform-admin-layout-gate.test.ts and unified-shell-tenant-ux.test.ts both pass, full-repo tsc --noEmit clean, real NODE_ENV=production next build exit 0 with all 8 /admin/platform/* routes still resolving', 'REAL_EXPOSED', 'This is itself the fix, not a pending item. First concrete step of the Admin IA rebuild (master brief sections 15-20): route-tree cleanup before nav/mode restructuring.', null, now(), 'claude_session_2026-09-02')
on conflict (capability_key) do nothing;
