-- Migration: Flag Historical Simulated Legacy Audit Records
-- Identifies records generated by the previous simulation pass and sets generation_method and report_trust_status.

update public.public_audit_requests
set report_data = jsonb_set(
  jsonb_set(
    coalesce(report_data, '{}'::jsonb),
    '{generation_method}',
    '"simulated_legacy"'
  ),
  '{report_trust_status}',
  '"unverified"'
)
where report_data ? 'executiveSummary'
  and not (report_data ? 'generation_method');
