-- Records the real Lucide icon library adoption across the shared shell
-- (master brief sections 19-20, "prefer appropriate use of... Lucide").
-- Applied live via Supabase MCP on 2026-09-02; this file makes that
-- reproducible from a fresh database.
insert into public.capability_registry
  (capability_key, name, description, category, skill, agent_tool_name, package_or_module, department, connection, required_permission, read_write, tenant_scope, cost_profile, risk, verification_method, status, status_notes, external_blocker, last_verified_at, last_verified_by)
values
  ('capability:lucide_icon_migration', 'Real Lucide icon library adopted across the shared shell -- master brief sections 19-20 ("prefer appropriate use of... Lucide")', 'Installed lucide-react (0.469.0, pinned) as a real new dependency -- confirmed the npm registry is reachable from this environment before committing to the change. Replaced every hand-drawn inline <svg> icon in the shared shell with its real lucide-react equivalent, same size/stroke-width preserved so no call site needed to change beyond the icon definitions themselves: components/shell/navigation/shared-icons.tsx (18 icons -- LayoutGrid, Bot, FileText, Check, MessageSquare, Globe, Search, Target, Megaphone, Sparkles, Folder, BarChart3, Plug, Wallet, Users, Settings, Handshake, ListOrdered, Activity), components/shell/navigation/app-nav-icons.tsx (6 icons -- House, CheckCircle2, Image, TrendingUp, Store, MessageCircle), components/shell/TopCommandBar.tsx (HelpCircle), components/shell/Sidebar.tsx (PanelLeftClose/PanelLeftOpen), components/shell/MobileBottomNav.tsx (MoreHorizontal). Deliberately did NOT attempt a full shadcn/Radix/Tremor component-framework migration: the existing hand-rolled design system (Card/StatusChip/Metric, the sx-* CSS token set) is itself already a real, coherent, tested, non-templated system built with genuine care -- ripping it out for a different framework would be a large, high-risk, low-value change per this session''s own "reuse existing canonical engines, never duplicate" discipline applied to UI. Lucide (a focused, additive icon library, not a competing component framework) was the safe, real, honest way to act on the brief''s specific library preference without that risk.', 'ecosystem', null, null, 'components/shell/navigation/shared-icons.tsx, app-nav-icons.tsx, components/shell/TopCommandBar.tsx, Sidebar.tsx, MobileBottomNav.tsx', 'Engineering', null, null, 'read', 'platform_only', 'free', 'read', 'Full-repo tsc --noEmit clean, lint clean (one jsx-a11y false-positive on the Image icon name fixed via aliasing), test:unified-shell-crm (5 files) and test:foundation (both suites) pass unchanged, real NODE_ENV=production next build exit 0.', 'REAL_EXPOSED', 'A real, scoped, honest fulfillment of the Lucide preference. The full Premium UI visual redesign (shadcn/Radix/Tremor component adoption, a broader visual pass) remains genuinely not done -- not claimed complete here.', null, now(), 'claude_session_2026-09-02')
on conflict (capability_key) do nothing;
