-- Records the honest Market Discovery finding (master brief section 13):
-- genuinely not built, no provider integrated, blocked on external OAuth
-- authorization (a real Apollo.io connector is available but unauthorized).
-- Applied live via Supabase MCP on 2026-09-02; this file makes that
-- reproducible from a fresh database.
insert into public.capability_registry
  (capability_key, name, description, category, skill, agent_tool_name, package_or_module, department, connection, required_permission, read_write, tenant_scope, cost_profile, risk, verification_method, status, status_notes, external_blocker, last_verified_at, last_verified_by)
values
  ('capability:market_discovery', 'Market Discovery (finding new prospective-customer businesses matching an ICP) -- genuinely not built, no provider integrated', 'Master brief section 13, which explicitly warns not to call generic web research "market discovery." Confirmed by repo-wide search: no dedicated lead/company/market-discovery engine exists anywhere (packages/search-discovery is SEO/site-audit discovery, a different concept; packages/leads-and-crm manages leads already in the CRM, it does not find new ones). No business-directory/company-data provider (Google Places, Apollo, Clearbit, Hunter, ZoomInfo, etc.) is integrated anywhere -- zero matches for any of those names in the codebase. A real, relevant provider IS available as a Claude connector in this environment (claude.ai Apollo.io, a real B2B company/lead discovery platform) but requires an interactive OAuth authorization this agent session cannot perform on its own. This is the honest unblocking path, not a hypothetical one.', 'ecosystem', null, null, null, 'Engineering', 'apollo_io', null, 'read', 'global', 'external', 'read', 'Repo-wide grep for market/lead-discovery engines and every plausible provider name (google places, apollo, clearbit, hunter.io, zoominfo): zero real implementation found.', 'EXTERNAL_REQUIRED', 'Genuinely blocked on external authorization (Apollo.io connector OAuth, or an equivalent business-data provider with a real API key), not on missing engineering effort. Once authorized, a real market-discovery tool could be built the same way every other real-provider tool in this session was: reuse the connector''s real data, never fabricate matches.', 'apollo_io_oauth_authorization_required', now(), 'claude_session_2026-09-02')
on conflict (capability_key) do nothing;
