-- Records a real finding from the master brief's "final rescan for
-- fabrication/placeholder patterns" pass: lib/reporting/value-ledger.ts and
-- lib/billing/monthly-cycle.ts are real, well-built, but completely
-- unwired, and both use an in-memory-store anti-pattern already flagged
-- elsewhere this session (packages/websites-and-domains/src/editing).
-- Applied live via Supabase MCP on 2026-09-02; this file makes it
-- reproducible from a fresh database.

insert into public.capability_registry
  (capability_key, name, description, category, skill, agent_tool_name, package_or_module, department, connection, required_permission, read_write, tenant_scope, cost_profile, risk, verification_method, status, status_notes, external_blocker, last_verified_at, last_verified_by)
values
  ('capability:monthly_value_ledger_engine', 'Monthly Value Ledger / Work & Value Report engine (lib/reporting/value-ledger.ts, lib/billing/monthly-cycle.ts) -- real, well-built, but completely unwired, and backed by in-memory storage', 'Found during a final rescan for fabrication/placeholder patterns (grepped for Math.random() usage as a fake-metric smell, which led here). ValueLedgerService (lib/reporting/value-ledger.ts) and MonthlyRenewalEngine (lib/billing/monthly-cycle.ts, which composes it with generateTailoredCustomerPlans and synthesizeBusinessRequirements into a full monthly recap package) are real, non-trivial, deliberately-designed code -- not a fabrication risk in the sense of fake numbers; the concern is structural. Two real defects, both currently inert because nothing calls this code: (1) ValueLedgerService.recordDeliverable/listEntriesForMonth store all data in a private in-memory array (this.inMemoryStore), and MonthlyRenewalEngine caches generated recap packages in a private in-memory Map (this.generatedRecapCache) -- the exact same anti-pattern already flagged this session in packages/websites-and-domains/src/editing''s WebsiteVersionManager (never fixed there either, deliberately left un-wired) -- any data recorded would vanish on the next serverless cold start/redeploy and never be shared across concurrent instances; (2) zero real callers anywhere in app/, lib/ (outside itself), apps/, or packages/ other than its own module and two test files (packages/whatsapp/src/copilot/copilot-agent.ts, itself dead -- confirmed zero real callers of THAT module too, referenced only by two test files). Genuinely valuable if built out (a real "prove your monthly ROI" customer report is a real churn-reduction lever) but out of the explicitly-named scope of the current convergence pass -- recorded honestly rather than either silently wired with its in-memory defect intact or invented as new unrequested scope.', 'ecosystem', null, null, 'lib/reporting/value-ledger.ts; lib/billing/monthly-cycle.ts', 'Engineering', null, null, 'read_write', 'tenant', 'free', 'read', 'Grepped for Math.random() as a fake-metric smell across the non-test codebase (25 files, most benign id/jitter generation); read value-ledger.ts and monthly-cycle.ts in full; confirmed zero real callers of MonthlyRenewalEngine/valueLedgerService anywhere outside lib/billing/monthly-cycle.ts itself, docs, and test files; traced the one real-code caller (packages/whatsapp/src/copilot/copilot-agent.ts) and confirmed IT also has zero real callers (referenced only by two __tests__ files).', 'REAL_NOT_EXPOSED', 'If this is ever wired into a real feature, the in-memory stores must be replaced with real Postgres-backed tables first (same discipline as website_intelligence_cache, Update 53) -- wiring it with the in-memory defect intact would silently repeat the editing/ module''s known anti-pattern in a new place.', null, now(), 'claude_session_2026-09-02')
on conflict (capability_key) do nothing;
