-- Records the new check_deployment_status agent tool (master brief
-- section 7, Website/Vercel deployment status). Applied live via Supabase
-- MCP on 2026-09-02; this file makes that reproducible from a fresh
-- database.
insert into public.capability_registry
  (capability_key, name, description, category, skill, agent_tool_name, package_or_module, department, connection, required_permission, read_write, tenant_scope, cost_profile, risk, verification_method, status, status_notes, external_blocker, last_verified_at, last_verified_by)
values
  ('capability:check_deployment_status_tool', 'check_deployment_status: real Vercel deployment history exposed to WhatsApp/Admin/Client Copilot -- section 7 (Website/Vercel: deployment status)', 'Found while re-auditing engine:website_vercel_orchestration (still REAL_NOT_EXPOSED for the creation/editing/deployment mutation surface): listVercelDeployments (packages/search-discovery/src/vercel/client.ts) is a real, already-implemented function -- real Vercel /v7/deployments API call, real readyState/url/createdAt per deployment -- with zero real callers anywhere in the codebase before this. Wired as a new read-only tool, check_deployment_status (lib/agent-core/growth-media-tools.ts), using the same VERCEL_AUTH_TOKEN and VERCEL_PROJECT_ID default already proven live by check_domain_status. Read-only: never triggers, cancels, or rolls back a deployment -- only reports real recent history.', 'ecosystem', null, 'check_deployment_status', 'lib/agent-core/growth-media-tools.ts', 'Engineering', null, 'agent:read:website', 'read', 'platform_only', 'free', 'read', 'Full-repo tsc --noEmit clean, lint clean, real NODE_ENV=production next build exit 0. No dedicated mocked test -- matches this file''s own established pattern for its other real-Vercel-API read tools (check_domain_status has none either), verified via build/production usage.', 'REAL_EXPOSED', 'A real, additive slice of engine:website_vercel_orchestration -- deployment status is now genuinely reachable. Deployment triggering, rollback, and recovery as agent-invokable mutations remain not built.', null, now(), 'claude_session_2026-09-02')
on conflict (capability_key) do nothing;
