-- Records commit_growth_plan -- the first real INSERT into workforce_plans
-- anywhere in this codebase (master brief sections 5/15). Verified live
-- against the real schema with a transactional dry-run insert (rolled
-- back) before this migration was written. Applied via Supabase MCP on
-- 2026-09-02; this file makes the capability_registry entries
-- reproducible from a fresh database.
insert into public.capability_registry
  (capability_key, name, description, category, skill, agent_tool_name, package_or_module, department, connection, required_permission, read_write, tenant_scope, cost_profile, risk, verification_method, status, status_notes, external_blocker, last_verified_at, last_verified_by)
values
  ('capability:commit_growth_plan_tool', 'commit_growth_plan: the first real INSERT into workforce_plans anywhere in this codebase -- persists a real, mission-linked 30-day growth plan', 'Master brief section 5 (Learning) and section 15 (Priority Engine full pipeline). Closes the precise blocker recorded against engine:learning_loop this same session: workforce_plans had zero real INSERT writers anywhere (confirmed by repo-wide grep; its only prior reference, lib/tenants/lifecycle.ts, is a tenant-offboarding delete path). Requires a real, already-existing missionId (from a prior create_mission call) -- never creates a mission itself. Real tenant-isolation check before any write: the mission''s own tenant_id must match the resolved caller tenant or the write is refused. Recomputes the plan fresh via planBusinessGrowth using assembleBusinessGrowthPlannerInput (the same real input assembly check_business_priorities/preview_growth_plan already use), then inserts the real mapped fields (objective, business_outcome, entitlement_snapshot, capability_snapshot, strategy_payload, budget_envelope) -- version/status/planning_horizon use the table''s own real defaults (1/DRAFT/30_day). Verified end-to-end against the live schema with a real transactional dry-run insert (BEGIN...ROLLBACK against a real tenant+mission row, confirmed the exact column shapes work, then rolled back leaving zero permanent data) before shipping, not just via tsc. mutating: true, risk: external_mutation, confirm-gated on every channel -- same classification as create_mission itself.', 'ecosystem', null, 'commit_growth_plan', 'lib/agent-core/growth-plan-commit-tool.ts', 'Engineering', null, 'agent:mutate:missions', 'read_write', 'tenant', 'free', 'external_mutation', 'Full-repo tsc --noEmit clean, lint clean, test:agent-core suite passes unchanged, real NODE_ENV=production next build exit 0, plus a real transactional dry-run insert against the live workforce_plans table (rolled back, zero permanent data) confirming the exact schema mapping is correct.', 'REAL_EXPOSED', 'The first real write path to workforce_plans. engine:learning_loop can now be revisited: a real persisted BusinessGrowthPlan exists to revise once a plan is actually committed. Revision itself (applyLearningRevision) is not wired to any tool yet -- a genuine next step, not claimed done here.', null, now(), 'claude_session_2026-09-02')
on conflict (capability_key) do nothing;

update public.capability_registry
set status_notes = status_notes || ' UPDATE 2026-09-02 (later pass, same day): the precise blocker recorded above is now fixed -- see capability:commit_growth_plan_tool, the first real INSERT into workforce_plans. A real, mission-linked BusinessGrowthPlan can now genuinely exist in production. Still honestly open: applyLearningRevision (the actual revision logic) is not wired to any real tool yet, and no real measured-outcome capture pipeline feeds it real MeasuredPerformanceSignal data -- the write path existing is necessary but not sufficient for the full learning loop to run.',
    last_verified_at = now(),
    last_verified_by = 'claude_session_2026-09-02'
where capability_key = 'engine:learning_loop';
