-- Records the Learning loop's two real halves shipped together:
-- check_plan_outcomes (real measured observations from search_measurement_
-- snapshots) and revise_growth_plan (confirm-gated, evidence-required
-- revision persisted as a new versioned workforce_plans row). Applied live
-- via Supabase MCP on 2026-09-02; this file makes it reproducible from a
-- fresh database.

update public.capability_registry
set status = 'REAL_EXPOSED',
    status_notes = status_notes || ' CLOSED 2026-09-02 (Learning/outcome-loop build, same day): both real halves now exist. check_plan_outcomes (lib/agent-core/plan-outcomes-tool.ts) computes real MetricObservation-shaped data from search_measurement_snapshots -- the same real GA4/Search Console captures check_growth_status already surfaces -- comparing the latest snapshot since a plan''s commit date against the closest one before it, with explicit missing-baseline handling (never fabricates a comparison; a division-by-zero baseline yields changePercent: null, never an invented infinite%). revise_growth_plan (lib/agent-core/growth-plan-revision-tool.ts) is the confirm-gated write half: refuses to revise a plan with zero real measured observations since commit ("Revision requires evidence" per learning-loop.ts''s own rule), derives real evidenceIds from those observations'' own snapshot ids, calls the real reviseThirtyDayPlan, and persists a new versioned workforce_plans row (previous_plan_id links it to the one it revises -- the schema commit_growth_plan''s own migration already built for exactly this). Deliberately still NOT automated, stated honestly: neither tool computes attribution (which real bottleneck caused which change) or a confidence-scored OptimizationRecommendation -- packages/workforce-core''s AttributionLink/OptimizationRecommendation types exist for that, but a real, evidence-based classifier for them is a distinct, larger task this pass correctly did not attempt. The human (or the model reasoning from check_plan_outcomes'' real numbers, confirm-gated before revise_growth_plan ever runs) decides what changed and why -- this tool only enforces that the decision is grounded in at least one real number, never zero. A real schema-verification catch during this build: plan-outcomes.ts originally filtered on availability_state = "available", a value that does not exist in the real CHECK constraint (connected|not_connected|permission_required|configuration_required|waiting_for_data|error) -- would have silently matched zero rows forever; found and fixed before shipping by reading the live constraint directly, confirmed against the real GA4 write path (runtime.ts) which uses "connected".',
    external_blocker = null,
    last_verified_at = now(), last_verified_by = 'claude_session_2026-09-02'
where capability_key = 'engine:learning_loop';
