-- Records the real runRevenueWorkflow wiring (Economic Intelligence),
-- exposed as check_revenue_diagnostics, plus the follow-up note on
-- capability:revenue_ops_workflow_pipeline reflecting real progress.
-- Applied live via Supabase MCP on 2026-09-02; this file makes that
-- reproducible from a fresh database.
insert into public.capability_registry
  (capability_key, name, description, category, skill, agent_tool_name, package_or_module, department, connection, required_permission, read_write, tenant_scope, cost_profile, risk, verification_method, status, status_notes, external_blocker, last_verified_at, last_verified_by)
values
  ('capability:revenue_diagnostics_pipeline', 'Real runRevenueWorkflow wiring: response-time diagnosis, lead intelligence, qualification, drafted follow-up plans and WhatsApp sequences, human-handoff -- exposed as check_revenue_diagnostics', 'The Economic Intelligence section of the master brief: the first real production caller of packages/revenue-ops''s runRevenueWorkflow (previously called only by its own test suite -- capability:revenue_ops_workflow_pipeline). New lib/agent-core/revenue-diagnostics.ts builds every required and honestly-available optional input from real tables: LeadRowInput[] direct from crm_leads (an unmodeled real source value, whatsapp_outreach, is normalized to whatsapp rather than dropped or guessed at something unrelated), LeadTimingSample[] from a real crm_leads-created_at vs whatsapp_messages-outbound-direction join (firstOutboundAtIso/hasPendingInbound both computed from real message ordering, never fabricated), consentByLeadId from contact_consent (real lead_id FK), and latestCustomerMessageByLeadId from the most recent real inbound whatsapp_messages row. offeredServices comes from the real current Brand Brain (getCurrentBrandBrain). Exposed as a new read-only agent tool, check_revenue_diagnostics (lib/agent-core/revenue-diagnostics-tool.ts). Two real inputs are honestly NOT sourced yet, left to runRevenueWorkflow''s own confirmed-optional field handling rather than fabricated: `events` for diagnoseConversion (no analytics-conversion-event table verified yet -- conversion diagnosis reports no data, not an invented rate) and conversationByLeadId''s automationMode/insideSessionWindow/approvedTemplates (a separate subsystem not traced this pass). Read-only by the underlying engine''s own design: productionMutations and sendAttempts are always empty -- nothing is ever sent or written, only diagnosed and drafted.', 'ecosystem', null, 'check_revenue_diagnostics', 'lib/agent-core/revenue-diagnostics.ts, lib/agent-core/revenue-diagnostics-tool.ts', 'Engineering', null, 'agent:read:research', 'read', 'tenant', 'free', 'read', 'revenue-diagnostics.test.ts (new, 3 real assertions incl. cross-tenant/no-message/no-consent honesty checks and the whatsapp_outreach source-normalization case), full test:revenue-ops suite still passes, full-repo tsc --noEmit clean, lint clean, real NODE_ENV=production next build exit 0', 'REAL_EXPOSED', 'runRevenueWorkflow''s response-time/lead-intelligence/qualification/follow-up-plan/WhatsApp-sequence-draft/handoff half is now genuinely reachable via WhatsApp/Admin/Client Copilot with real evidence. diagnoseConversion (needs a real analytics-conversion-event source) and full conversationByLeadId automation context (needs a separate subsystem trace) remain honestly open, not fabricated to look complete.', null, now(), 'claude_session_2026-09-02')
on conflict (capability_key) do nothing;

update public.capability_registry
set status_notes = status_notes || ' UPDATE (same day, next pass): runRevenueWorkflow is now genuinely wired to real inputs and exposed as check_revenue_diagnostics -- see capability:revenue_diagnostics_pipeline. Still honestly open: diagnoseConversion''s real analytics-event source and conversationByLeadId''s automation-mode context (a separate subsystem not yet traced).',
    last_verified_at = now(),
    last_verified_by = 'claude_session_2026-09-02'
where capability_key = 'capability:revenue_ops_workflow_pipeline';
