-- Records customer-facing /app/growth parity with the real Growth
-- Priorities pipeline (master brief section 23, "same brain across
-- interfaces"), plus two real fabrication bugs fixed on that same page.
-- Applied live via Supabase MCP on 2026-09-02; this file makes that
-- reproducible from a fresh database.
insert into public.capability_registry
  (capability_key, name, description, category, skill, agent_tool_name, package_or_module, department, connection, required_permission, read_write, tenant_scope, cost_profile, risk, verification_method, status, status_notes, external_blocker, last_verified_at, last_verified_by)
values
  ('capability:customer_growth_priorities_parity', 'Customer-facing /app/growth now shows the same real Growth Priorities the Admin/WhatsApp Copilot answers -- "same brain across interfaces" (section 23)', 'New app/api/platform/growth/priorities/route.ts -- a customer-safe (requireTenantReadContext, RLS session client, brand_brain:view permission) counterpart to check_business_priorities (Update 38), calling the exact same real functions: computeRealBusinessSignals, computeRealEntitlementSnapshot, getCurrentBrandBrain, loadIntegrationsStatusData, diagnoseBusinessGrowth, deriveBottlenecks. app/app/growth/page.tsx gained a 5th concurrent loader and a new "What Should Happen Next" card rendering real evidence-gated bottlenecks -- only shown once real data resolves, not rendered at all if the result is genuinely empty. Two real fabrication bugs fixed in the same file while working on it: (1) the Growth Audit score line silently fell back to a hardcoded "85/100" whenever the real overall_score field was missing -- now only renders when a real numeric score exists; (2) the "Content Assets" card hardcoded the word "Active" unconditionally with zero real check behind it -- replaced with an honest navigation-only card, matching this same file''s own established pattern for the Search Growth card directly above it.', 'ecosystem', null, null, 'app/api/platform/growth/priorities/route.ts, app/app/growth/page.tsx', 'Engineering', null, 'brand_brain:view', 'read', 'tenant', 'free', 'read', 'customer-app-bugfixes-polish.test.ts passes unchanged (all its growth-page source assertions still hold), full-repo tsc --noEmit clean, lint clean, real NODE_ENV=production next build exit 0', 'REAL_EXPOSED', 'Continuation of Update 48 (which added the equivalent card to Admin Home) -- both interfaces now share the identical real diagnosis, not two separately-maintained implementations.', null, now(), 'claude_session_2026-09-02')
on conflict (capability_key) do nothing;
