-- Records the Value Ledger's persistence fix and its two new real agent
-- tools. Applied live via Supabase MCP on 2026-09-02; this file makes it
-- reproducible from a fresh database.

update public.capability_registry
set status = 'REAL_EXPOSED',
    status_notes = status_notes || ' CLOSED 2026-09-02 (remaining capability bridges pass): ValueLedgerService (lib/reporting/value-ledger.ts) is now real, Postgres-backed persistence (value_ledger_entries table, service-role-only RLS) instead of a private in-memory array -- every method was already declared async, so no caller anywhere needed to change signature, only implementation. Two new real agent tools bridge it: record_service_deliverable (low_mutation, staff records a real completed deliverable) and get_monthly_value_report (read, real aggregation from real recorded entries). Fixing this surfaced and fixed three further real, previously-latent issues in the same pass: (1) a TypeScript parameter-property constructor shorthand does not survive node --experimental-strip-types (had to use an explicit field + constructor body instead) -- a real language-tooling constraint, not previously hit this session; (2) the real Supabase client had to be resolved via lib/supabase/service.ts''s createSupabaseServiceClient directly, NOT lib/tenants/tenant-context.ts''s getTenantServiceContext, because the latter carries `import "server-only"` and a transitive next/headers import that fails to load under plain node at all -- confirmed live while building this fix; (3) three real, pre-existing tests that directly constructed `new ValueLedgerService()` (lib/billing/__tests__/monthly-adaptive-renewal.test.ts, packages/whatsapp/src/__tests__/whatsapp-copilot-flow.test.ts, packages/workforce-core/src/__tests__/autonomous-growth-e2e.test.ts) needed a constructor-injectable fake supabase client to stay isolated from any live database -- added the same injection point MonthlyRenewalEngine.execute26thMonthlyReport''s own `ledger?:` override already used for the same reason. While re-verifying these, also found and fixed a genuinely separate, pre-existing bug unrelated to this change: autonomous-growth-e2e.test.ts hardcoded cycleMonth "2026-08" for deliverables the WhatsApp copilot''s ASK_TODAYS_WORK handler reads back using the REAL current wall-clock month -- a real date-hardcoded fragility that would fail every month after August 2026 regardless of any code change, caught only because this pass actually re-ran a test not wired into any npm script. MonthlyRenewalEngine''s own generatedRecapCache (in-memory Map, composing this service with plan-proposal generation into a fuller renewal-recap package) remains deliberately unwired -- a distinct, larger piece of work than closing the core ledger itself.',
    external_blocker = null,
    last_verified_at = now(), last_verified_by = 'claude_session_2026-09-02'
where capability_key = 'capability:monthly_value_ledger_engine';
