import assert from "node:assert/strict";
import { assertPublicHttpTarget, crawlWebsite, CRAWL_LIMITS, HARD_CRAWL_CEILING, normalizeCrawlUrl, retryDelayMs, schedulerCanRun, SEARCH_MAX_ATTEMPTS, SEARCH_RUNTIME_FLAGS, stableFingerprint } from "../index.ts";
const publicResolver: any = async () => [{ address: "93.184.216.34", family: 4 }];
await assert.rejects(() => assertPublicHttpTarget(new URL("http://localhost"), publicResolver), /PRIVATE/);
await assert.rejects(() => assertPublicHttpTarget(new URL("http://127.0.0.1"), publicResolver), /PRIVATE/);
await assert.rejects(() => assertPublicHttpTarget(new URL("http://169.254.1.2"), publicResolver), /PRIVATE/);
await assert.rejects(() => assertPublicHttpTarget(new URL("https://example.com:8443"), publicResolver), /NOT_ALLOWED/);
assert.equal(normalizeCrawlUrl("https://example.com/a/?utm=x#part").href, "https://example.com/a");
assert.equal(stableFingerprint(["Tenant", "HTTPS://EXAMPLE.COM/"]), stableFingerprint(["tenant", "https://example.com/"]));
assert.equal(new Set(Object.values(CRAWL_LIMITS)).size, 5); assert.ok(Math.max(...Object.values(CRAWL_LIMITS)) <= HARD_CRAWL_CEILING);
const html = (links: string) => `<html><head><title>Example page title</title><meta name="description" content="Useful page"><link rel="canonical" href="https://example.com/"><script type="application/ld+json">{"@type":"LocalBusiness"}</script></head><body><h1>Page</h1><img src="a.jpg" alt="Office">${links}</body></html>`;
const fetcher: any = async (url: URL) => { if (url.pathname === "/file.pdf") return new Response("pdf", { headers: { "content-type": "application/pdf" } }); if (url.pathname === "/redirect") return new Response(null, { status: 302, headers: { location: "/final" } }); return new Response(html('<a href="/two?x=1#part">Two</a><a href="https://other.example/out">Out</a><a href="/login">Login</a><a href="/file.pdf">PDF</a>'), { status: 200, headers: { "content-type": "text/html" } }); };
const crawled = await crawlWebsite("https://example.com", { fetcher, resolver: publicResolver, limits: { maxPages: 2, maxDepth: 2, totalTimeoutMs: 5000 } });
assert.equal(crawled.pages.length, 2, "page cap must apply"); assert.equal(crawled.pages.some((p) => p.url.includes("other.example")), false, "same-origin only"); assert.equal(crawled.pages[0].structuredDataTypes?.[0], "LocalBusiness");
const timeoutFetcher: any = async (url: URL, init: RequestInit) => url.pathname === "/robots.txt" || url.pathname === "/sitemap.xml" ? new Response("", { status: 404 }) : await new Promise((_resolve, reject) => init.signal?.addEventListener("abort", () => reject(new Error("aborted"))));
const timed = await crawlWebsite("https://example.com", { fetcher: timeoutFetcher, resolver: publicResolver, limits: { requestTimeoutMs: 5, totalTimeoutMs: 50, maxPages: 1 } }); assert.equal(timed.errors.length, 1);
assert.equal(SEARCH_RUNTIME_FLAGS.schedulerEnabled, false); assert.equal(SEARCH_RUNTIME_FLAGS.crawlEnabled, false); assert.equal(schedulerCanRun(), false);
assert.equal(retryDelayMs(1), 1000); assert.equal(retryDelayMs(SEARCH_MAX_ATTEMPTS), null);
console.log("runtime.test.ts: ALL PASS (SSRF, origin, normalization, caps, filtering, timeout, flags, retry)");
